<#
.SYNOPSIS
Performs one fixed, verified MCC Windows update or manual Administrator update.

.DESCRIPTION
Uses only the protected Administrator-installed configuration. The script verifies
origin/main, a clean fast-forward worktree, semantic versions, and the server-issued
target before stopping the one managed MCC task. It creates an external safety
backup, installs locked dependencies, builds, starts, health-checks, and rolls back
automatically after a post-change failure.

.PARAMETER ConfigurationPath
The fixed protected configuration path.

.PARAMETER RequestPath
The fixed request generated by the protected MCC API and detected by the agent.

.PARAMETER Manual
Derives the target from a fresh origin/main fetch. No target, branch, repository,
command, version, or commit can be supplied.
#>
[CmdletBinding(DefaultParameterSetName = 'Agent')]
param(
    [Parameter(Mandatory = $true)]
    [string]$ConfigurationPath,

    [Parameter(Mandatory = $true, ParameterSetName = 'Agent')]
    [string]$RequestPath,

    [Parameter(Mandatory = $true, ParameterSetName = 'Manual')]
    [switch]$Manual
)

Set-StrictMode -Version Latest
$ErrorActionPreference = 'Stop'
$ProgressPreference = 'SilentlyContinue'

Import-Module (Join-Path $PSScriptRoot 'MccWindowsUpdater.Common.psm1') -Force
Assert-MccAdministrator
$constants = Get-MccUpdaterConstants
$configuration = Read-MccWindowsConfiguration -ConfigurationPath $ConfigurationPath
$applicationPath = [string]$configuration.applicationPath
$env:PATH = "$(Split-Path -Parent ([string]$configuration.gitPath));$(Split-Path -Parent ([string]$configuration.nodePath));$env:PATH"
$statusPath = Join-Path $constants.UpdaterRoot 'status\status.json'
$fixedRequestPath = Join-Path $constants.UpdaterRoot 'request\request.json'
$lockPath = Join-Path $constants.UpdaterRoot 'updater.lock'
$backupRoot = Join-Path $constants.UpdaterRoot 'backups'
$logDirectory = Join-Path $constants.UpdaterRoot 'logs'
$detailedLogPath = Join-Path $logDirectory "update-$([DateTime]::UtcNow.ToString('yyyyMMddTHHmmssZ'))-$PID.log"
$terminalStates = @('succeeded', 'rolled_back', 'failed')
$validStates = @(
    'idle', 'checking', 'update_available', 'queued', 'backing_up', 'stopping', 'pulling',
    'installing_dependencies', 'building', 'starting', 'health_check', 'succeeded',
    'rolling_back', 'rolled_back', 'failed'
)

$script:JobId = ''
$script:RequestedAt = $null
$script:Requester = [ordered]@{ id = 0; name = 'Local Windows Administrator' }
$script:InstalledVersion = $null
$script:InstalledCommit = $null
$script:TargetVersion = $null
$script:TargetCommit = $null
$script:BackupDirectory = $null
$script:CodeChanged = $false
$script:MccStopped = $false
$lockStream = $null

function Write-UpdateLog {
    param([Parameter(Mandatory = $true)][string]$Message)
    $safeMessage = Get-MccCleanText -Value $Message -Maximum 1000
    Add-Content -LiteralPath $detailedLogPath -Value "[$([DateTime]::UtcNow.ToString('o'))] $safeMessage" -Encoding utf8
}

function Write-UpdateStatus {
    param(
        [Parameter(Mandatory = $true)][ValidateSet(
            'idle', 'checking', 'update_available', 'queued', 'backing_up', 'stopping', 'pulling',
            'installing_dependencies', 'building', 'starting', 'health_check', 'succeeded',
            'rolling_back', 'rolled_back', 'failed'
        )][string]$State,
        [Parameter(Mandatory = $true)][string]$Message,
        [ValidateSet('none', 'succeeded', 'rolled_back', 'failed')][string]$Outcome = 'none'
    )
    if ($validStates -notcontains $State) {
        throw 'An invalid updater state was rejected.'
    }
    $timestamp = [DateTime]::UtcNow.ToString('o')
    $existing = $null
    if (Test-Path -LiteralPath $statusPath -PathType Leaf) {
        try { $existing = Read-MccJson -LiteralPath $statusPath } catch { $existing = $null }
    }
    $events = [Collections.Generic.List[object]]::new()
    if ($null -ne $existing -and $null -ne $existing.events) {
        @($existing.events) | Select-Object -Last 79 | ForEach-Object { $events.Add($_) }
    }
    $events.Add([ordered]@{
        id = "$(Get-MccCleanText -Value $script:JobId -Maximum 120):${State}:$timestamp"
        state = $State
        at = $timestamp
        message = Get-MccCleanText -Value $Message
    })
    $startedAt = if ($null -ne $existing -and [string]$existing.jobId -eq $script:JobId -and $existing.startedAt) {
        [string]$existing.startedAt
    } else {
        $timestamp
    }
    $code = if ($terminalStates -contains $State) { $State } elseif ($State -eq 'queued') { 'queued' } else { 'checking' }
    $environmentLabel = if ([string]$configuration.deploymentMode -eq 'WindowsTest') { 'WINDOWS TEST MODE' } else { 'WINDOWS 11 PRODUCTION' }
    $mode = if ([string]$configuration.deploymentMode -eq 'WindowsTest') { 'windows_test' } else { 'windows_production' }
    Write-MccAtomicJson -LiteralPath $statusPath -Value ([ordered]@{
        schemaVersion = 1
        jobId = Get-MccCleanText -Value $script:JobId -Maximum 120
        state = $State
        code = $code
        message = Get-MccCleanText -Value $Message
        mode = $mode
        environmentLabel = $environmentLabel
        installed = [ordered]@{ version = $script:InstalledVersion; commit = $script:InstalledCommit }
        target = [ordered]@{ version = $script:TargetVersion; commit = $script:TargetCommit }
        requestedAt = $script:RequestedAt
        startedAt = $startedAt
        lastUpdatedAt = $timestamp
        completedAt = if ($terminalStates -contains $State) { $timestamp } else { $null }
        requester = $script:Requester
        outcome = $Outcome
        finalResult = $Outcome
        checkToken = $null
        checkExpiresAt = $null
        events = $events
    })
}

function Get-RemotePackageVersion {
    param([Parameter(Mandatory = $true)][string]$Commit)
    $manifestText = (Invoke-MccGit -ApplicationPath $applicationPath -ArgumentList @('show', "$Commit`:package.json") -DetailedLogPath $detailedLogPath).StandardOutput
    try { $manifest = $manifestText | ConvertFrom-Json } catch { throw 'The approved target package metadata is invalid.' }
    if (-not (Test-MccSemver -Value $manifest.version)) {
        throw 'The approved target package version is invalid.'
    }
    return [string]$manifest.version
}

function Stop-MccManagedTask {
    $task = Get-ScheduledTask -TaskName $constants.MccTaskName -ErrorAction SilentlyContinue
    if ($null -eq $task) {
        throw 'The managed MCC background task is not installed.'
    }
    $processStatePath = Join-Path $constants.UpdaterRoot 'web-logs\mcc-process.json'
    $managedProcessId = 0
    if (Test-Path -LiteralPath $processStatePath -PathType Leaf) {
        try {
            $processState = Read-MccJson -LiteralPath $processStatePath
            $processId = 0
            if ([int]::TryParse([string]$processState.processId, [ref]$processId) -and $processId -gt 0) {
                $managedProcess = Get-Process -Id $processId -ErrorAction SilentlyContinue
                if ($null -ne $managedProcess) {
                    $expectedNode = Get-MccNormalizedPath -LiteralPath ([string]$configuration.nodePath)
                    $actualNode = Get-MccNormalizedPath -LiteralPath ([string]$managedProcess.Path)
                    if (-not $actualNode.Equals($expectedNode, [StringComparison]::OrdinalIgnoreCase)) {
                        throw 'The stored MCC PID does not identify the configured Node.js process.'
                    }
                    $managedProcessId = $processId
                    Write-MccAtomicJson -LiteralPath (Join-Path $constants.UpdaterRoot 'request\shutdown-request.json') -Value ([ordered]@{
                        schemaVersion = 1
                        processId = $managedProcessId
                        requestedAt = [DateTime]::UtcNow.ToString('o')
                    })
                    Wait-Process -Id $managedProcessId -Timeout 20 -ErrorAction SilentlyContinue
                }
            }
        } catch {
            if ($_.Exception.Message -match 'stored MCC PID') { throw }
            Write-UpdateLog -Message 'The managed MCC task stopped without a readable child PID.'
        }
    }
    Stop-ScheduledTask -TaskName $constants.MccTaskName -ErrorAction SilentlyContinue
    $script:MccStopped = $true
    if ($managedProcessId -gt 0 -and $null -ne (Get-Process -Id $managedProcessId -ErrorAction SilentlyContinue)) {
        Write-UpdateLog -Message 'The graceful shutdown timed out; stopping only the verified configured MCC Node.js PID.'
        Stop-Process -Id $managedProcessId -Force -ErrorAction Stop
        Wait-Process -Id $managedProcessId -Timeout 10 -ErrorAction SilentlyContinue
    }
}

function Start-MccManagedTask {
    Start-ScheduledTask -TaskName $constants.MccTaskName
}

function New-MccRuntimeBackup {
    $backupName = "$([DateTime]::UtcNow.ToString('yyyyMMddTHHmmssZ'))-$($script:InstalledVersion)-before-$($script:TargetVersion)"
    $destination = Join-Path $backupRoot $backupName
    $runtimeDestination = Join-Path $destination 'runtime'
    [System.IO.Directory]::CreateDirectory($runtimeDestination) | Out-Null
    $runtimePaths = @('backend\data', 'backend\uploads', 'backend\documents', 'backend\files', 'backend\.env', '.env')
    foreach ($relativePath in $runtimePaths) {
        $source = Join-Path $applicationPath $relativePath
        if (-not (Test-Path -LiteralPath $source)) { continue }
        $target = Join-Path $runtimeDestination $relativePath
        $targetParent = Split-Path -Parent $target
        [System.IO.Directory]::CreateDirectory($targetParent) | Out-Null
        Copy-Item -LiteralPath $source -Destination $target -Recurse -Force
    }
    $configurationSnapshot = [ordered]@{
        schemaVersion = 1
        deploymentMode = [string]$configuration.deploymentMode
        repository = $constants.Repository
        remote = $constants.Remote
        branch = $constants.Branch
        port = $constants.Port
        mccTaskName = $constants.MccTaskName
        updaterTaskName = $constants.UpdaterTaskName
    }
    Write-MccAtomicJson -LiteralPath (Join-Path $destination 'configuration-snapshot.json') -Value $configurationSnapshot
    $hashes = @(
        Get-ChildItem -LiteralPath $runtimeDestination -File -Recurse -Force | ForEach-Object {
            [ordered]@{
                relativePath = $_.FullName.Substring($runtimeDestination.Length).TrimStart('\').Replace('\', '/')
                length = $_.Length
                sha256 = (Get-FileHash -LiteralPath $_.FullName -Algorithm SHA256).Hash.ToLowerInvariant()
            }
        }
    )
    Write-MccAtomicJson -LiteralPath (Join-Path $destination 'backup-verification.json') -Value ([ordered]@{
        schemaVersion = 1
        algorithm = 'SHA256'
        files = $hashes
    })
    Write-MccAtomicJson -LiteralPath (Join-Path $destination 'job-metadata.json') -Value ([ordered]@{
        schemaVersion = 1
        jobId = $script:JobId
        requestedAt = $script:RequestedAt
        previousCommit = $script:InstalledCommit
        targetCommit = $script:TargetCommit
        previousVersion = $script:InstalledVersion
        targetVersion = $script:TargetVersion
        deploymentMode = [string]$configuration.deploymentMode
        createdAt = [DateTime]::UtcNow.ToString('o')
    })
    $verification = Read-MccJson -LiteralPath (Join-Path $destination 'backup-verification.json')
    foreach ($item in @($verification.files)) {
        $filePath = Join-Path $runtimeDestination ([string]$item.relativePath).Replace('/', '\')
        if (-not (Test-Path -LiteralPath $filePath -PathType Leaf) -or
            (Get-FileHash -LiteralPath $filePath -Algorithm SHA256).Hash.ToLowerInvariant() -ne [string]$item.sha256) {
            throw 'The pre-update runtime backup failed verification.'
        }
    }
    return $destination
}

function Restore-MccRuntimeBackup {
    param([Parameter(Mandatory = $true)][string]$BackupDirectory)
    $runtimeSource = Join-Path $BackupDirectory 'runtime'
    $verificationPath = Join-Path $BackupDirectory 'backup-verification.json'
    if (-not (Test-Path -LiteralPath $runtimeSource -PathType Container) -or
        -not (Test-Path -LiteralPath $verificationPath -PathType Leaf)) {
        throw 'The verified runtime backup required for rollback is missing.'
    }
    $verification = Read-MccJson -LiteralPath $verificationPath
    foreach ($item in @($verification.files)) {
        $source = Join-Path $runtimeSource ([string]$item.relativePath).Replace('/', '\')
        if (-not (Test-Path -LiteralPath $source -PathType Leaf) -or
            (Get-FileHash -LiteralPath $source -Algorithm SHA256).Hash.ToLowerInvariant() -ne [string]$item.sha256) {
            throw 'The runtime backup hash verification failed during rollback.'
        }
    }
    $runtimePaths = @('backend\data', 'backend\uploads', 'backend\documents', 'backend\files', 'backend\.env', '.env')
    foreach ($relativePath in $runtimePaths) {
        $source = Join-Path $runtimeSource $relativePath
        if (-not (Test-Path -LiteralPath $source)) { continue }
        $destination = Join-Path $applicationPath $relativePath
        $normalizedDestination = Get-MccNormalizedPath -LiteralPath $destination
        if (-not ($normalizedDestination + '\').StartsWith($applicationPath + '\', [StringComparison]::OrdinalIgnoreCase)) {
            throw 'Rollback refused an invalid runtime destination.'
        }
        if (Test-Path -LiteralPath $destination) {
            Remove-Item -LiteralPath $destination -Recurse -Force
        }
        [System.IO.Directory]::CreateDirectory((Split-Path -Parent $destination)) | Out-Null
        Copy-Item -LiteralPath $source -Destination $destination -Recurse -Force
    }
}

function Find-MccJobBackup {
    param([Parameter(Mandatory = $true)][string]$JobId)
    foreach ($directory in @(Get-ChildItem -LiteralPath $backupRoot -Directory -ErrorAction SilentlyContinue | Sort-Object LastWriteTimeUtc -Descending)) {
        $metadataPath = Join-Path $directory.FullName 'job-metadata.json'
        if (-not (Test-Path -LiteralPath $metadataPath -PathType Leaf)) { continue }
        try {
            $metadata = Read-MccJson -LiteralPath $metadataPath
            if ([string]$metadata.jobId -eq $JobId) {
                return $directory.FullName
            }
        } catch {}
    }
    return $null
}

function Install-MccLockedDependencies {
    foreach ($project in @('frontend', 'backend')) {
        Invoke-MccProcess -FilePath ([string]$configuration.nodePath) -ArgumentList @([string]$configuration.npmCliPath, 'ci', '--prefix', $project) -WorkingDirectory $applicationPath -TimeoutSeconds 900 -DetailedLogPath $detailedLogPath | Out-Null
    }
}

function Build-Mcc {
    Invoke-MccProcess -FilePath ([string]$configuration.nodePath) -ArgumentList @([string]$configuration.npmCliPath, 'run', 'build') -WorkingDirectory $applicationPath -TimeoutSeconds 900 -DetailedLogPath $detailedLogPath | Out-Null
}

try {
    [System.IO.Directory]::CreateDirectory($logDirectory) | Out-Null
    $lockStream = [System.IO.File]::Open($lockPath, [System.IO.FileMode]::OpenOrCreate, [System.IO.FileAccess]::ReadWrite, [System.IO.FileShare]::None)
    Write-UpdateLog -Message 'Acquired the exclusive Windows MCC updater lock.'
    Assert-MccApprovedApplicationPath -LiteralPath $applicationPath | Out-Null
    $nodeVersionResult = Invoke-MccProcess -FilePath ([string]$configuration.nodePath) -ArgumentList @('--version') -WorkingDirectory $applicationPath -TimeoutSeconds 15 -DetailedLogPath $detailedLogPath
    if ($nodeVersionResult.StandardOutput -notmatch '^v(?<major>\d+)\.' -or [int]$Matches.major -lt 22) {
        throw 'Node.js 22 or newer is required for an MCC update.'
    }
    Invoke-MccProcess -FilePath ([string]$configuration.nodePath) -ArgumentList @([string]$configuration.npmCliPath, '--version') -WorkingDirectory $applicationPath -TimeoutSeconds 15 -DetailedLogPath $detailedLogPath | Out-Null
    Assert-MccRepository -ApplicationPath $applicationPath -DetailedLogPath $detailedLogPath -RequireClean
    foreach ($requiredLock in @('package-lock.json', 'frontend\package-lock.json', 'backend\package-lock.json')) {
        if (-not (Test-Path -LiteralPath (Join-Path $applicationPath $requiredLock) -PathType Leaf)) {
            throw 'A required package-lock file is missing.'
        }
    }

    Invoke-MccGit -ApplicationPath $applicationPath -ArgumentList @('fetch', '--no-tags', $constants.Remote, "+refs/heads/$($constants.Branch):refs/remotes/$($constants.Remote)/$($constants.Branch)") -TimeoutSeconds 120 -DetailedLogPath $detailedLogPath | Out-Null
    $script:InstalledCommit = (Invoke-MccGit -ApplicationPath $applicationPath -ArgumentList @('rev-parse', 'HEAD') -DetailedLogPath $detailedLogPath).StandardOutput.ToLowerInvariant()
    $verifiedTargetCommit = (Invoke-MccGit -ApplicationPath $applicationPath -ArgumentList @('rev-parse', "refs/remotes/$($constants.Remote)/$($constants.Branch)") -DetailedLogPath $detailedLogPath).StandardOutput.ToLowerInvariant()
    if (-not (Test-MccCommit -Value $script:InstalledCommit) -or -not (Test-MccCommit -Value $verifiedTargetCommit)) {
        throw 'Installed or target commit metadata is invalid.'
    }
    Invoke-MccGit -ApplicationPath $applicationPath -ArgumentList @('merge-base', '--is-ancestor', $script:InstalledCommit, $verifiedTargetCommit) -DetailedLogPath $detailedLogPath | Out-Null
    $script:InstalledVersion = Get-MccPackageVersion -ApplicationPath $applicationPath
    $verifiedTargetVersion = Get-RemotePackageVersion -Commit $verifiedTargetCommit

    if ($Manual) {
        $script:JobId = [Guid]::NewGuid().ToString()
        $script:RequestedAt = [DateTime]::UtcNow.ToString('o')
        $script:TargetCommit = $verifiedTargetCommit
        $script:TargetVersion = $verifiedTargetVersion
    } else {
        $normalizedRequestPath = Get-MccNormalizedPath -LiteralPath $RequestPath
        if (-not $normalizedRequestPath.Equals($fixedRequestPath, [StringComparison]::OrdinalIgnoreCase)) {
            throw 'The updater agent refused a non-fixed request location.'
        }
        $request = Read-MccJson -LiteralPath $fixedRequestPath
        $parsedJobId = [Guid]::Empty
        $requestTime = [DateTime]::MinValue
        if ([int]$request.schemaVersion -ne 1 -or
            -not [Guid]::TryParse([string]$request.jobId, [ref]$parsedJobId) -or
            -not [DateTime]::TryParse([string]$request.requestedAt, [ref]$requestTime) -or
            [DateTime]::UtcNow.Subtract($requestTime.ToUniversalTime()).TotalMinutes -gt 30 -or
            $requestTime.ToUniversalTime().Subtract([DateTime]::UtcNow).TotalMinutes -gt 5 -or
            [string]$request.source.repository -ne $constants.Repository -or
            [string]$request.source.remote -ne $constants.Remote -or
            [string]$request.source.branch -ne $constants.Branch -or
            [int]$request.source.port -ne $constants.Port -or
            -not (Test-MccCommit -Value $request.installed.commit) -or
            -not (Test-MccCommit -Value $request.target.commit) -or
            -not (Test-MccSemver -Value $request.installed.version) -or
            -not (Test-MccSemver -Value $request.target.version)) {
            throw 'The fixed MCC update request is invalid or stale.'
        }
        $script:JobId = $parsedJobId.ToString()
        $script:RequestedAt = $requestTime.ToUniversalTime().ToString('o')
        $script:Requester = [ordered]@{
            id = [Math]::Max(0, [int]$request.requester.id)
            name = Get-MccCleanText -Value $request.requester.name -Maximum 120
        }
        $script:TargetCommit = ([string]$request.target.commit).ToLowerInvariant()
        $script:TargetVersion = [string]$request.target.version
        $requestInstalledCommit = ([string]$request.installed.commit).ToLowerInvariant()
        $requestInstalledVersion = [string]$request.installed.version
        $persistedStatus = $null
        if (Test-Path -LiteralPath $statusPath -PathType Leaf) {
            try { $persistedStatus = Read-MccJson -LiteralPath $statusPath } catch { $persistedStatus = $null }
        }
        if ($null -ne $persistedStatus -and [string]$persistedStatus.jobId -eq $script:JobId -and
            @('succeeded', 'rolled_back') -contains [string]$persistedStatus.state -and
            (($persistedStatus.state -eq 'succeeded' -and $script:InstalledCommit -eq $script:TargetCommit) -or
             ($persistedStatus.state -eq 'rolled_back' -and $script:InstalledCommit -eq $requestInstalledCommit))) {
            Remove-Item -LiteralPath $fixedRequestPath -Force
            Write-UpdateLog -Message 'Removed a completed update request left behind by an interrupted cleanup.'
            return
        }
        if ($script:InstalledCommit -eq $script:TargetCommit -and $requestInstalledCommit -ne $script:TargetCommit) {
            $script:InstalledCommit = $requestInstalledCommit
            $script:InstalledVersion = $requestInstalledVersion
            $script:BackupDirectory = Find-MccJobBackup -JobId $script:JobId
            $script:CodeChanged = $true
            throw 'An interrupted Windows update was detected after code changed. Automatic rollback is starting.'
        }
        if ($script:InstalledCommit -ne ([string]$request.installed.commit).ToLowerInvariant() -or
            $script:InstalledVersion -ne $requestInstalledVersion -or
            $script:TargetCommit -ne $verifiedTargetCommit -or
            $script:TargetVersion -ne $verifiedTargetVersion) {
            throw 'The server-verified update target is stale. Run a new update check.'
        }
    }
    if ($script:InstalledCommit -eq $script:TargetCommit) {
        throw 'The approved origin/main commit is already installed.'
    }

    Write-UpdateStatus -State 'stopping' -Message 'Stopping only the managed Maintenance Command Center background task.'
    Stop-MccManagedTask

    Write-UpdateStatus -State 'backing_up' -Message 'Creating and verifying the external pre-update runtime-data backup.'
    $script:BackupDirectory = New-MccRuntimeBackup

    Write-UpdateStatus -State 'pulling' -Message 'Fast-forwarding the approved main branch to the server-verified target.'
    Invoke-MccGit -ApplicationPath $applicationPath -ArgumentList @('merge', '--ff-only', $script:TargetCommit) -DetailedLogPath $detailedLogPath | Out-Null
    $script:CodeChanged = $true

    Write-UpdateStatus -State 'installing_dependencies' -Message 'Installing locked frontend and backend dependencies.'
    Install-MccLockedDependencies

    Write-UpdateStatus -State 'building' -Message 'Building the MCC frontend and backend.'
    Build-Mcc

    Write-UpdateStatus -State 'starting' -Message 'Starting the managed Maintenance Command Center background task.'
    Start-MccManagedTask

    Write-UpdateStatus -State 'health_check' -Message 'Health-checking the managed MCC application on port 4273.'
    if (-not (Test-MccHttpHealth -Port $constants.Port -TimeoutSeconds 120)) {
        throw 'The updated MCC health check failed on port 4273.'
    }
    $installedAfter = (Invoke-MccGit -ApplicationPath $applicationPath -ArgumentList @('rev-parse', 'HEAD') -DetailedLogPath $detailedLogPath).StandardOutput.ToLowerInvariant()
    if ($installedAfter -ne $script:TargetCommit -or (Get-MccPackageVersion -ApplicationPath $applicationPath) -ne $script:TargetVersion) {
        throw 'The running MCC commit or application version does not match the approved target.'
    }
    $script:InstalledCommit = $script:TargetCommit
    $script:InstalledVersion = $script:TargetVersion
    Write-UpdateStatus -State 'succeeded' -Message 'The Windows MCC update completed and passed commit, version, and port 4273 health verification.' -Outcome 'succeeded'
    if (-not $Manual -and (Test-Path -LiteralPath $fixedRequestPath -PathType Leaf)) {
        Remove-Item -LiteralPath $fixedRequestPath -Force
    }
    Write-UpdateLog -Message 'The update completed successfully. The pre-update backup was retained.'
} catch {
    $safeFailure = Get-MccCleanText -Value $_.Exception.Message -Maximum 500
    Write-UpdateLog -Message $safeFailure
    if (-not $Manual -and -not $script:JobId -and (Test-Path -LiteralPath $fixedRequestPath -PathType Leaf)) {
        $script:JobId = [Guid]::NewGuid().ToString()
        $script:RequestedAt = [DateTime]::UtcNow.ToString('o')
        try {
            $blockedRequest = Read-MccJson -LiteralPath $fixedRequestPath
            $blockedJobId = [Guid]::Empty
            if ([Guid]::TryParse([string]$blockedRequest.jobId, [ref]$blockedJobId)) {
                $script:JobId = $blockedJobId.ToString()
            }
            $blockedRequestTime = [DateTime]::MinValue
            if ([DateTime]::TryParse([string]$blockedRequest.requestedAt, [ref]$blockedRequestTime)) {
                $script:RequestedAt = $blockedRequestTime.ToUniversalTime().ToString('o')
            }
            $script:Requester = [ordered]@{
                id = [Math]::Max(0, [int]$blockedRequest.requester.id)
                name = Get-MccCleanText -Value $blockedRequest.requester.name -Maximum 120
            }
        } catch {}
    }
    if ($script:JobId -and ($script:CodeChanged -or $script:MccStopped)) {
        try {
            Write-UpdateStatus -State 'rolling_back' -Message 'The update failed. Restoring the previous MCC commit and runtime data.'
            Stop-MccManagedTask
            if ($script:CodeChanged -and -not $script:BackupDirectory) {
                throw 'The verified safety backup required for interrupted-update rollback is missing.'
            }
            if ($script:CodeChanged) {
                $currentCommit = (Invoke-MccGit -ApplicationPath $applicationPath -ArgumentList @('rev-parse', 'HEAD') -DetailedLogPath $detailedLogPath).StandardOutput.ToLowerInvariant()
                Invoke-MccGit -ApplicationPath $applicationPath -ArgumentList @('update-ref', "refs/heads/$($constants.Branch)", $script:InstalledCommit, $currentCommit) -DetailedLogPath $detailedLogPath | Out-Null
                Invoke-MccGit -ApplicationPath $applicationPath -ArgumentList @('read-tree', '--reset', '-u', $script:InstalledCommit) -DetailedLogPath $detailedLogPath | Out-Null
            }
            if ($script:BackupDirectory) {
                Restore-MccRuntimeBackup -BackupDirectory $script:BackupDirectory
            }
            Install-MccLockedDependencies
            Build-Mcc
            Start-MccManagedTask
            if (-not (Test-MccHttpHealth -Port $constants.Port -TimeoutSeconds 120)) {
                throw 'The previous MCC version did not pass its rollback health check.'
            }
            if ((Invoke-MccGit -ApplicationPath $applicationPath -ArgumentList @('rev-parse', 'HEAD') -DetailedLogPath $detailedLogPath).StandardOutput.ToLowerInvariant() -ne $script:InstalledCommit -or
                (Get-MccPackageVersion -ApplicationPath $applicationPath) -ne $script:InstalledVersion) {
                throw 'Rollback commit or version verification failed.'
            }
            Write-UpdateStatus -State 'rolled_back' -Message 'The update failed - the previous MCC version was restored and passed its health check.' -Outcome 'rolled_back'
            Write-UpdateLog -Message 'Automatic rollback completed successfully.'
        } catch {
            $rollbackFailure = Get-MccCleanText -Value $_.Exception.Message -Maximum 500
            Write-UpdateLog -Message "Critical rollback failure. $rollbackFailure"
            Write-UpdateStatus -State 'failed' -Message 'Critical update failure - manual recovery is required. The safety backup and Administrator logs were preserved.' -Outcome 'failed'
            Set-Content -LiteralPath (Join-Path $logDirectory "MANUAL-RECOVERY-$($script:JobId).txt") -Encoding utf8 -Value @(
                'CRITICAL MCC UPDATE FAILURE'
                "Job: $($script:JobId)"
                "Previous commit: $($script:InstalledCommit)"
                "Target commit: $($script:TargetCommit)"
                "Backup: $($script:BackupDirectory)"
                "Detailed log: $detailedLogPath"
                'Run Test-MccWindowsUpdater.ps1 and follow README-Windows-Updater.md recovery procedures.'
            )
        }
    } elseif ($script:JobId) {
        Write-UpdateStatus -State 'failed' -Message "The update was blocked before installed code changed. $safeFailure" -Outcome 'failed'
    }
    throw
} finally {
    if (-not $Manual -and $script:JobId -and (Test-Path -LiteralPath $fixedRequestPath -PathType Leaf)) {
        Remove-Item -LiteralPath $fixedRequestPath -Force -ErrorAction SilentlyContinue
    }
    if ($null -ne $lockStream) {
        $lockStream.Dispose()
    }
}
