<#
.SYNOPSIS
Performs one fixed, verified MCC Windows update or manual Administrator update.

.DESCRIPTION
Uses only the protected Administrator-installed configuration. The script verifies
the configured origin branch, a clean fast-forward worktree, semantic versions, and
the server-issued target before stopping the one managed MCC task. It creates an
external safety backup, installs locked dependencies, builds, starts, health-checks,
and rolls back automatically after a post-change failure.

.PARAMETER ConfigurationPath
The fixed protected configuration path.

.PARAMETER RequestPath
The fixed request generated by the protected MCC API and detected by the agent.

.PARAMETER Manual
Derives the target from a fresh fetch of the protected configured branch. No target,
branch, repository, command, version, or commit can be supplied.
#>
[CmdletBinding(DefaultParameterSetName = 'Agent')]
param(
    [Parameter(Mandatory = $true)]
    [string]$ConfigurationPath,

    [Parameter(Mandatory = $true, ParameterSetName = 'Agent')]
    [string]$RequestPath,

    [Parameter(Mandatory = $true, ParameterSetName = 'Manual')]
    [switch]$Manual
)

Set-StrictMode -Version Latest
$ErrorActionPreference = 'Stop'
$ProgressPreference = 'SilentlyContinue'

Import-Module (Join-Path $PSScriptRoot 'MccWindowsUpdater.Common.psm1') -Force
Assert-MccAdministrator
$constants = Get-MccUpdaterConstants
$configuration = Read-MccWindowsConfiguration -ConfigurationPath $ConfigurationPath
$applicationPath = [string]$configuration.applicationPath
$configuredBranch = [string]$configuration.branch
$environmentLabel = if ([string]$configuration.deploymentMode -eq 'WindowsTest') { 'WINDOWS TEST MODE' } else { 'WINDOWS 11 PRODUCTION' }
Set-MccExecutablePathBootstrap -GitPath ([string]$configuration.gitPath) -NodePath ([string]$configuration.nodePath)
Set-MccGitRepositoryTrustBootstrap -ApplicationPath $applicationPath -ConfiguredApplicationPath ([string]$configuration.applicationPath)
$statusPath = Join-Path $constants.UpdaterRoot 'status\status.json'
$agentHealthPath = Join-Path $constants.UpdaterRoot 'status\agent-health.json'
$processStatePath = Join-Path $constants.UpdaterRoot 'web-logs\mcc-process.json'
$fixedRequestPath = Join-Path $constants.UpdaterRoot 'request\request.json'
$lockPath = Join-Path $constants.UpdaterRoot 'updater.lock'
$backupRoot = Join-Path $constants.UpdaterRoot 'backups'
$logDirectory = Join-Path $constants.UpdaterRoot 'logs'
$detailedLogPath = Join-Path $logDirectory "update-$([DateTime]::UtcNow.ToString('yyyyMMddTHHmmssZ'))-$PID.log"
$terminalStates = @('succeeded', 'rolled_back', 'failed')
$validStates = @(
    'idle', 'checking', 'update_available', 'queued', 'backing_up', 'stopping', 'pulling',
    'installing_dependencies', 'building', 'starting', 'health_check', 'succeeded',
    'rolling_back', 'rolled_back', 'failed'
)

$script:JobId = ''
$script:RequestedAt = $null
$script:Requester = [ordered]@{ id = 0; name = 'Local Windows Administrator' }
$script:InstalledVersion = $null
$script:InstalledCommit = $null
$script:TargetVersion = $null
$script:TargetCommit = $null
$script:BackupDirectory = $null
$script:CodeChanged = $false
$script:MccStopped = $false
$script:PreviousManagedProcessId = 0
$script:PreviousManagedLaunchId = ''
$lockStream = $null

function Write-UpdateLog {
    param([Parameter(Mandatory = $true)][string]$Message)
    $safeMessage = Get-MccCleanText -Value $Message -Maximum 1000
    Add-Content -LiteralPath $detailedLogPath -Value "[$([DateTime]::UtcNow.ToString('o'))] $safeMessage" -Encoding utf8
}

function Write-UpdateStatus {
    param(
        [Parameter(Mandatory = $true)][ValidateSet(
            'idle', 'checking', 'update_available', 'queued', 'backing_up', 'stopping', 'pulling',
            'installing_dependencies', 'building', 'starting', 'health_check', 'succeeded',
            'rolling_back', 'rolled_back', 'failed'
        )][string]$State,
        [Parameter(Mandatory = $true)][string]$Message,
        [ValidateSet('none', 'succeeded', 'rolled_back', 'failed')][string]$Outcome = 'none'
    )
    if ($validStates -notcontains $State) {
        throw 'An invalid updater state was rejected.'
    }
    $timestamp = [DateTime]::UtcNow.ToString('o')
    $existing = $null
    if (Test-Path -LiteralPath $statusPath -PathType Leaf) {
        try { $existing = Read-MccJson -LiteralPath $statusPath } catch { $existing = $null }
    }
    $events = [Collections.Generic.List[object]]::new()
    if ($null -ne $existing -and $null -ne $existing.events) {
        @($existing.events) | Select-Object -Last 79 | ForEach-Object { $events.Add($_) }
    }
    $events.Add([ordered]@{
        id = "$(Get-MccCleanText -Value $script:JobId -Maximum 120):${State}:$timestamp"
        state = $State
        at = $timestamp
        message = Get-MccCleanText -Value $Message
    })
    $startedAt = if ($null -ne $existing -and [string]$existing.jobId -eq $script:JobId -and $existing.startedAt) {
        [string]$existing.startedAt
    } else {
        $timestamp
    }
    $code = if ($terminalStates -contains $State) { $State } elseif ($State -eq 'queued') { 'queued' } else { 'checking' }
    $environmentLabel = if ([string]$configuration.deploymentMode -eq 'WindowsTest') { 'WINDOWS TEST MODE' } else { 'WINDOWS 11 PRODUCTION' }
    $mode = if ([string]$configuration.deploymentMode -eq 'WindowsTest') { 'windows_test' } else { 'windows_production' }
    Write-MccAtomicJson -LiteralPath $statusPath -Value ([ordered]@{
        schemaVersion = 1
        jobId = Get-MccCleanText -Value $script:JobId -Maximum 120
        state = $State
        code = $code
        message = Get-MccCleanText -Value $Message
        mode = $mode
        environmentLabel = $environmentLabel
        installed = [ordered]@{ version = $script:InstalledVersion; commit = $script:InstalledCommit }
        target = [ordered]@{ version = $script:TargetVersion; commit = $script:TargetCommit }
        requestedAt = $script:RequestedAt
        startedAt = $startedAt
        lastUpdatedAt = $timestamp
        completedAt = if ($terminalStates -contains $State) { $timestamp } else { $null }
        requester = $script:Requester
        outcome = $Outcome
        finalResult = $Outcome
        checkToken = $null
        checkExpiresAt = $null
        events = $events
    })
}

function Get-RemotePackageVersion {
    param([Parameter(Mandatory = $true)][string]$Commit)
    $manifestText = (Invoke-MccGit -ApplicationPath $applicationPath -ArgumentList @('show', "$Commit`:package.json") -DetailedLogPath $detailedLogPath).StandardOutput
    try { $manifest = $manifestText | ConvertFrom-Json } catch { throw 'The approved target package metadata is invalid.' }
    if (-not (Test-MccSemver -Value $manifest.version)) {
        throw 'The approved target package version is invalid.'
    }
    return [string]$manifest.version
}

function Get-MccManagedProcessRecord {
    if (-not (Test-Path -LiteralPath $processStatePath -PathType Leaf)) { return $null }
    try { return Read-MccJson -LiteralPath $processStatePath } catch { return $null }
}

function Get-MccManagedWin32Process {
    param([Parameter(Mandatory = $true)][int]$ProcessId)
    return Get-CimInstance -ClassName Win32_Process -Filter "ProcessId = $ProcessId" -ErrorAction SilentlyContinue
}

function Assert-MccManagedProcessIdentity {
    param(
        [Parameter(Mandatory = $true)][object]$Record,
        [switch]$RequireLauncherAttestation
    )
    $managedProcessId = 0
    if (-not [int]::TryParse([string]$Record.processId, [ref]$managedProcessId) -or $managedProcessId -le 0) {
        throw 'The managed launcher did not publish a valid MCC child PID.'
    }
    $processDetails = Get-MccManagedWin32Process -ProcessId $managedProcessId
    if ($null -eq $processDetails) { return $null }
    $expectedNode = Get-MccNormalizedPath -LiteralPath ([string]$configuration.nodePath)
    $expectedEntryPoint = Get-MccNormalizedPath -LiteralPath (Join-Path $applicationPath 'backend\dist\server\index.js')
    $actualNode = Get-MccNormalizedPath -LiteralPath ([string]$processDetails.ExecutablePath)
    $commandLine = ([string]$processDetails.CommandLine).Replace('"', '')
    if (-not $actualNode.Equals($expectedNode, [StringComparison]::OrdinalIgnoreCase) -or
        $commandLine.IndexOf($expectedEntryPoint, [StringComparison]::OrdinalIgnoreCase) -lt 0) {
        throw 'The stored MCC PID does not identify the configured managed backend process.'
    }
    if ($RequireLauncherAttestation) {
        $recordApplicationPath = Get-MccNormalizedPath -LiteralPath ([string]$Record.applicationPath)
        $recordEntryPoint = Get-MccNormalizedPath -LiteralPath ([string]$Record.entryPoint)
        $recordNodePath = Get-MccNormalizedPath -LiteralPath ([string]$Record.nodePath)
        $recordConfigurationPath = Get-MccNormalizedPath -LiteralPath ([string]$Record.configurationPath)
        if ($Record.applicationMatchesConfiguration -ne $true -or
            -not $recordApplicationPath.Equals($applicationPath, [StringComparison]::OrdinalIgnoreCase) -or
            -not $recordEntryPoint.Equals($expectedEntryPoint, [StringComparison]::OrdinalIgnoreCase) -or
            -not $recordNodePath.Equals($expectedNode, [StringComparison]::OrdinalIgnoreCase) -or
            -not $recordConfigurationPath.Equals((Get-MccNormalizedPath -LiteralPath $ConfigurationPath), [StringComparison]::OrdinalIgnoreCase) -or
            [string]$Record.managedEnvironment.updateMode -cne 'windows_agent' -or
            [string]$Record.managedEnvironment.nodeEnvironment -cne 'production') {
            throw 'The managed launcher attestation does not match the protected updater configuration.'
        }
    }
    return $processDetails
}

function Wait-MccScheduledTaskNotRunning {
    param([Parameter(Mandatory = $true)][string]$TaskName, [ValidateRange(1, 120)][int]$TimeoutSeconds = 30)
    $deadline = [DateTime]::UtcNow.AddSeconds($TimeoutSeconds)
    do {
        $task = Get-ScheduledTask -TaskName $TaskName -ErrorAction SilentlyContinue
        if ($null -eq $task) { throw 'A required managed MCC scheduled task is not installed.' }
        if ([string]$task.State -ne 'Running') { return }
        Start-Sleep -Milliseconds 500
    } while ([DateTime]::UtcNow -lt $deadline)
    throw 'The managed MCC scheduled task did not stop within the allowed time.'
}

function Wait-MccPortReleased {
    param([ValidateRange(1, 120)][int]$TimeoutSeconds = 30)
    $deadline = [DateTime]::UtcNow.AddSeconds($TimeoutSeconds)
    do {
        $listeners = @(Get-NetTCPConnection -LocalPort $constants.Port -State Listen -ErrorAction SilentlyContinue)
        if ($listeners.Count -eq 0) { return }
        Start-Sleep -Milliseconds 500
    } while ([DateTime]::UtcNow -lt $deadline)
    throw 'Port 4273 is still owned after the managed MCC task stopped. No unrelated process was terminated.'
}

function Stop-MccManagedTask {
    $task = Get-ScheduledTask -TaskName $constants.MccTaskName -ErrorAction SilentlyContinue
    if ($null -eq $task) { throw 'The managed MCC background task is not installed.' }
    $record = Get-MccManagedProcessRecord
    $managedProcessId = 0
    $managedProcess = $null
    if ($null -ne $record) {
        [void][int]::TryParse([string]$record.processId, [ref]$managedProcessId)
        $script:PreviousManagedProcessId = $managedProcessId
        $script:PreviousManagedLaunchId = [string]$record.launchId
        if ($managedProcessId -gt 0) {
            $managedProcess = Assert-MccManagedProcessIdentity -Record $record
        }
    }
    if ([string]$task.State -eq 'Running') {
        Stop-ScheduledTask -TaskName $constants.MccTaskName -ErrorAction Stop
    }
    $script:MccStopped = $true
    Wait-MccScheduledTaskNotRunning -TaskName $constants.MccTaskName
    $finalRecord = Get-MccManagedProcessRecord
    $finalRecordedProcessId = 0
    if ($null -ne $finalRecord -and
        [int]::TryParse([string]$finalRecord.processId, [ref]$finalRecordedProcessId) -and
        $finalRecordedProcessId -gt 0 -and
        $finalRecordedProcessId -ne $managedProcessId -and
        $null -ne (Get-MccManagedWin32Process -ProcessId $finalRecordedProcessId)) {
        [void](Assert-MccManagedProcessIdentity -Record $finalRecord)
        $record = $finalRecord
        $managedProcessId = $finalRecordedProcessId
        $script:PreviousManagedProcessId = $managedProcessId
        $script:PreviousManagedLaunchId = [string]$record.launchId
        Write-UpdateLog -Message 'The launcher recorded one final verified MCC child during task shutdown; that exact child will be stopped.'
    }
    if ($managedProcessId -gt 0 -and $null -ne (Get-MccManagedWin32Process -ProcessId $managedProcessId)) {
        [void](Assert-MccManagedProcessIdentity -Record $record)
        Write-MccAtomicJson -LiteralPath (Join-Path $constants.UpdaterRoot 'request\shutdown-request.json') -Value ([ordered]@{
            schemaVersion = 1
            processId = $managedProcessId
            requestedAt = [DateTime]::UtcNow.ToString('o')
        })
        $gracefulDeadline = [DateTime]::UtcNow.AddSeconds(20)
        while ($null -ne (Get-MccManagedWin32Process -ProcessId $managedProcessId) -and [DateTime]::UtcNow -lt $gracefulDeadline) {
            Start-Sleep -Milliseconds 500
        }
        if ($null -ne (Get-MccManagedWin32Process -ProcessId $managedProcessId)) {
            Write-UpdateLog -Message 'The graceful shutdown timed out; terminating only the verified recorded MCC child process tree.'
            $exactProcess = [Diagnostics.Process]::GetProcessById($managedProcessId)
            try {
                if (-not (Stop-MccExactProcessTreeFallback -Process $exactProcess)) {
                    throw 'The exact managed MCC process tree did not confirm termination.'
                }
            } finally {
                $exactProcess.Dispose()
            }
        }
    }
    Wait-MccPortReleased
    if (Test-Path -LiteralPath $processStatePath -PathType Leaf) {
        Remove-Item -LiteralPath $processStatePath -Force
    }
}

function Write-MccUpdaterHealthSnapshot {
    $mccTask = Get-ScheduledTask -TaskName $constants.MccTaskName -ErrorAction SilentlyContinue
    $updaterTask = Get-ScheduledTask -TaskName $constants.UpdaterTaskName -ErrorAction SilentlyContinue
    $repositoryValid = $false
    $branchValid = $false
    try {
        Assert-MccRepository -ApplicationPath $applicationPath -ExpectedBranch $configuredBranch
        $repositoryValid = $true
        $branchValid = $true
    } catch {}
    $health = New-MccWindowsAgentHealth `
        -HeartbeatCompleted $true `
        -ExecutableBootstrapSucceeded $true `
        -ConfigurationValid $true `
        -DeploymentMode ([string]$configuration.deploymentMode) `
        -ApplicationPathMatches (-not (Test-MccProtectedDevelopmentPath -LiteralPath $applicationPath)) `
        -RepositoryValid $repositoryValid `
        -BranchValid $branchValid `
        -RequestDirectoryAccessible (Test-Path -LiteralPath (Split-Path -Parent $fixedRequestPath) -PathType Container) `
        -StatusDirectoryAccessible (Test-Path -LiteralPath (Split-Path -Parent $statusPath) -PathType Container) `
        -MccTaskInstalled ($null -ne $mccTask) `
        -MccTaskRunning ($null -ne $mccTask -and [string]$mccTask.State -eq 'Running') `
        -UpdaterTaskInstalled ($null -ne $updaterTask) `
        -UpdaterTaskRunning ($null -ne $updaterTask -and [string]$updaterTask.State -eq 'Running')
    Write-MccAtomicJson -LiteralPath $agentHealthPath -Value $health
}

function Start-MccManagedTask {
    param(
        [Parameter(Mandatory = $true)][string]$ExpectedVersion,
        [Parameter(Mandatory = $true)][string]$ExpectedCommit,
        [switch]$AllowLegacyReadiness404
    )
    Wait-MccScheduledTaskNotRunning -TaskName $constants.MccTaskName
    $startupRequestedAt = [DateTime]::UtcNow
    Start-ScheduledTask -TaskName $constants.MccTaskName -ErrorAction Stop
    $expectedMode = if ([string]$configuration.deploymentMode -eq 'WindowsTest') { 'windows_test' } else { 'windows_production' }
    $deadline = [DateTime]::UtcNow.AddSeconds(180)
    $lastFailure = 'The managed launcher has not published a new process yet.'
    do {
        try {
            $mccTask = Get-ScheduledTask -TaskName $constants.MccTaskName -ErrorAction Stop
            $updaterTask = Get-ScheduledTask -TaskName $constants.UpdaterTaskName -ErrorAction Stop
            if ([string]$mccTask.State -ne 'Running' -or [string]$updaterTask.State -ne 'Running') {
                throw 'Both managed MCC scheduled tasks must be running.'
            }
            $record = Get-MccManagedProcessRecord
            if ($null -eq $record) { throw 'The managed launcher process record is not available.' }
            $newProcessId = 0
            if (-not [int]::TryParse([string]$record.processId, [ref]$newProcessId) -or $newProcessId -le 0) {
                throw 'The managed launcher process record does not contain a running child PID.'
            }
            $newLaunchId = [Guid]::Empty
            if (-not [Guid]::TryParse([string]$record.launchId, [ref]$newLaunchId)) {
                throw 'The managed launcher process record does not contain a valid launch ID.'
            }
            if ($newProcessId -eq $script:PreviousManagedProcessId -or
                ($script:PreviousManagedLaunchId -and $newLaunchId.ToString() -ceq $script:PreviousManagedLaunchId)) {
                throw 'The managed launcher has not published a distinct replacement process.'
            }
            $startedAt = [DateTime]::MinValue
            if (-not [DateTime]::TryParse([string]$record.startedAt, [ref]$startedAt) -or $startedAt.ToUniversalTime() -lt $startupRequestedAt.AddSeconds(-2)) {
                throw 'The managed launcher process record is stale.'
            }
            $processDetails = Assert-MccManagedProcessIdentity -Record $record -RequireLauncherAttestation
            if ($null -eq $processDetails) {
                throw 'The newly recorded managed MCC process is not running.'
            }
            $listeners = @(Get-NetTCPConnection -LocalPort $constants.Port -State Listen -ErrorAction SilentlyContinue)
            if ($listeners.Count -ne 1 -or [int]$listeners[0].OwningProcess -ne $newProcessId) {
                throw 'Port 4273 is not owned by the newly recorded managed MCC process.'
            }
            Assert-MccRepository -ApplicationPath $applicationPath -ExpectedBranch $configuredBranch -RequireClean
            Assert-MccOriginBranch -ApplicationPath $applicationPath -Branch $configuredBranch -DetailedLogPath $detailedLogPath
            Write-MccUpdaterHealthSnapshot
            $agentHealth = Read-MccJson -LiteralPath $agentHealthPath
            if ($agentHealth.agentHealthy -ne $true -or
                $agentHealth.configurationValid -ne $true -or
                $agentHealth.applicationPathMatches -ne $true -or
                $agentHealth.repositoryValid -ne $true -or
                $agentHealth.branchValid -ne $true -or
                $agentHealth.requestDirectoryAccessible -ne $true -or
                $agentHealth.statusDirectoryAccessible -ne $true -or
                $agentHealth.mccTaskInstalled -ne $true -or
                $agentHealth.mccTaskRunning -ne $true -or
                $agentHealth.updaterTaskInstalled -ne $true -or
                $agentHealth.updaterTaskRunning -ne $true -or
                [string]$agentHealth.deploymentMode -cne [string]$configuration.deploymentMode) {
                throw 'The protected updater-agent heartbeat is not healthy after managed startup.'
            }
            $readinessProbe = Invoke-MccHttpJsonProbe `
                -Uri "http://127.0.0.1:$($constants.Port)/api/system/update/managed-readiness" `
                -TimeoutSeconds 5 `
                -AllowedFailureStatusCodes @(404) `
                -RequireFailureJson
            if ([int]$readinessProbe.statusCode -eq 200) {
                Assert-MccManagedReadinessPayload `
                    -Payload $readinessProbe.payload `
                    -ExpectedMode $expectedMode `
                    -ExpectedEnvironmentLabel $environmentLabel `
                    -ExpectedBranch $configuredBranch `
                    -ExpectedVersion $ExpectedVersion `
                    -ExpectedCommit $ExpectedCommit `
                    -ExpectedPort $constants.Port
            } elseif ([int]$readinessProbe.statusCode -eq 404) {
                if (-not $AllowLegacyReadiness404) {
                    throw 'The managed-readiness endpoint is mandatory for the newly updated MCC target.'
                }
                $actualVersion = Get-MccPackageVersion -ApplicationPath $applicationPath
                $actualCommit = (Invoke-MccGit -ApplicationPath $applicationPath -ArgumentList @('rev-parse', 'HEAD') -DetailedLogPath $detailedLogPath).StandardOutput.ToLowerInvariant()
                $healthProbe = Invoke-MccHttpJsonProbe -Uri "http://127.0.0.1:$($constants.Port)/api/health" -TimeoutSeconds 5
                $health = $healthProbe.payload
                $statusProbe = Invoke-MccHttpJsonProbe `
                    -Uri "http://127.0.0.1:$($constants.Port)/api/system/update/status" `
                    -TimeoutSeconds 5 `
                    -AllowedFailureStatusCodes @(401)
                $configurationValid =
                    [string]$configuration.repository -ceq $constants.Repository -and
                    [string]$configuration.remote -ceq $constants.Remote -and
                    [string]$configuration.branch -ceq $configuredBranch -and
                    [int]$configuration.port -eq $constants.Port -and
                    [string]$configuration.serviceIdentity -ceq 'NT AUTHORITY\LOCAL SERVICE' -and
                    [string]$configuration.agentIdentity -ceq 'NT AUTHORITY\SYSTEM'
                $expectedNode = Get-MccNormalizedPath -LiteralPath ([string]$configuration.nodePath)
                $expectedEntryPoint = Get-MccNormalizedPath -LiteralPath (Join-Path $applicationPath 'backend\dist\server\index.js')
                $actualNode = Get-MccNormalizedPath -LiteralPath ([string]$processDetails.ExecutablePath)
                $actualCommandLine = ([string]$processDetails.CommandLine).Replace('"', '')
                Assert-MccLegacyManagedRuntimeEvidence -Evidence ([ordered]@{
                    verificationContext = 'Rollback'
                    readinessStatusCode = [int]$readinessProbe.statusCode
                    installedVersion = $actualVersion
                    restoredCommitMatchesBackup = $actualCommit -ceq $ExpectedCommit.ToLowerInvariant()
                    configurationValid = $configurationValid
                    applicationPathMatches = (Get-MccNormalizedPath -LiteralPath ([string]$configuration.applicationPath)).Equals($applicationPath, [StringComparison]::OrdinalIgnoreCase)
                    originMatches = $true
                    branchMatches = $true
                    packageVersionMatches = $actualVersion -ceq $ExpectedVersion
                    commitMatches = $actualCommit -ceq $ExpectedCommit.ToLowerInvariant()
                    repositoryClean = $true
                    mccTaskInstalled = $null -ne $mccTask
                    mccTaskRunning = [string]$mccTask.State -eq 'Running'
                    mccTaskIdentityMatches = Test-MccScheduledTaskIdentity -Task $mccTask -ExpectedSid 'S-1-5-19'
                    updaterTaskInstalled = $null -ne $updaterTask
                    updaterTaskRunning = [string]$updaterTask.State -eq 'Running'
                    updaterTaskIdentityMatches = Test-MccScheduledTaskIdentity -Task $updaterTask -ExpectedSid 'S-1-5-18'
                    agentHealthy = $agentHealth.agentHealthy -eq $true
                    agentConfigurationValid = $agentHealth.configurationValid -eq $true
                    agentRepositoryValid = $agentHealth.repositoryValid -eq $true
                    agentBranchValid = $agentHealth.branchValid -eq $true
                    agentApplicationPathMatches = $agentHealth.applicationPathMatches -eq $true
                    requestDirectoryAccessible = $agentHealth.requestDirectoryAccessible -eq $true
                    statusDirectoryAccessible = $agentHealth.statusDirectoryAccessible -eq $true
                    processRecordExists = $null -ne $record
                    launchIdValid = $newLaunchId -ne [Guid]::Empty
                    launchIdDistinct = -not $script:PreviousManagedLaunchId -or $newLaunchId.ToString() -cne $script:PreviousManagedLaunchId
                    processApplicationMatchesConfiguration = $record.applicationMatchesConfiguration -eq $true
                    processUpdateModeMatches = [string]$record.managedEnvironment.updateMode -ceq 'windows_agent'
                    processNodeEnvironmentMatches = [string]$record.managedEnvironment.nodeEnvironment -ceq 'production'
                    pidRunning = $null -ne $processDetails
                    nodeExecutableMatches = $actualNode.Equals($expectedNode, [StringComparison]::OrdinalIgnoreCase)
                    backendCommandLineMatches = $actualCommandLine.IndexOf($expectedEntryPoint, [StringComparison]::OrdinalIgnoreCase) -ge 0
                    exclusivePortOwner = $listeners.Count -eq 1 -and [int]$listeners[0].OwningProcess -eq $newProcessId
                    healthOk = [int]$healthProbe.statusCode -eq 200 -and $health.ok -eq $true
                    healthApplicationMatches = [string]$health.app -ceq 'Maintenance Command Center'
                    healthPortMatches = [int]$health.port -eq $constants.Port
                    updateStatusUnauthorized = [int]$statusProbe.statusCode -eq 401
                })
                Write-UpdateLog -Message 'Legacy managed-readiness compatibility verification passed for a restored MCC version predating the managed-readiness endpoint.'
            } else {
                throw 'The managed MCC readiness endpoint returned an unsupported response.'
            }
            return $record
        } catch {
            $lastFailure = Get-MccCleanText -Value $_.Exception.Message -Maximum 500
        }
        Start-Sleep -Seconds 2
    } while ([DateTime]::UtcNow -lt $deadline)
    throw "Managed MCC restart verification failed. $lastFailure"
}

function New-MccRuntimeBackup {
    $backupName = "$([DateTime]::UtcNow.ToString('yyyyMMddTHHmmssZ'))-$($script:InstalledVersion)-before-$($script:TargetVersion)"
    $destination = Join-Path $backupRoot $backupName
    $runtimeDestination = Join-Path $destination 'runtime'
    [System.IO.Directory]::CreateDirectory($runtimeDestination) | Out-Null
    $runtimePaths = @('backend\data', 'backend\uploads', 'backend\documents', 'backend\files', 'backend\.env', '.env')
    foreach ($relativePath in $runtimePaths) {
        $source = Join-Path $applicationPath $relativePath
        if (-not (Test-Path -LiteralPath $source)) { continue }
        $target = Join-Path $runtimeDestination $relativePath
        $targetParent = Split-Path -Parent $target
        [System.IO.Directory]::CreateDirectory($targetParent) | Out-Null
        Copy-Item -LiteralPath $source -Destination $target -Recurse -Force
    }
    $configurationSnapshot = [ordered]@{
        schemaVersion = 1
        deploymentMode = [string]$configuration.deploymentMode
        repository = $constants.Repository
        remote = $constants.Remote
        branch = $configuredBranch
        port = $constants.Port
        mccTaskName = $constants.MccTaskName
        updaterTaskName = $constants.UpdaterTaskName
    }
    Write-MccAtomicJson -LiteralPath (Join-Path $destination 'configuration-snapshot.json') -Value $configurationSnapshot
    $hashes = @(
        Get-ChildItem -LiteralPath $runtimeDestination -File -Recurse -Force | ForEach-Object {
            [ordered]@{
                relativePath = $_.FullName.Substring($runtimeDestination.Length).TrimStart('\').Replace('\', '/')
                length = $_.Length
                sha256 = (Get-FileHash -LiteralPath $_.FullName -Algorithm SHA256).Hash.ToLowerInvariant()
            }
        }
    )
    Write-MccAtomicJson -LiteralPath (Join-Path $destination 'backup-verification.json') -Value ([ordered]@{
        schemaVersion = 1
        algorithm = 'SHA256'
        files = $hashes
    })
    Write-MccAtomicJson -LiteralPath (Join-Path $destination 'job-metadata.json') -Value ([ordered]@{
        schemaVersion = 1
        jobId = $script:JobId
        requestedAt = $script:RequestedAt
        previousCommit = $script:InstalledCommit
        targetCommit = $script:TargetCommit
        previousVersion = $script:InstalledVersion
        targetVersion = $script:TargetVersion
        deploymentMode = [string]$configuration.deploymentMode
        createdAt = [DateTime]::UtcNow.ToString('o')
    })
    $verification = Read-MccJson -LiteralPath (Join-Path $destination 'backup-verification.json')
    foreach ($item in @($verification.files)) {
        $filePath = Join-Path $runtimeDestination ([string]$item.relativePath).Replace('/', '\')
        if (-not (Test-Path -LiteralPath $filePath -PathType Leaf) -or
            (Get-FileHash -LiteralPath $filePath -Algorithm SHA256).Hash.ToLowerInvariant() -ne [string]$item.sha256) {
            throw 'The pre-update runtime backup failed verification.'
        }
    }
    return $destination
}

function Restore-MccRuntimeBackup {
    param([Parameter(Mandatory = $true)][string]$BackupDirectory)
    $runtimeSource = Join-Path $BackupDirectory 'runtime'
    $verificationPath = Join-Path $BackupDirectory 'backup-verification.json'
    if (-not (Test-Path -LiteralPath $runtimeSource -PathType Container) -or
        -not (Test-Path -LiteralPath $verificationPath -PathType Leaf)) {
        throw 'The verified runtime backup required for rollback is missing.'
    }
    $verification = Read-MccJson -LiteralPath $verificationPath
    foreach ($item in @($verification.files)) {
        $source = Join-Path $runtimeSource ([string]$item.relativePath).Replace('/', '\')
        if (-not (Test-Path -LiteralPath $source -PathType Leaf) -or
            (Get-FileHash -LiteralPath $source -Algorithm SHA256).Hash.ToLowerInvariant() -ne [string]$item.sha256) {
            throw 'The runtime backup hash verification failed during rollback.'
        }
    }
    $runtimePaths = @('backend\data', 'backend\uploads', 'backend\documents', 'backend\files', 'backend\.env', '.env')
    foreach ($relativePath in $runtimePaths) {
        $source = Join-Path $runtimeSource $relativePath
        if (-not (Test-Path -LiteralPath $source)) { continue }
        $destination = Join-Path $applicationPath $relativePath
        $normalizedDestination = Get-MccNormalizedPath -LiteralPath $destination
        if (-not ($normalizedDestination + '\').StartsWith($applicationPath + '\', [StringComparison]::OrdinalIgnoreCase)) {
            throw 'Rollback refused an invalid runtime destination.'
        }
        if (Test-Path -LiteralPath $destination) {
            Remove-Item -LiteralPath $destination -Recurse -Force
        }
        [System.IO.Directory]::CreateDirectory((Split-Path -Parent $destination)) | Out-Null
        Copy-Item -LiteralPath $source -Destination $destination -Recurse -Force
    }
}

function Find-MccJobBackup {
    param([Parameter(Mandatory = $true)][string]$JobId)
    foreach ($directory in @(Get-ChildItem -LiteralPath $backupRoot -Directory -ErrorAction SilentlyContinue | Sort-Object LastWriteTimeUtc -Descending)) {
        $metadataPath = Join-Path $directory.FullName 'job-metadata.json'
        if (-not (Test-Path -LiteralPath $metadataPath -PathType Leaf)) { continue }
        try {
            $metadata = Read-MccJson -LiteralPath $metadataPath
            if ([string]$metadata.jobId -eq $JobId) {
                return $directory.FullName
            }
        } catch {}
    }
    return $null
}

function Install-MccLockedDependencies {
    foreach ($project in @('frontend', 'backend')) {
        Invoke-MccProcess -FilePath ([string]$configuration.nodePath) -ArgumentList @([string]$configuration.npmCliPath, 'ci', '--prefix', $project) -WorkingDirectory $applicationPath -TimeoutSeconds 900 -DetailedLogPath $detailedLogPath | Out-Null
    }
}

function Build-Mcc {
    Invoke-MccProcess -FilePath ([string]$configuration.nodePath) -ArgumentList @([string]$configuration.npmCliPath, 'run', 'build') -WorkingDirectory $applicationPath -TimeoutSeconds 900 -DetailedLogPath $detailedLogPath | Out-Null
}

try {
    [System.IO.Directory]::CreateDirectory($logDirectory) | Out-Null
    $lockStream = [System.IO.File]::Open($lockPath, [System.IO.FileMode]::OpenOrCreate, [System.IO.FileAccess]::ReadWrite, [System.IO.FileShare]::None)
    Write-UpdateLog -Message 'Acquired the exclusive Windows MCC updater lock.'
    Write-UpdateLog -Message "$environmentLabel. Configured update branch: origin/$configuredBranch."
    Assert-MccApprovedApplicationPath -LiteralPath $applicationPath | Out-Null
    $nodeVersionResult = Invoke-MccProcess -FilePath ([string]$configuration.nodePath) -ArgumentList @('--version') -WorkingDirectory $applicationPath -TimeoutSeconds 15 -DetailedLogPath $detailedLogPath
    if ($nodeVersionResult.StandardOutput -notmatch '^v(?<major>\d+)\.' -or [int]$Matches.major -lt 22) {
        throw 'Node.js 22 or newer is required for an MCC update.'
    }
    Invoke-MccProcess -FilePath ([string]$configuration.nodePath) -ArgumentList @([string]$configuration.npmCliPath, '--version') -WorkingDirectory $applicationPath -TimeoutSeconds 15 -DetailedLogPath $detailedLogPath | Out-Null
    Assert-MccRepository -ApplicationPath $applicationPath -ExpectedBranch $configuredBranch -DetailedLogPath $detailedLogPath -RequireClean
    Assert-MccOriginBranch -ApplicationPath $applicationPath -Branch $configuredBranch -DetailedLogPath $detailedLogPath
    foreach ($requiredLock in @('package-lock.json', 'frontend\package-lock.json', 'backend\package-lock.json')) {
        if (-not (Test-Path -LiteralPath (Join-Path $applicationPath $requiredLock) -PathType Leaf)) {
            throw 'A required package-lock file is missing.'
        }
    }

    Invoke-MccGit -ApplicationPath $applicationPath -ArgumentList @('fetch', '--no-tags', $constants.Remote, "+refs/heads/${configuredBranch}:refs/remotes/$($constants.Remote)/${configuredBranch}") -TimeoutSeconds 120 -DetailedLogPath $detailedLogPath | Out-Null
    $script:InstalledCommit = (Invoke-MccGit -ApplicationPath $applicationPath -ArgumentList @('rev-parse', 'HEAD') -DetailedLogPath $detailedLogPath).StandardOutput.ToLowerInvariant()
    $verifiedTargetCommit = (Invoke-MccGit -ApplicationPath $applicationPath -ArgumentList @('rev-parse', "refs/remotes/$($constants.Remote)/${configuredBranch}") -DetailedLogPath $detailedLogPath).StandardOutput.ToLowerInvariant()
    if (-not (Test-MccCommit -Value $script:InstalledCommit) -or -not (Test-MccCommit -Value $verifiedTargetCommit)) {
        throw 'Installed or target commit metadata is invalid.'
    }
    Invoke-MccGit -ApplicationPath $applicationPath -ArgumentList @('merge-base', '--is-ancestor', $script:InstalledCommit, $verifiedTargetCommit) -DetailedLogPath $detailedLogPath | Out-Null
    $script:InstalledVersion = Get-MccPackageVersion -ApplicationPath $applicationPath
    $verifiedTargetVersion = Get-RemotePackageVersion -Commit $verifiedTargetCommit

    if ($Manual) {
        $script:JobId = [Guid]::NewGuid().ToString()
        $script:RequestedAt = [DateTime]::UtcNow.ToString('o')
        $script:TargetCommit = $verifiedTargetCommit
        $script:TargetVersion = $verifiedTargetVersion
    } else {
        $normalizedRequestPath = Get-MccNormalizedPath -LiteralPath $RequestPath
        if (-not $normalizedRequestPath.Equals($fixedRequestPath, [StringComparison]::OrdinalIgnoreCase)) {
            throw 'The updater agent refused a non-fixed request location.'
        }
        $request = Read-MccJson -LiteralPath $fixedRequestPath
        $parsedJobId = [Guid]::Empty
        $requestTime = [DateTime]::MinValue
        if ([int]$request.schemaVersion -ne 1 -or
            -not [Guid]::TryParse([string]$request.jobId, [ref]$parsedJobId) -or
            -not [DateTime]::TryParse([string]$request.requestedAt, [ref]$requestTime) -or
            [DateTime]::UtcNow.Subtract($requestTime.ToUniversalTime()).TotalMinutes -gt 30 -or
            $requestTime.ToUniversalTime().Subtract([DateTime]::UtcNow).TotalMinutes -gt 5 -or
            [string]$request.source.repository -ne $constants.Repository -or
            [string]$request.source.remote -ne $constants.Remote -or
            [string]$request.source.branch -cne $configuredBranch -or
            [int]$request.source.port -ne $constants.Port -or
            -not (Test-MccCommit -Value $request.installed.commit) -or
            -not (Test-MccCommit -Value $request.target.commit) -or
            -not (Test-MccSemver -Value $request.installed.version) -or
            -not (Test-MccSemver -Value $request.target.version)) {
            throw 'The fixed MCC update request is invalid or stale.'
        }
        $script:JobId = $parsedJobId.ToString()
        $script:RequestedAt = $requestTime.ToUniversalTime().ToString('o')
        $script:Requester = [ordered]@{
            id = [Math]::Max(0, [int]$request.requester.id)
            name = Get-MccCleanText -Value $request.requester.name -Maximum 120
        }
        $script:TargetCommit = ([string]$request.target.commit).ToLowerInvariant()
        $script:TargetVersion = [string]$request.target.version
        $requestInstalledCommit = ([string]$request.installed.commit).ToLowerInvariant()
        $requestInstalledVersion = [string]$request.installed.version
        $persistedStatus = $null
        if (Test-Path -LiteralPath $statusPath -PathType Leaf) {
            try { $persistedStatus = Read-MccJson -LiteralPath $statusPath } catch { $persistedStatus = $null }
        }
        if ($null -ne $persistedStatus -and [string]$persistedStatus.jobId -eq $script:JobId -and
            @('succeeded', 'rolled_back') -contains [string]$persistedStatus.state -and
            (($persistedStatus.state -eq 'succeeded' -and $script:InstalledCommit -eq $script:TargetCommit) -or
             ($persistedStatus.state -eq 'rolled_back' -and $script:InstalledCommit -eq $requestInstalledCommit))) {
            Remove-Item -LiteralPath $fixedRequestPath -Force
            Write-UpdateLog -Message 'Removed a completed update request left behind by an interrupted cleanup.'
            return
        }
        if ($script:InstalledCommit -eq $script:TargetCommit -and $requestInstalledCommit -ne $script:TargetCommit) {
            $script:InstalledCommit = $requestInstalledCommit
            $script:InstalledVersion = $requestInstalledVersion
            $script:BackupDirectory = Find-MccJobBackup -JobId $script:JobId
            $script:CodeChanged = $true
            throw 'An interrupted Windows update was detected after code changed. Automatic rollback is starting.'
        }
        if ($script:InstalledCommit -ne ([string]$request.installed.commit).ToLowerInvariant() -or
            $script:InstalledVersion -ne $requestInstalledVersion -or
            $script:TargetCommit -ne $verifiedTargetCommit -or
            $script:TargetVersion -ne $verifiedTargetVersion) {
            throw 'The server-verified update target is stale. Run a new update check.'
        }
    }
    if ($script:InstalledCommit -eq $script:TargetCommit) {
        throw 'The approved configured-branch commit is already installed.'
    }

    Write-UpdateStatus -State 'stopping' -Message 'Stopping only the managed Maintenance Command Center background task.'
    Stop-MccManagedTask

    Write-UpdateStatus -State 'backing_up' -Message 'Creating and verifying the external pre-update runtime-data backup.'
    $script:BackupDirectory = New-MccRuntimeBackup

    Write-UpdateStatus -State 'pulling' -Message 'Fast-forwarding the approved Administrator-configured branch to the server-verified target.'
    Invoke-MccGit -ApplicationPath $applicationPath -ArgumentList @('merge', '--ff-only', $script:TargetCommit) -DetailedLogPath $detailedLogPath | Out-Null
    $script:CodeChanged = $true

    Write-UpdateStatus -State 'installing_dependencies' -Message 'Installing locked frontend and backend dependencies.'
    Install-MccLockedDependencies

    Write-UpdateStatus -State 'building' -Message 'Building the MCC frontend and backend.'
    Build-Mcc

    Write-UpdateStatus -State 'starting' -Message 'Starting the managed Maintenance Command Center background task.'
    Write-UpdateStatus -State 'health_check' -Message 'Verifying the scheduled-task handoff, new managed PID, protected updater configuration, port owner, target build, and updater-agent heartbeat.'
    Start-MccManagedTask -ExpectedVersion $script:TargetVersion -ExpectedCommit $script:TargetCommit | Out-Null
    $installedAfter = (Invoke-MccGit -ApplicationPath $applicationPath -ArgumentList @('rev-parse', 'HEAD') -DetailedLogPath $detailedLogPath).StandardOutput.ToLowerInvariant()
    if ($installedAfter -ne $script:TargetCommit -or (Get-MccPackageVersion -ApplicationPath $applicationPath) -ne $script:TargetVersion) {
        throw 'The running MCC commit or application version does not match the approved target.'
    }
    $script:InstalledCommit = $script:TargetCommit
    $script:InstalledVersion = $script:TargetVersion
    Write-UpdateStatus -State 'succeeded' -Message 'The Windows MCC update completed through the protected managed launcher and passed identity, configuration, task, port, heartbeat, version, and commit verification.' -Outcome 'succeeded'
    if (-not $Manual -and (Test-Path -LiteralPath $fixedRequestPath -PathType Leaf)) {
        Remove-Item -LiteralPath $fixedRequestPath -Force
    }
    Write-UpdateLog -Message 'The update completed successfully. The pre-update backup was retained.'
} catch {
    $safeFailure = Get-MccCleanText -Value $_.Exception.Message -Maximum 500
    Write-UpdateLog -Message $safeFailure
    if (-not $Manual -and -not $script:JobId -and (Test-Path -LiteralPath $fixedRequestPath -PathType Leaf)) {
        $script:JobId = [Guid]::NewGuid().ToString()
        $script:RequestedAt = [DateTime]::UtcNow.ToString('o')
        try {
            $blockedRequest = Read-MccJson -LiteralPath $fixedRequestPath
            $blockedJobId = [Guid]::Empty
            if ([Guid]::TryParse([string]$blockedRequest.jobId, [ref]$blockedJobId)) {
                $script:JobId = $blockedJobId.ToString()
            }
            $blockedRequestTime = [DateTime]::MinValue
            if ([DateTime]::TryParse([string]$blockedRequest.requestedAt, [ref]$blockedRequestTime)) {
                $script:RequestedAt = $blockedRequestTime.ToUniversalTime().ToString('o')
            }
            $script:Requester = [ordered]@{
                id = [Math]::Max(0, [int]$blockedRequest.requester.id)
                name = Get-MccCleanText -Value $blockedRequest.requester.name -Maximum 120
            }
        } catch {}
    }
    if ($script:JobId -and ($script:CodeChanged -or $script:MccStopped)) {
        try {
            Write-UpdateStatus -State 'rolling_back' -Message 'The update failed. Restoring the previous MCC commit and runtime data.'
            Stop-MccManagedTask
            if ($script:CodeChanged -and -not $script:BackupDirectory) {
                throw 'The verified safety backup required for interrupted-update rollback is missing.'
            }
            if ($script:CodeChanged) {
                $currentCommit = (Invoke-MccGit -ApplicationPath $applicationPath -ArgumentList @('rev-parse', 'HEAD') -DetailedLogPath $detailedLogPath).StandardOutput.ToLowerInvariant()
                Invoke-MccGit -ApplicationPath $applicationPath -ArgumentList @('update-ref', "refs/heads/${configuredBranch}", $script:InstalledCommit, $currentCommit) -DetailedLogPath $detailedLogPath | Out-Null
                Invoke-MccGit -ApplicationPath $applicationPath -ArgumentList @('read-tree', '--reset', '-u', $script:InstalledCommit) -DetailedLogPath $detailedLogPath | Out-Null
            }
            if ($script:BackupDirectory) {
                Restore-MccRuntimeBackup -BackupDirectory $script:BackupDirectory
            }
            Install-MccLockedDependencies
            Build-Mcc
            Start-MccManagedTask -ExpectedVersion $script:InstalledVersion -ExpectedCommit $script:InstalledCommit -AllowLegacyReadiness404 | Out-Null
            if ((Invoke-MccGit -ApplicationPath $applicationPath -ArgumentList @('rev-parse', 'HEAD') -DetailedLogPath $detailedLogPath).StandardOutput.ToLowerInvariant() -ne $script:InstalledCommit -or
                (Get-MccPackageVersion -ApplicationPath $applicationPath) -ne $script:InstalledVersion) {
                throw 'Rollback commit or version verification failed.'
            }
            Write-UpdateStatus -State 'rolled_back' -Message 'The update failed - the previous MCC version was restored and passed its health check.' -Outcome 'rolled_back'
            Write-UpdateLog -Message 'Automatic rollback completed successfully.'
        } catch {
            $rollbackFailure = Get-MccCleanText -Value $_.Exception.Message -Maximum 500
            Write-UpdateLog -Message "Critical rollback failure. $rollbackFailure"
            Write-UpdateStatus -State 'failed' -Message 'Critical update failure - manual recovery is required. The safety backup and Administrator logs were preserved.' -Outcome 'failed'
            Set-Content -LiteralPath (Join-Path $logDirectory "MANUAL-RECOVERY-$($script:JobId).txt") -Encoding utf8 -Value @(
                'CRITICAL MCC UPDATE FAILURE'
                "Job: $($script:JobId)"
                "Previous commit: $($script:InstalledCommit)"
                "Target commit: $($script:TargetCommit)"
                "Backup: $($script:BackupDirectory)"
                "Detailed log: $detailedLogPath"
                'Run Test-MccWindowsUpdater.ps1 and follow README-Windows-Updater.md recovery procedures.'
            )
        }
    } elseif ($script:JobId) {
        Write-UpdateStatus -State 'failed' -Message "The update was blocked before installed code changed. $safeFailure" -Outcome 'failed'
    }
    throw
} finally {
    if (-not $Manual -and $script:JobId -and (Test-Path -LiteralPath $fixedRequestPath -PathType Leaf)) {
        Remove-Item -LiteralPath $fixedRequestPath -Force -ErrorAction SilentlyContinue
    }
    if ($null -ne $lockStream) {
        $lockStream.Dispose()
    }
}
