import { type FormEvent, useEffect, useState } from 'react';
import { createPortal } from 'react-dom';
import type { AssetIdentity, AssetLibraryScope } from '../machine-library/PreventiveMaintenanceTracking';
import { notifyPmUpdated } from '../machine-library/pmEvents';
import { pollPmWorkflowStatus, usePmActionProgress } from './PmActionProgress';

type MeterType='hours'|'cycles';
type Meter={id:number;meterType:MeterType;currentReading:number;updatedAt:string}|null;
type MeterResponse={meters:{hours:Meter;cycles:Meter}};

async function json<T>(url:string,init?:RequestInit){const response=await fetch(url,{...init,credentials:'include',headers:{'Content-Type':'application/json',...(init?.headers??{})}});const data=await response.json().catch(()=>({}));if(!response.ok)throw new Error(data.error||'Request failed.');if(init?.method&&init.method!=='GET')notifyPmUpdated();return data as T;}

function MeterEditor({type,meter,asset,library,canEdit,onSaved}:{type:MeterType;meter:Meter;asset:AssetIdentity;library:AssetLibraryScope;canEdit:boolean;onSaved:()=>void|Promise<void>}){
  const [reading,setReading]=useState(meter?String(meter.currentReading):'');const [overrideType,setOverrideType]=useState<'replacement'|'correction'|'override'>('replacement');const [reason,setReason]=useState('');const [error,setError]=useState('');const meterAction=usePmActionProgress({label:`Updating ${type==='hours'?'hour meter':'cycle counter'}`,pollStatus:()=>pollPmWorkflowStatus(library,asset.id)});const saving=meterAction.pending;
  useEffect(()=>setReading(meter?String(meter.currentReading):''),[meter]);const numeric=reading===''?null:Number(reading);const decreasing=numeric!==null&&Number.isFinite(numeric)&&meter!==null&&numeric<meter.currentReading;
  async function submit(event:FormEvent){event.preventDefault();if(numeric===null||!Number.isFinite(numeric)||numeric<0||(type==='cycles'&&!Number.isInteger(numeric))){setError(type==='hours'?'Enter a valid hour reading.':'Enter a whole-number cycle reading.');return;}if(decreasing&&(reason.trim().length<5||!/[A-Za-z0-9]/.test(reason))){setError('Enter a meaningful audited reason for the decreasing reading.');return;}setError('');try{await meterAction.run(async()=>{await json(`/api/${library}-library/assets/${asset.id}/preventive-maintenance/meters/${type}`,{method:'PUT',body:JSON.stringify({reading:numeric,...(decreasing?{overrideType,overrideReason:reason}:{})})});await onSaved();setReason('');});}catch(value){setError((value as Error).message);}}
  return <form className="pm-machine-meter-card glass-card glass-card--nested" onSubmit={submit}><div><span>{type==='hours'?'Hour Meter':'Cycle Counter'}</span><strong>{meter?meter.currentReading.toLocaleString():'Not set'}</strong><small>One physical {type==='hours'?'hour reading':'cycle count'} shared by every {type==='hours'?'hourly':'cycle'} PM.</small></div>{canEdit&&<><label className="form-field"><span>New reading</span><input className="glass-input" type="number" min="0" step={type==='hours'?'0.01':'1'} value={reading} onChange={event=>setReading(event.target.value)}/></label>{decreasing&&<div className="pm-meter-correction"><label className="form-field"><span>Correction type *</span><select className="glass-input" value={overrideType} onChange={event=>setOverrideType(event.target.value as typeof overrideType)}><option value="replacement">Meter replacement</option><option value="correction">Meter reset / correction</option><option value="override">Authorized override</option></select></label><label className="form-field"><span>Audit reason *</span><input className="glass-input" value={reason} onChange={event=>setReason(event.target.value)}/></label></div>}{error&&<p className="form-message error" role="alert">{error}</p>}<button className="primary-button compact-button glass-button glass-button--primary" type="submit" disabled={saving}>{saving?'Updating…':`Update ${type==='hours'?'Hours':'Cycles'}`}</button></>}</form>;
}

export function PmMachineMeterPanel({asset,library,canEdit,onUpdated}:{asset:AssetIdentity;library:AssetLibraryScope;canEdit:boolean;onUpdated:()=>void|Promise<void>}){
  const [meters,setMeters]=useState<MeterResponse['meters']>({hours:null,cycles:null});const [error,setError]=useState('');
  async function load(){try{const data=await json<MeterResponse>(`/api/${library}-library/assets/${asset.id}/preventive-maintenance/meters`);setMeters(data.meters??{hours:null,cycles:null});setError('');}catch(value){setError((value as Error).message);}}
  useEffect(()=>{void load();},[asset.id,library]);
  async function saved(){await Promise.all([load(),onUpdated()]);}
  return <section className="pm-machine-meters" aria-labelledby={`pm-machine-meters-${library}-${asset.id}`}><div className="pm-machine-meters-heading"><div><p className="eyebrow">Authoritative machine readings</p><h4 id={`pm-machine-meters-${library}-${asset.id}`}>Machine-level meters</h4></div><span className="glass-pill">Shared across all schedule statuses</span></div>{error&&<p className="form-message error">{error}</p>}<div className="pm-machine-meter-grid"><MeterEditor type="hours" meter={meters.hours} asset={asset} library={library} canEdit={canEdit} onSaved={saved}/><MeterEditor type="cycles" meter={meters.cycles} asset={asset} library={library} canEdit={canEdit} onSaved={saved}/></div></section>;
}

type AssetHistory={id:number;taskTitle:string;scheduleDeleted:boolean;completionDate:string;completedMeter:number|null;performedBy:string;participants?:Array<{displayName:string}>;workOrderNumber:string;completionNotes:string;followUpRequired:boolean;followUpReason:string;attachment?:{status:string;openUrl:string;filename:string}|null};
export function PmAssetHistoryModal({asset,library,onClose}:{asset:AssetIdentity;library:AssetLibraryScope;onClose:()=>void}){
  const [history,setHistory]=useState<AssetHistory[]>([]);const [loading,setLoading]=useState(true);const [error,setError]=useState('');useEffect(()=>{json<{history:AssetHistory[]}>(`/api/${library}-library/assets/${asset.id}/preventive-maintenance/history`).then(data=>setHistory(data.history??[])).catch(value=>setError((value as Error).message)).finally(()=>setLoading(false));},[asset.id,library]);
  return createPortal(<div className="modal-backdrop glass-modal-backdrop" role="presentation"><section className="mcc-card glass-modal-shell pm-modal pm-history-modal mcc-wide-modal" role="dialog" aria-modal="true" aria-labelledby="pm-asset-history-title"><div className="modal-heading"><div><p className="eyebrow">Permanent PM audit trail</p><h3 id="pm-asset-history-title">{asset.assetNumber} PM History</h3></div><button className="link-button compact-button" type="button" onClick={onClose}>Close</button></div>{loading&&<div className="glass-empty-state">Loading PM History…</div>}{error&&<p className="form-message error" role="alert">{error}</p>}{!loading&&!error&&!history.length&&<div className="glass-empty-state">No PM completions have been recorded.</div>}<div className="pm-history-list">{history.map(item=><article className="pm-history-entry" key={item.id}><div><strong>{item.taskTitle}</strong>{item.scheduleDeleted&&<span className="glass-pill pm-archived-pill">Schedule deleted · history preserved</span>}<span>{item.completionDate} · Performed by {item.participants?.map(person=>person.displayName).join(', ')||item.performedBy}</span></div><div className="pm-history-due"><span>Work order: {item.workOrderNumber}</span><span>Meter: {item.completedMeter===null?'Not set':item.completedMeter.toLocaleString()}</span><span>Follow-up: {item.followUpRequired?'Yes':'No'}</span></div>{item.followUpReason&&<p>{item.followUpReason}</p>}{item.completionNotes&&<p>{item.completionNotes}</p>}{item.attachment?.status==='available'&&<a className="secondary-button compact-button" href={item.attachment.openUrl} target="_blank" rel="noreferrer">Open {item.attachment.filename}</a>}</article>)}</div><div className="modal-actions"><button className="secondary-button" type="button" onClick={onClose}>Close</button></div></section></div>,document.body);
}
