import { useRef, useState } from 'react';
import { createPortal } from 'react-dom';

type ExportPlan={schemaVersion?:number;appVersion?:string;generatedAt?:string;rootName:string;directories:string[];files:Array<{archivePath:string;sizeBytes:number;downloadUrl:string;checksumSha256?:string}>;summary:{fileCount:number;totalBytes:number}};
type ExportState={active:boolean;title:string;message:string;transferredBytes:number;totalBytes:number;completedFiles:number;fileCount:number;error:string};
type DirectoryHandle={getDirectoryHandle:(name:string,options?:{create?:boolean})=>Promise<DirectoryHandle>;getFileHandle:(name:string,options?:{create?:boolean})=>Promise<FileHandle>};
type FileHandle={createWritable:()=>Promise<WritableHandle>};
type WritableHandle={write:(data:Uint8Array)=>Promise<void>;close:()=>Promise<void>;abort?:(reason?:unknown)=>Promise<void>};
type PickerWindow=Window&{showDirectoryPicker?:()=>Promise<DirectoryHandle>;showSaveFilePicker?:(options:{suggestedName:string;types:Array<{description:string;accept:Record<string,string[]>}>})=>Promise<FileHandle>};

export function useLibraryExport(){
  const [state,setState]=useState<ExportState|null>(null);const controller=useRef<AbortController|null>(null);
  async function start(input:{title:string;planUrl:string;zipUrl:string;zipFilename:string}){
    const abort=new AbortController();controller.current=abort;setState({active:true,title:input.title,message:'Choose an export destination…',transferredBytes:0,totalBytes:0,completedFiles:0,fileCount:0,error:''});
    try{const result=await exportLibrary({planUrl:input.planUrl,zipUrl:input.zipUrl,zipFilename:input.zipFilename,signal:abort.signal,onProgress:update=>setState(current=>current?{...current,...update}:current)});setState(current=>current?{...current,active:false,message:result==='browser'?'Export started. Your browser will manage the download.':'Export complete.'}:current);}
    catch(error){const cancelled=isAbort(error);setState(current=>current?{...current,active:false,message:cancelled?'Export cancelled.':'Export failed.',error:cancelled?'':error instanceof Error?error.message:'Export failed.'}:current);}
    finally{controller.current=null;}
  }
  return{state,start,cancel:()=>controller.current?.abort(),close:()=>setState(null)};
}

export function LibraryExportProgress({state,onCancel,onClose}:{state:ExportState|null;onCancel:()=>void;onClose:()=>void}){
  if(!state)return null;const percent=state.totalBytes?Math.min(100,state.transferredBytes/state.totalBytes*100):0;
  return createPortal(<div className="modal-backdrop glass-modal-backdrop" role="presentation"><section className="mcc-card glass-modal-shell library-export-modal" role="dialog" aria-modal="true" aria-label={state.title} aria-busy={state.active}><div className="modal-heading"><div><p className="eyebrow">Asset library export</p><h3>{state.title}</h3></div></div><div className="library-upload-progress" role="status" aria-live="polite"><div><strong>{state.message}</strong><span>{Math.round(percent)}%</span></div><progress max="100" value={percent}/><small>{formatBytes(state.transferredBytes)} of {formatBytes(state.totalBytes)} · {state.completedFiles} of {state.fileCount} files</small></div>{state.error&&<p className="form-message error" role="alert">{state.error}</p>}<div className="modal-actions glass-modal__actions"><button className="secondary-button glass-button glass-button--secondary" type="button" onClick={state.active?onCancel:onClose}>{state.active?'Cancel Export':'Close'}</button></div></section></div>,document.body);
}

async function exportLibrary(input:{planUrl:string;zipUrl:string;zipFilename:string;signal:AbortSignal;onProgress:(update:Partial<ExportState>)=>void}):Promise<'directory'|'file'|'browser'>{
  const picker=window as PickerWindow;
  if(picker.showDirectoryPicker){const parent=await picker.showDirectoryPicker();input.onProgress({message:'Preparing file list and checksums…'});const plan=await getPlan(input.planUrl,input.signal);input.onProgress({message:'Exporting folder tree…',totalBytes:plan.summary.totalBytes,fileCount:plan.summary.fileCount});await writePlan(parent,plan,input.signal,input.onProgress);return'directory';}
  if(picker.showSaveFilePicker){const handle=await picker.showSaveFilePicker({suggestedName:input.zipFilename,types:[{description:'ZIP archive',accept:{'application/zip':['.zip']}}]});input.onProgress({message:'Preparing export and checksums…'});const response=await fetch(input.zipUrl,{credentials:'include',signal:input.signal});if(!response.ok)throw await responseError(response);const total=Number(response.headers.get('X-MCC-Export-Bytes')??0);input.onProgress({message:'Saving ZIP archive…',totalBytes:total,fileCount:1});await writeResponse(handle,response,input.signal,(bytes)=>input.onProgress({transferredBytes:bytes,completedFiles:bytes&&total&&bytes>=total?1:0}));return'file';}
  const link=document.createElement('a');link.href=input.zipUrl;link.download=input.zipFilename;document.body.appendChild(link);link.click();link.remove();return'browser';
}
async function getPlan(url:string,signal:AbortSignal){const response=await fetch(url,{credentials:'include',signal});if(!response.ok)throw await responseError(response);const data=await response.json() as {plan:ExportPlan};return data.plan;}
async function writePlan(parent:DirectoryHandle,plan:ExportPlan,signal:AbortSignal,onProgress:(update:Partial<ExportState>)=>void){
  const directoryCache=new Map<string,DirectoryHandle>([['',parent]]);const exportedFiles:Array<Omit<ExportPlan['files'][number],'downloadUrl'>>=[];let transferred=0;let completed=0;
  for(const directory of plan.directories.sort((left,right)=>left.split('/').length-right.split('/').length)){await ensureDirectory(parent,directory,directoryCache);}
  for(const file of plan.files){if(signal.aborted)throw new DOMException('Export cancelled.','AbortError');const segments=file.archivePath.split('/').filter(Boolean);const filename=segments.pop()!;const directory=await ensureDirectory(parent,segments.join('/'),directoryCache);const output=await keepBothFile(directory,filename);const response=await fetch(file.downloadUrl,{credentials:'include',signal});if(!response.ok)throw await responseError(response);await writeResponse(output.handle,response,signal,bytes=>onProgress({transferredBytes:transferred+bytes}));const{downloadUrl:_,...portableFile}=file;exportedFiles.push({...portableFile,archivePath:[...segments,output.filename].join('/')});transferred+=file.sizeBytes;completed+=1;onProgress({transferredBytes:transferred,completedFiles:completed,message:`Exported ${completed} of ${plan.summary.fileCount} files…`});}
  if(plan.schemaVersion===1&&plan.generatedAt){const root=await ensureDirectory(parent,plan.rootName,directoryCache);const manifest={schemaVersion:plan.schemaVersion,appVersion:plan.appVersion??'unknown',generatedAt:plan.generatedAt,rootName:plan.rootName,directories:plan.directories,files:exportedFiles,summary:plan.summary};await writeText(root,'MCC_ASSET_LIBRARY_MANIFEST.json',`${JSON.stringify(manifest,null,2)}\n`);await writeText(root,'MCC_EXPORT_INFO.txt',`MCC Asset Library Master Export\nMCC version: ${manifest.appVersion}\nGenerated: ${plan.generatedAt}\nFiles: ${plan.summary.fileCount}\nBytes: ${plan.summary.totalBytes}\n\nThe JSON manifest contains the relative path, size, and SHA-256 checksum for every exported file.\n`);}
}
async function ensureDirectory(root:DirectoryHandle,pathValue:string,cache:Map<string,DirectoryHandle>){let current=root;let built='';for(const segment of pathValue.split('/').filter(Boolean)){built=built?`${built}/${segment}`:segment;const cached=cache.get(built);if(cached){current=cached;continue;}current=await current.getDirectoryHandle(segment,{create:true});cache.set(built,current);}return current;}
async function keepBothFile(directory:DirectoryHandle,filename:string){const extension=/\.[^.]+$/.exec(filename)?.[0]??'';const base=extension?filename.slice(0,-extension.length):filename;for(let index=1;index<10000;index+=1){const candidate=index===1?filename:`${base} (${index})${extension}`;try{await directory.getFileHandle(candidate);continue;}catch{return{handle:await directory.getFileHandle(candidate,{create:true}),filename:candidate};}}throw new Error('A unique export filename could not be created.');}
async function writeText(directory:DirectoryHandle,filename:string,content:string){const{handle}=await keepBothFile(directory,filename);const writable=await handle.createWritable();try{await writable.write(new TextEncoder().encode(content));await writable.close();}catch(error){await writable.abort?.(error);throw error;}}
async function writeResponse(handle:FileHandle,response:Response,signal:AbortSignal,onBytes:(bytes:number)=>void){const writable=await handle.createWritable();const reader=response.body?.getReader();if(!reader){await writable.abort?.();throw new Error('The browser did not provide a download stream.');}let bytes=0;try{while(true){if(signal.aborted)throw new DOMException('Export cancelled.','AbortError');const chunk=await reader.read();if(chunk.done)break;await writable.write(chunk.value);bytes+=chunk.value.byteLength;onBytes(bytes);}await writable.close();}catch(error){await writable.abort?.(error);throw error;}}
async function responseError(response:Response){const data=await response.json().catch(()=>({})) as {error?:string};return new Error(data.error||`Export failed (${response.status}).`);}
function isAbort(value:unknown){return value instanceof DOMException&&value.name==='AbortError'||value instanceof Error&&/cancelled|aborted/i.test(value.message);}
function formatBytes(value:number){if(!value)return'0 B';if(value<1024)return`${Math.round(value)} B`;if(value<1024**2)return`${(value/1024).toFixed(1)} KB`;if(value<1024**3)return`${(value/1024**2).toFixed(1)} MB`;return`${(value/1024**3).toFixed(1)} GB`;}
