import {expect,type Page,test} from '@playwright/test';

type Library='machine'|'equipment';
type NotePermissions={canEdit:boolean;canDelete:boolean;canResolve:boolean;canReopen:boolean;canAddUpdate:boolean;canDeleteAttachments:boolean};

const writable:NotePermissions={canEdit:true,canDelete:true,canResolve:true,canReopen:false,canAddUpdate:true,canDeleteAttachments:true};
const readOnly:NotePermissions={canEdit:false,canDelete:false,canResolve:false,canReopen:false,canAddUpdate:false,canDeleteAttachments:false};
const machine={id:136,assetNumber:'PRESS-136',assetName:'Issue 136 Press',brand:'MCC',model:'M-136',serialNumber:'M136-SN',machineYear:'2024',location:'North Cell',department:'Molding',status:'active',brandColorHex:'#44D7FF',pmSummary:{total:0,status:'current',label:'PM: Current'},historyPreview:[],createdAt:'2026-09-01T12:00:00Z',updatedAt:'2026-09-22T12:00:00Z'};
const equipment={id:236,assetNumber:'EQ-136',equipmentName:'Issue 136 Dryer',assetName:'Issue 136 Dryer',category:'Dryer',equipmentType:'Desiccant Dryer',manufacturer:'MCC',brand:'MCC',model:'E-136',serialNumber:'E136-SN',equipmentYear:'2024',year:'2024',location:'South Cell',department:'Molding',status:'active',criticality:'normal',powerType:'Electric',voltage:'480 VAC',phase:'3 phase',amperage:'30 A',airRequirement:'90 PSI',waterRequirement:'N/A',capacityRating:'250 lb',dimensions:'40 x 40 x 70 in',weight:'500 lb',specificationNotes:'',pmSummary:{total:0,dueSoon:0,overdue:0,nextDueDate:null,nextDueMeter:null},latestHistory:null,createdAt:'2026-09-01T12:00:00Z',updatedAt:'2026-09-22T12:00:00Z'};

function assetFor(library:Library){return library==='machine'?machine:equipment;}
function maintenanceNote(library:Library,id:number,title:string,status:'active'|'resolved',permissions:NotePermissions=writable){
  const asset=assetFor(library);const resolved=status==='resolved';
  return{id,assetId:asset.id,assetNumber:asset.assetNumber,assetName:asset.assetName,title,noteDate:'2026-09-22',body:`Original ${title} issue.`,warning:true,workOrder:`WO-${library.toUpperCase()}-${id}`,status,createdByUserId:1,createdBy:'Issue 136 Technician',createdAt:'2026-09-22T12:00:00Z',updatedAt:resolved?'2026-09-22T14:00:00Z':'2026-09-22T12:00:00Z',resolvedAt:resolved?'2026-09-22T14:00:00Z':null,resolvedBy:resolved?'Issue 136 Technician':'',resolutionSummary:resolved?'Final repair verified under production load.':'',resolvedYear:resolved?'2026':'',pdfFilename:`${asset.assetNumber}_Maintenance_Record_${id}.pdf`,pdfUrl:`/api/${library}-library/asset-notes/${id}/pdf`,pdfDownloadUrl:`/api/${library}-library/asset-notes/${id}/pdf?download=true`,labor:[{id:1,userId:1,displayName:'Issue 136 Technician',hours:2.25,isPrimary:true,order:0}],totalLaborHours:2.25,attachments:[],workOrderPages:[],updates:[],lifecycle:resolved?[{id:id*10,type:'issue_resolved',actor:'Issue 136 Technician',reason:'Final repair verified under production load.',createdAt:'2026-09-22T14:00:00Z'}]:[],permissions};
}

async function baseRoutes(page:Page,library:Library,notes:unknown[]){
  const asset=assetFor(library);
  await page.route('**/api/auth/status',route=>route.fulfill({json:{setupRequired:false,user:{id:1,fullName:'Issue 136 Technician',email:'issue136@example.com',role:'Admin',isOwnerAdmin:true,forcePasswordChange:false,effectivePermissions:['machine.view','machine.notes_manage','equipment.view','equipment.notes_manage']}}}));
  await page.route('**/api/requisitions/summary',route=>route.fulfill({json:{ok:true,requestedCount:0,orderedCount:0,receivedCount:0,canceledCount:0,activeCount:0}}));
  await page.route(new RegExp(`/api/${library}-library/assets(?:\\?.*)?$`),route=>route.fulfill({json:library==='machine'?{ok:true,assets:[asset],brandSettings:[],permissions:{canEdit:true,canDelete:true}}:{ok:true,assets:[asset],categories:['Dryer'],permissions:{canEdit:true,canDelete:true}}}));
  await page.route(new RegExp(`/api/${library}-library/assets/${asset.id}/notes$`),route=>route.fulfill({json:{ok:true,notes,currentUser:{id:1,fullName:'Issue 136 Technician',email:'issue136@example.com',role:'Admin',isCurrentUser:true},permissions:{canCreate:true,canExportWorkOrderRecords:false}}}));
  await page.route(new RegExp(`/api/${library}-library/assets/${asset.id}/history$`),route=>route.fulfill({json:{ok:true,asset,records:[]}}));
  await page.route(new RegExp(`/api/${library}-library/assets/${asset.id}/preventive-maintenance$`),route=>route.fulfill({json:{ok:true,tasks:[],summary:{total:0,current:0,dueSoon:0,dueNow:0,overdue:0,hold:0,inactive:0,incomplete:0,nextDueDate:null,nextDueMeter:null}}}));
  await page.route(new RegExp(`/api/${library}-library/assets/${asset.id}/(document-folders|documents)$`),route=>route.fulfill({json:{ok:true,folders:[],documents:[],summary:{folderCount:0,documentCount:0}}}));
  if(library==='machine')await page.route(new RegExp(`/api/${library}-library/assets/${asset.id}/(inspection-records|component-images)$`),route=>route.fulfill({json:{ok:true,records:[],images:[]}}));
}

async function openNotes(page:Page,library:Library){
  const asset=assetFor(library);await page.goto(`/${library}-library?asset=${asset.id}`);await page.getByRole('button',{name:/Asset Notes & Attachments/}).click();
}

for(const library of ['machine','equipment'] as const){
  test(`${library} successful resolution offers No without changing the saved record`,async({page})=>{
    const note=maintenanceNote(library,library==='machine'?1361:2361,`${library} resolve no`,'active');const notes=[note];let resolveCalls=0;let pdfRequests=0;
    await baseRoutes(page,library,notes);
    await page.route(new RegExp(`/api/${library}-library/asset-notes/${note.id}/resolve$`),async route=>{resolveCalls+=1;const body=route.request().postDataJSON();expect(body.resolutionSummary).toBe('Final repair verified under production load.');Object.assign(note,{status:'resolved',resolvedAt:'2026-09-22T14:00:00Z',resolvedBy:'Issue 136 Technician',resolutionSummary:body.resolutionSummary,resolvedYear:'2026',updatedAt:'2026-09-22T14:00:00Z',permissions:{...readOnly}});await route.fulfill({json:{ok:true,note}});});
    await page.route(new RegExp(`/api/${library}-library/asset-notes/${note.id}/pdf(?:\\?.*)?$`),route=>{pdfRequests+=1;return route.fulfill({contentType:'application/pdf',body:Buffer.from('%PDF-1.4\n%%EOF')});});
    await openNotes(page,library);const card=page.locator('.asset-note-active-issue-card',{hasText:note.title});await card.locator('.asset-note-issue-toggle').click();await card.getByRole('button',{name:'Issue is Resolved'}).click();await card.getByLabel('Resolution Summary *').fill('Final repair verified under production load.');await card.getByRole('button',{name:'Confirm Resolution'}).click();
    const prompt=page.getByRole('alertdialog',{name:'Print / save the Maintenance Record PDF now?'});await expect(prompt).toBeVisible();await expect(prompt.getByRole('button',{name:'Yes',exact:true})).toBeFocused();await prompt.getByRole('button',{name:'No',exact:true}).click();await expect(prompt).toHaveCount(0);expect(resolveCalls).toBe(1);expect(pdfRequests).toBe(0);
    const historyButton=page.getByRole('button',{name:/Work Order History/});await historyButton.click();const history=page.getByRole('dialog',{name:`Resolved History for ${assetFor(library).assetNumber}`});const year=history.getByRole('button',{name:/2026.*1 resolved issue/});await year.click();const saved=history.locator('.asset-note-entry',{hasText:note.title});await expect(saved).toContainText('Final repair verified under production load.');const more=saved.getByRole('button',{name:`More actions for ${note.title}`});await expect(more).toBeVisible();await more.click();const menu=page.getByRole('menu',{name:`More actions for ${note.title}`});await expect(menu.getByRole('menuitem',{name:'Print Maintenance Record'})).toBeVisible();await expect(menu.getByRole('menuitem',{name:/Edit|Delete/})).toHaveCount(0);
  });

  test(`${library} Yes opens the current completed Maintenance Record PDF`,async({page})=>{
    const note=maintenanceNote(library,library==='machine'?1362:2362,`${library} resolve yes`,'active');const notes=[note];let resolveCalls=0;
    await baseRoutes(page,library,notes);
    await page.route(new RegExp(`/api/${library}-library/asset-notes/${note.id}/resolve$`),route=>{resolveCalls+=1;Object.assign(note,{status:'resolved',resolvedAt:'2026-09-22T14:00:00Z',resolvedBy:'Issue 136 Technician',resolutionSummary:'Completed PDF data verified.',resolvedYear:'2026',updatedAt:'2026-09-22T14:00:00Z',permissions:{...readOnly}});return route.fulfill({json:{ok:true,note}});});
    await page.route(new RegExp(`/api/${library}-library/asset-notes/${note.id}/pdf(?:\\?.*)?$`),route=>route.fulfill({contentType:'application/pdf',body:Buffer.from('%PDF-1.4\n%%EOF')}));
    await openNotes(page,library);const card=page.locator('.asset-note-active-issue-card',{hasText:note.title});await card.locator('.asset-note-issue-toggle').click();await card.getByRole('button',{name:'Issue is Resolved'}).click();await card.getByLabel('Resolution Summary *').fill('Completed PDF data verified.');await card.getByRole('button',{name:'Confirm Resolution'}).click();const prompt=page.getByRole('alertdialog',{name:'Print / save the Maintenance Record PDF now?'});await prompt.getByRole('button',{name:'Yes',exact:true}).click();
    const viewer=page.getByRole('dialog',{name:`${note.pdfFilename} viewer`});await expect(viewer).toBeVisible();await expect(viewer.locator('object')).toHaveAttribute('data',note.pdfUrl);await expect(viewer.getByRole('button',{name:'Download',exact:true})).toBeVisible();await expect(viewer.getByRole('button',{name:'Print',exact:true})).toBeVisible();await expect(viewer.getByRole('button',{name:'Open Original',exact:true})).toBeVisible();expect(resolveCalls).toBe(1);
  });

  test(`${library} history More targets one record at a time and stays usable above the modal`,async({page})=>{
    const first=maintenanceNote(library,library==='machine'?1363:2363,`${library} read only history`,'resolved',readOnly);const second=maintenanceNote(library,library==='machine'?1364:2364,`${library} editable history`,'resolved',{...writable,canResolve:false,canReopen:true,canAddUpdate:false});const notes=[first,second];
    await page.addInitScript(()=>{const opened:string[]=[];(window as unknown as {__issue136Opened:string[]}).__issue136Opened=opened;window.open=((url?:string|URL)=>{opened.push(String(url));return null;}) as typeof window.open;});await baseRoutes(page,library,notes);await openNotes(page,library);await page.getByRole('button',{name:/Work Order History/}).click();const history=page.getByRole('dialog',{name:`Resolved History for ${assetFor(library).assetNumber}`});await history.getByRole('button',{name:/2026.*2 resolved issues/}).click();
    const firstTrigger=history.getByRole('button',{name:`More actions for ${first.title}`});const secondTrigger=history.getByRole('button',{name:`More actions for ${second.title}`});await firstTrigger.click();let menu=page.getByRole('menu',{name:`More actions for ${first.title}`});await expect(menu).toBeVisible();await expect(menu.getByRole('menuitem')).toHaveCount(1);await expect(menu.getByRole('menuitem',{name:'Print Maintenance Record'})).toBeVisible();
    const geometry=await menu.evaluate(element=>{const box=element.getBoundingClientRect();const backdrop=document.querySelector('.asset-note-history-backdrop')!;const hit=document.elementFromPoint(box.left+Math.min(12,box.width/2),box.top+Math.min(12,box.height/2));return{left:box.left,top:box.top,right:box.right,bottom:box.bottom,viewportWidth:innerWidth,viewportHeight:innerHeight,z:Number(getComputedStyle(element).zIndex),backdropZ:Number(getComputedStyle(backdrop).zIndex),hitInside:element.contains(hit)};});expect(geometry.left).toBeGreaterThanOrEqual(0);expect(geometry.top).toBeGreaterThanOrEqual(0);expect(geometry.right).toBeLessThanOrEqual(geometry.viewportWidth);expect(geometry.bottom).toBeLessThanOrEqual(geometry.viewportHeight);expect(geometry.z).toBeGreaterThan(geometry.backdropZ);expect(geometry.hitInside).toBe(true);
    await history.getByText('Active and resolved maintenance records remain printable and auditable.').click();await expect(menu).toHaveCount(0);await firstTrigger.focus();await page.keyboard.press('ArrowDown');menu=page.getByRole('menu',{name:`More actions for ${first.title}`});await expect(menu.getByRole('menuitem').first()).toBeFocused();await page.keyboard.press('Escape');await expect(menu).toHaveCount(0);await expect(firstTrigger).toBeFocused();await expect(history).toBeVisible();
    await firstTrigger.click();await secondTrigger.click();await expect(firstTrigger).toHaveAttribute('aria-expanded','false');await expect(secondTrigger).toHaveAttribute('aria-expanded','true');await expect(page.getByRole('menu')).toHaveCount(1);menu=page.getByRole('menu',{name:`More actions for ${second.title}`});await expect(menu.getByRole('menuitem',{name:'Edit Note'})).toBeVisible();await expect(menu.getByRole('menuitem',{name:'Delete Note'})).toBeVisible();await menu.getByRole('menuitem',{name:'Print Maintenance Record'}).click();expect(await page.evaluate(()=>(window as unknown as {__issue136Opened:string[]}).__issue136Opened)).toEqual([second.pdfUrl]);await expect(history).toBeVisible();expect(await page.evaluate(()=>document.documentElement.scrollWidth-document.documentElement.clientWidth)).toBeLessThanOrEqual(1);
  });
}
