import { expect, type Page, test } from '@playwright/test';

const asset={id:71,assetNumber:'DOC-PRESS-71',assetName:'Document Press',brand:'Toyo',model:'D-71',serialNumber:'DOC-71',machineYear:'2020',machineType:'Injection Molding Machine',powerType:'Electric',shotSizeOz:10,tonnage:250,barrelDiameter:'35mm',location:'North Cell',department:'Molding',status:'active',voltageValue:'480',voltageType:'AC',fullLoadAmp:'200',machineLength:'20 ft',machineWidth:'8 ft',machineHeight:'9 ft',fullDieHeightLength:'48 in',screwType:'General',screwTipType:'Ring',screwTipInstalledDate:'',screwInstalledDate:'',barrelInstalledDate:'',barrelEndCapInstalledDate:'',barrelLength:'90 in',screwLength:'88 in',screwRebuildRepaired:false,barrelRebuildRepaired:false,screwConditionStatus:'used',barrelConditionStatus:'used',hasDoubleShotInjection:false,hasPlungerInjection:false,screw2Type:'',screw2TipType:'',screw2RebuildRepaired:false,screw2ConditionStatus:'new',screw2InstalledDate:'',screw2TipInstalledDate:'',screw2Length:'',barrel2Diameter:'',barrel2RebuildRepaired:false,barrel2ConditionStatus:'new',barrel2InstalledDate:'',barrel2EndCapInstalledDate:'',barrel2Length:'',plungerType:'',plungerRebuildRepaired:false,plungerConditionStatus:'new',plungerInstalledDate:'',plungerLength:'',plungerDiameter:'',plungerBarrelType:'',plungerBarrelRebuildRepaired:false,plungerBarrelConditionStatus:'new',plungerBarrelInstalledDate:'',plungerBarrelEndCapInstalledDate:'',plungerBarrelLength:'',plungerBarrelDiameter:'',notes:'',criticalNotes:'',brandColorHex:'#44D7FF',createdAt:'2026-01-01T12:00:00Z',updatedAt:'2026-07-21T12:00:00Z',pmSummary:null,historyPreview:[]};
let folders=[{id:1,assetId:71,name:'Manuals',description:'OEM manuals',documentCount:1,createdAt:'2026-07-20T12:00:00Z',updatedAt:'2026-07-21T12:00:00Z'},{id:2,assetId:71,name:'Electrical Prints',description:'',documentCount:0,createdAt:'2026-07-20T12:00:00Z',updatedAt:'2026-07-20T12:00:00Z'}];
let documents=[documentFixture(10,1,'Manual.pdf','.pdf')];let nextFolderId=3;let nextDocumentId=11;
function documentFixture(id:number,folderId:number,displayFilename:string,extension:string){return{id,assetId:71,folderId,folderName:folders.find(folder=>folder.id===folderId)?.name??'',originalFilename:displayFilename,displayFilename,extension,mimeType:extension==='.pdf'?'application/pdf':'text/plain',sizeBytes:2048,description:'Machine document',revision:'A',uploadedAt:'2026-07-21T12:00:00Z',updatedAt:'2026-07-21T12:00:00Z',uploadedBy:'Automation User',openUrl:`/api/machine-library/assets/71/documents/${id}/open`,downloadUrl:`/api/machine-library/assets/71/documents/${id}/download`,canPrint:extension==='.pdf'};}
function refreshCounts(){folders=folders.map(folder=>({...folder,documentCount:documents.filter(document=>document.folderId===folder.id).length}));}
async function mockLibrary(page:Page){folders=folders.map(folder=>({...folder}));documents=documents.map(document=>({...document}));
  await page.route('**/api/auth/status',route=>route.fulfill({json:{setupRequired:false,user:{id:1,fullName:'Automation User',email:'test@example.com',role:'Admin',isOwnerAdmin:true,forcePasswordChange:false}}}));
  await page.route(/\/api\/machine-library\/assets(?:\?.*)?$/,route=>route.fulfill({json:{ok:true,assets:[asset],brandSettings:[],permissions:{canEdit:true,canDelete:true}}}));
  await page.route(/\/api\/machine-library\/assets\/71\/(preventive-maintenance|notes|component-images|inspection-records)$/,route=>route.fulfill({json:route.request().url().includes('preventive-maintenance')?{ok:true,tasks:[],summary:{total:0}}:route.request().url().includes('notes')?{ok:true,notes:[]}:{ok:true,images:[],records:[]}}));
  await page.route(/\/api\/machine-library\/assets\/71\/document-folders(?:\/\d+)?$/,async route=>{const request=route.request();const url=new URL(request.url());const parts=url.pathname.split('/');const folderId=Number(parts.at(-1));if(request.method()==='GET')return route.fulfill({json:{ok:true,folders,summary:{folderCount:folders.length,documentCount:documents.length}}});if(request.method()==='POST'){const body=request.postDataJSON() as {name:string;description?:string};if(folders.some(folder=>folder.name.toLowerCase()===body.name.trim().toLowerCase()))return route.fulfill({status:409,json:{ok:false,code:'DUPLICATE_FOLDER',error:'A folder with this name already exists.'}});const folder={id:nextFolderId++,assetId:71,name:body.name.trim(),description:body.description??'',documentCount:0,createdAt:new Date().toISOString(),updatedAt:new Date().toISOString()};folders.push(folder);return route.fulfill({status:201,json:{ok:true,folder}});}if(request.method()==='PATCH'){const body=request.postDataJSON() as {name:string;description:string};folders=folders.map(folder=>folder.id===folderId?{...folder,...body}:folder);return route.fulfill({json:{ok:true,folder:folders.find(folder=>folder.id===folderId)}});}if(request.method()==='DELETE'){const folder=folders.find(item=>item.id===folderId);if(folder?.documentCount)return route.fulfill({status:409,json:{ok:false,code:'FOLDER_NOT_EMPTY',error:'This folder contains documents. Move or delete them before deleting the folder.'}});folders=folders.filter(folder=>folder.id!==folderId);return route.fulfill({json:{ok:true}});}return route.fallback();});
  await page.route(/\/api\/machine-library\/assets\/71\/documents(?:\/\d+(?:\/move)?)?$/,async route=>{const request=route.request();const url=new URL(request.url());if(request.method()==='GET')return route.fulfill({json:{ok:true,documents}});const match=url.pathname.match(/documents\/(\d+)/);const documentId=Number(match?.[1]);if(request.method()==='PATCH'){const body=request.postDataJSON() as {displayFilename:string;description:string;revision:string};documents=documents.map(document=>document.id===documentId?{...document,...body}:document);return route.fulfill({json:{ok:true,document:documents.find(document=>document.id===documentId)}});}if(request.method()==='POST'&&url.pathname.endsWith('/move')){const body=request.postDataJSON() as {folderId:number;duplicateAction?:string};const current=documents.find(document=>document.id===documentId)!;const duplicate=documents.find(document=>document.folderId===body.folderId&&document.displayFilename===current.displayFilename);if(duplicate&&!body.duplicateAction)return route.fulfill({status:409,json:{ok:false,code:'DOCUMENT_DUPLICATE',error:'A document with this name already exists.'}});documents=documents.map(document=>document.id===documentId?{...document,folderId:body.folderId,folderName:folders.find(folder=>folder.id===body.folderId)?.name??''}:document);refreshCounts();return route.fulfill({json:{ok:true,document:documents.find(document=>document.id===documentId)}});}if(request.method()==='DELETE'){documents=documents.filter(document=>document.id!==documentId);refreshCounts();return route.fulfill({json:{ok:true}});}return route.fallback();});
  await page.route(/\/api\/machine-library\/assets\/71\/document-folders\/(\d+)\/documents$/,async route=>{const body=route.request().postData()??'';const folderId=Number(new URL(route.request().url()).pathname.split('/').at(-2));const filename=/filename="([^"]+)"/.exec(body)?.[1]??'Uploaded.pdf';const duplicate=documents.some(document=>document.folderId===folderId&&document.displayFilename.toLowerCase()===filename.toLowerCase());if(duplicate&&!body.includes('keep_both')&&!body.includes('replace'))return route.fulfill({status:409,json:{ok:false,code:'DOCUMENT_DUPLICATE',error:'A document with this name already exists.'}});let displayFilename=filename;if(duplicate&&body.includes('keep_both')){const extension=displayFilename.slice(displayFilename.lastIndexOf('.'));displayFilename=`${displayFilename.slice(0,-extension.length)} (2)${extension}`;}if(duplicate&&body.includes('replace'))documents=documents.filter(document=>!(document.folderId===folderId&&document.displayFilename.toLowerCase()===filename.toLowerCase()));const document=documentFixture(nextDocumentId++,folderId,displayFilename,`.${fileExtension(displayFilename)}`);documents.push(document);refreshCounts();return route.fulfill({status:201,json:{ok:true,documents:[document]}});});
  await page.route(/\/api\/machine-library\/assets\/71\/documents\/\d+\/(open|download)$/,route=>route.fulfill({contentType:'application/pdf',body:'%PDF-1.4\n%%EOF'}));
}
function fileExtension(value:string){return value.split('.').pop()?.toLowerCase()??'';}

test('document library supports folder, upload, duplicate, document actions, and persistence workflows',async({page})=>{await mockLibrary(page);await page.goto('/machine-library');await page.locator('.machine-asset-card .machine-card-brand-name').click();const detail=page.locator('.machine-detail-modal');await expect(detail.getByText('Asset Document Library',{exact:true})).toBeVisible();const headers=detail.locator('.machine-detail-section-title');const headerTexts=await headers.allTextContents();expect(headerTexts.indexOf('Preventive Maintenance Tracking')).toBeLessThan(headerTexts.indexOf('Asset Document Library'));expect(headerTexts.indexOf('Asset Document Library')).toBeLessThan(headerTexts.indexOf('Asset Notes & Attachments'));
  const libraryToggle=detail.getByRole('button',{name:/Asset Document Library/});await expect(libraryToggle).toHaveAttribute('aria-expanded','false');await libraryToggle.click();await expect(libraryToggle).toHaveAttribute('aria-expanded','true');await expect(libraryToggle).toContainText('2 folders · 1 document');await libraryToggle.click();await expect(libraryToggle).toHaveAttribute('aria-expanded','false');await libraryToggle.focus();await page.keyboard.press('Space');await expect(libraryToggle).toHaveAttribute('aria-expanded','true');
  await detail.getByRole('button',{name:'Create Folder'}).click();let modal=page.getByRole('dialog',{name:'Create Folder'});await modal.getByLabel('Folder Name *').fill('Safety Information');await modal.getByLabel('Description').fill('Safety procedures');await modal.getByRole('button',{name:'Create',exact:true}).click();await expect(libraryToggle).toContainText('3 folders · 1 document');
  await detail.getByRole('button',{name:'Create Folder'}).click();modal=page.getByRole('dialog',{name:'Create Folder'});await modal.getByLabel('Folder Name *').fill(' manuals ');await modal.getByRole('button',{name:'Create',exact:true}).click();await expect(detail.getByText('A folder with this name already exists.')).toBeVisible();await modal.getByRole('button',{name:'Cancel'}).click();
  const manuals=detail.getByRole('button',{name:/Manuals.*1 document/});await manuals.focus();await page.keyboard.press('Enter');await expect(manuals).toHaveAttribute('aria-expanded','true');await detail.getByRole('button',{name:'Upload Document'}).click();modal=page.getByRole('dialog',{name:'Upload to Manuals'});const input=modal.locator('input[type=file]');await input.setInputFiles([{name:'Setup.txt',mimeType:'text/plain',buffer:Buffer.from('setup')}]);await expect(modal.getByText('Setup.txt')).toBeVisible();await modal.getByRole('button',{name:'Upload Document'}).click();await expect(detail.getByText('Setup.txt')).toBeVisible();
  const manualRow=detail.locator('.machine-document-row',{hasText:'Manual.pdf'});await expect(manualRow.getByRole('button',{name:'Open'})).toBeVisible();await expect(manualRow.getByRole('button',{name:'Download / Save'})).toBeVisible();await expect(manualRow.getByRole('button',{name:'Print PDF'})).toBeVisible();await expect(manualRow.getByRole('button',{name:'Rename / Edit'})).toBeVisible();await expect(manualRow.getByRole('button',{name:'Move to Folder'})).toBeVisible();
  await detail.getByRole('button',{name:'Upload Document'}).click();modal=page.getByRole('dialog',{name:'Upload to Manuals'});await modal.locator('input[type=file]').setInputFiles([{name:'Manual.pdf',mimeType:'application/pdf',buffer:Buffer.from('%PDF-1.4\n%%EOF')}]);await modal.getByRole('button',{name:'Upload Document'}).click();await expect(modal.getByText('A document with this name already exists.')).toBeVisible();await expect(modal.getByRole('button',{name:'Replace Existing'})).toBeVisible();await expect(modal.getByRole('button',{name:'Keep Both'})).toBeVisible();await modal.getByRole('button',{name:'Cancel'}).click();
  await page.reload();await page.locator('.machine-asset-card .machine-card-brand-name').click();const reloadedDetail=page.locator('.machine-detail-modal');const reloadedToggle=reloadedDetail.getByRole('button',{name:/Asset Document Library/});await reloadedToggle.click();await expect(reloadedToggle).toContainText('3 folders · 2 documents');expect(await page.evaluate(()=>document.documentElement.scrollWidth-document.documentElement.clientWidth)).toBeLessThanOrEqual(1);
});

test('read-only users can open folders and documents without write controls',async({page})=>{await mockLibrary(page);await page.route('**/api/auth/status',route=>route.fulfill({json:{setupRequired:false,user:{id:2,fullName:'Viewer',email:'viewer@example.com',role:'Maintenance Tech 1',isOwnerAdmin:false,forcePasswordChange:false}}}));await page.route(/\/api\/machine-library\/assets(?:\?.*)?$/,route=>route.fulfill({json:{ok:true,assets:[asset],brandSettings:[],permissions:{canEdit:false,canDelete:false}}}));await page.goto('/machine-library');await page.locator('.machine-asset-card .machine-card-brand-name').click();const detail=page.locator('.machine-detail-modal');await detail.getByRole('button',{name:/Asset Document Library/}).click();await expect(detail.getByRole('button',{name:'Create Folder'})).toHaveCount(0);const manuals=detail.getByRole('button',{name:/Manuals/});await manuals.click();const row=detail.locator('.machine-document-row',{hasText:'Manual.pdf'});await expect(row.getByRole('button',{name:'Open'})).toBeVisible();await expect(row.getByRole('button',{name:'Download / Save'})).toBeVisible();await expect(row.getByRole('button',{name:'Rename / Edit'})).toHaveCount(0);await expect(row.getByRole('button',{name:'Delete'})).toHaveCount(0);});
