import { expect, type Page, test } from '@playwright/test';
import path from 'node:path';

const asset={id:100,assetNumber:'M-100',assetName:'Sanitized Press',brand:'MCC',model:'PM-100',serialNumber:'SAN-100',machineYear:'2024',machineType:'Injection Molding Machine',powerType:'Hydraulic',setupType:'Standard Injection',shotSizeOz:10,tonnage:250,barrelDiameter:'40 mm',location:'Test Cell',department:'Maintenance',status:'active',voltageValue:'480',voltageType:'VAC',fullLoadAmp:'100',machineLength:'',machineWidth:'',machineHeight:'',fullDieHeightLength:'',screwType:'',screwTipType:'',screwTipInstalledDate:'',screwInstalledDate:'',barrelInstalledDate:'',barrelEndCapInstalledDate:'',barrelLength:'',screwLength:'',screwRebuildRepaired:false,barrelRebuildRepaired:false,screwConditionStatus:'new',barrelConditionStatus:'new',hasDoubleShotInjection:false,hasPlungerInjection:false,screw2Type:'',screw2TipType:'',screw2RebuildRepaired:false,screw2ConditionStatus:'new',screw2InstalledDate:'',screw2TipInstalledDate:'',screw2Length:'',barrel2Diameter:'',barrel2RebuildRepaired:false,barrel2ConditionStatus:'new',barrel2InstalledDate:'',barrel2EndCapInstalledDate:'',barrel2Length:'',plungerType:'',plungerRebuildRepaired:false,plungerConditionStatus:'new',plungerInstalledDate:'',plungerLength:'',plungerDiameter:'',plungerBarrelType:'',plungerBarrelRebuildRepaired:false,plungerBarrelConditionStatus:'new',plungerBarrelInstalledDate:'',plungerBarrelEndCapInstalledDate:'',plungerBarrelLength:'',plungerBarrelDiameter:'',notes:'',criticalNotes:'',brandColorHex:'#44D7FF',createdAt:'2026-01-01T12:00:00Z',updatedAt:'2026-08-04T12:00:00Z',pmSummary:{total:1,status:'current',label:'PM: Current'},historyPreview:[]};
const task={id:700,assetId:100,title:'Hydraulic service',instructions:'Follow approved procedure.',intervalType:'hourly',intervalLabel:'Hourly',intervalValue:3000,lastCompletedDate:null,lastCompletedMeter:3456,currentMeter:3560,nextDueDate:null,nextDueMeter:6456,scheduleStatus:'active',active:true,notes:'',status:'Current',countdown:'2,896 hours remaining',historyCount:0,createdAt:'2026-01-01T12:00:00Z',updatedAt:'2026-08-04T12:00:00Z'};

async function mockPmUi(page:Page,captured:{completion?:Record<string,unknown>;completionKey?:string;confirmation?:Record<string,unknown>;confirmationKey?:string}){
  await page.route('**/api/auth/status',route=>route.fulfill({json:{setupRequired:false,user:{id:1,fullName:'PM Owner',email:'pm@example.com',role:'Admin',isOwnerAdmin:true,forcePasswordChange:false,effectivePermissions:['machine.view','machine.pm_manage']}}}));
  await page.route(/\/api\/machine-library\/assets(?:\?.*)?$/,route=>route.fulfill({json:{ok:true,assets:[asset],brandSettings:[],permissions:{canEdit:true,canDelete:true}}}));
  await page.route(/\/api\/machine-library\/assets\/100\/preventive-maintenance$/,route=>route.fulfill({json:{ok:true,tasks:[task],summary:{total:1,dueSoon:0,overdue:0,nextDueDate:null,nextDueMeter:6456}}}));
  await page.route('/api/pm-excel/status',route=>route.fulfill({json:{ok:true,sync:{status:'success',attemptedAt:'2026-08-04T12:00:00Z',synchronizedAt:'2026-08-04T12:00:00Z',originalFilename:'PM_report _1.2v.xlsx',errorMessage:'',downloadAvailable:true}}}));
  await page.route('/api/pm-excel/preview',route=>route.fulfill({json:{ok:true,preview:{token:'11111111-1111-4111-8111-111111111111',filename:'pm-report-sanitized.xlsx',expiresAt:'2026-08-04T13:00:00Z',additions:[{sheet:'Machine Pm Tracker',rowNumber:4,assetNumber:'M-100',taskTitle:'Hydraulic service'}],updates:[],historyAdditions:[{sheet:'PMHistory',rowNumber:3,assetNumber:'M-100',taskType:'Hydraulic service',workOrderNumber:'WO-SAN-001'}],conflicts:[],warnings:[{sheet:'Machine Pm Tracker',rowNumber:4,message:'Status will be recalculated as Current.'}],rejectedRows:[],summary:{additions:1,updates:0,historyAdditions:1,conflicts:0,warnings:1,rejectedRows:0}}}}));
  await page.route('/api/pm-excel/confirm',async route=>{captured.confirmation=route.request().postDataJSON();captured.confirmationKey=await route.request().headerValue('idempotency-key')??undefined;await route.fulfill({json:{ok:true,import:{added:1,updated:0,historyAdded:1},sync:{status:'success',attemptedAt:'2026-08-04T12:01:00Z',synchronizedAt:'2026-08-04T12:01:00Z',originalFilename:'pm-report-sanitized.xlsx',errorMessage:'',downloadAvailable:true},syncError:null}});});
  await page.route(/\/api\/machine-library\/preventive-maintenance\/700\/complete$/,async route=>{captured.completion=route.request().postDataJSON();captured.completionKey=await route.request().headerValue('idempotency-key')??undefined;await route.fulfill({json:{ok:true,task:{...task,lastCompletedMeter:3400,currentMeter:3400,nextDueMeter:6400},history:{id:1,completionDate:'2026-08-04',completedMeter:3400,performedBy:'PM Owner',completionNotes:'PM completed at 3,400 machine hours. No issues found.'},sync:{status:'success',synchronizedAt:'2026-08-04T12:02:00Z',downloadAvailable:true}}});});
  await page.route(/\/api\/machine-library\/assets\/\d+\/(?:history|inspection-records|notes|component-images|document-folders|documents)$/,route=>route.fulfill({json:{ok:true,records:[],notes:[],images:[],folders:[],documents:[],summary:{folderCount:0,documentCount:0}}}));
}

test('provides controlled PM Excel import and the complete-PM confirmation workflow',async({page})=>{
  const captured:{}&{completion?:Record<string,unknown>;completionKey?:string;confirmation?:Record<string,unknown>;confirmationKey?:string}={};await mockPmUi(page,captured);await page.goto('/machine-library');await page.locator('.machine-asset-card .machine-asset-number-pill').click();await expect(page.locator('.machine-detail-modal')).toBeVisible();await page.locator('.pm-tracking-card .machine-detail-accordion-toggle').click();
  const sync=page.locator('.pm-excel-sync');await expect(sync).toContainText('Last Excel Sync: Successful');await expect(sync.getByRole('link',{name:'Download Latest PM Excel'})).toBeVisible();const input=sync.locator('input[type=file]');await input.setInputFiles(path.resolve('tests/fixtures/pm-report-sanitized.xlsx'));await sync.getByRole('button',{name:'Preview Changes'}).click();const preview=page.getByRole('dialog',{name:'PM Excel Import Preview'});await expect(preview).toContainText('1 additions');await expect(preview).toContainText('1 history rows');await expect(preview).toContainText('Previewing has not changed MCC data');await preview.getByRole('button',{name:'Confirm Import'}).click();await expect(sync).toContainText('PM import confirmed: 1 added, 0 updated, 1 history rows added');expect(captured.confirmation).toMatchObject({previewToken:'11111111-1111-4111-8111-111111111111',meterOverrides:[]});expect(captured.confirmationKey).toMatch(/^[0-9a-f-]{36}$/);

  await page.getByRole('button',{name:'Complete PM'}).click();const complete=page.getByRole('dialog',{name:'Complete Hydraulic service'});await expect(complete).toContainText('M-100 — Sanitized Press');await expect(complete).toContainText('Hydraulic service');await expect(complete).toContainText('Hourly');await expect(complete).toContainText('PM Owner');const noIssues=complete.getByRole('checkbox',{name:'No issues found'});await expect(noIssues).toBeChecked();await noIssues.uncheck();await complete.getByRole('textbox',{name:'Task Note'}).fill('bad');await complete.getByRole('button',{name:'Confirm Completion'}).click();await expect(complete.getByRole('alert')).toContainText('meaningful Task Note');await noIssues.check();await complete.getByRole('textbox',{name:'Task Note'}).fill('');const reading=complete.getByRole('spinbutton',{name:'Current machine hour reading'});await reading.fill('3400');await expect(complete).toContainText('Decreasing meter reading requires authorization');await complete.getByRole('textbox',{name:'Override reason'}).fill('Installed documented replacement meter.');await complete.getByRole('button',{name:'Confirm Completion'}).click();await expect(complete).toHaveCount(0);expect(captured.completion).toMatchObject({completedMeter:3400,noIssuesFound:true,taskNote:'',meterOverride:{type:'replacement',reason:'Installed documented replacement meter.'}});expect(captured.completionKey).toMatch(/^[0-9a-f-]{36}$/);
});
