import {expect,type Page,test} from '@playwright/test';

type Library='machine'|'equipment';
const permissions={canEdit:true,canDelete:true,canResolve:true,canReopen:false,canAddUpdate:true,canDeleteAttachments:true};
const machineAsset={id:9801,assetNumber:'PRESS-98',assetName:'Lifecycle Press',brand:'Toyo',model:'M-98',serialNumber:'M98-SN',machineYear:'2022',machineType:'Injection Molding Machine',powerType:'Electric',setupType:'Standard Injection',shotSizeOz:12,tonnage:250,barrelDiameter:'35mm',location:'North Cell',department:'Molding',status:'active',voltageValue:'480',voltageType:'AC',fullLoadAmp:'120',machineLength:'20 ft',machineWidth:'7 ft',machineHeight:'8 ft',fullDieHeightLength:'48 in',screwType:'GP',screwTipType:'Ring',screwTipInstalledDate:'',screwInstalledDate:'',barrelInstalledDate:'',barrelEndCapInstalledDate:'',barrelLength:'96 in',screwLength:'92 in',screwRebuildRepaired:false,barrelRebuildRepaired:false,screwConditionStatus:'used',barrelConditionStatus:'used',hasDoubleShotInjection:false,hasPlungerInjection:false,screw2Type:'',screw2TipType:'',screw2RebuildRepaired:false,screw2ConditionStatus:'new',screw2InstalledDate:'',screw2TipInstalledDate:'',screw2Length:'',barrel2Diameter:'',barrel2RebuildRepaired:false,barrel2ConditionStatus:'new',barrel2InstalledDate:'',barrel2EndCapInstalledDate:'',barrel2Length:'',plungerType:'',plungerRebuildRepaired:false,plungerConditionStatus:'new',plungerInstalledDate:'',plungerLength:'',plungerDiameter:'',plungerBarrelType:'',plungerBarrelRebuildRepaired:false,plungerBarrelConditionStatus:'new',plungerBarrelInstalledDate:'',plungerBarrelEndCapInstalledDate:'',plungerBarrelLength:'',plungerBarrelDiameter:'',notes:'',criticalNotes:'',createdAt:'2026-01-01T12:00:00Z',updatedAt:'2026-08-20T12:00:00Z',brandColorHex:'#1E6BFF',historyPreview:[]};
const equipmentAsset={id:9802,assetNumber:'EQ-98',equipmentName:'Lifecycle Dryer',assetName:'Lifecycle Dryer',category:'Dryer',equipmentType:'Desiccant Dryer',manufacturer:'Matsui',brand:'Matsui',model:'E-98',serialNumber:'E98-SN',equipmentYear:'2023',year:'2023',location:'South Cell',department:'Molding',status:'active',criticality:'high',powerType:'Electric',voltage:'480 VAC',phase:'3 phase',amperage:'30 A',airRequirement:'90 PSI',waterRequirement:'N/A',capacityRating:'500 lb',dimensions:'48 x 36 x 84 in',weight:'825 lb',specificationNotes:'',createdAt:'2026-01-01T12:00:00Z',updatedAt:'2026-08-20T12:00:00Z'};

function issue(id:number,overrides:Record<string,unknown>={}){return{id,assetId:9800,title:`Warning issue ${id}`,noteDate:'2026-08-20',body:'Original bearing vibration problem statement.',warning:true,workOrder:`WO-${id}`,status:'active',createdBy:'Issue Creator',createdAt:'2026-08-20T12:00:00Z',updatedAt:'2026-08-20T12:00:00Z',resolvedAt:null,resolvedBy:'',resolutionSummary:'',resolvedYear:'',pdfFilename:`issue-${id}.pdf`,pdfUrl:`/api/machine-library/asset-notes/${id}/pdf`,pdfDownloadUrl:`/api/machine-library/asset-notes/${id}/pdf?download=true`,attachments:[],updates:[],lifecycle:[{id:id*10,type:'issue_created',actor:'Issue Creator',reason:'',createdAt:'2026-08-20T12:00:00Z'}],permissions:{...permissions},...overrides};}
function ordinary(id:number){return{id,assetId:9800,title:'Ordinary lubrication note',noteDate:'2026-08-19',body:'Lubrication checked with no warning condition.',warning:false,workOrder:'',status:'ordinary',createdBy:'Issue Creator',createdAt:'2026-08-19T12:00:00Z',updatedAt:'2026-08-19T12:00:00Z',pdfFilename:`ordinary-${id}.pdf`,pdfUrl:`/api/machine-library/asset-notes/${id}/pdf`,pdfDownloadUrl:`/api/machine-library/asset-notes/${id}/pdf?download=true`,attachments:[],updates:[],lifecycle:[],permissions:{...permissions,canResolve:false,canReopen:false,canAddUpdate:false}};}
function attachment(library:Library,id:number,filename:string,mimeType:string,fileSize:number){return{id,noteId:9810,filename,mimeType,fileSize,createdAt:'2026-08-20T12:10:00Z',contentUrl:`/api/${library}-library/asset-note-attachments/${id}/content`,downloadUrl:`/api/${library}-library/asset-note-attachments/${id}/content?download=true`};}

async function mockLibrary(page:Page,library:Library,primaryState:'active'|'resolved'='active'){
  const asset=library==='machine'?machineAsset:equipmentAsset;const assetId=asset.id;const notePhoto=attachment(library,9901,'bearing-photo.png','image/png',43812);const notePdf=attachment(library,9902,'inspection-report.pdf','application/pdf',91820);const updatePhoto={...attachment(library,9903,'repair-result.webp','image/webp',35804),noteId:undefined,updateId:9897};
  const primaryIssue=issue(9810,{assetId,assetNumber:asset.assetNumber,assetName:asset.assetName,workOrder:`WO-${library.toUpperCase()}-98`,title:`${library} active warning`,updatedAt:'2026-08-20T13:00:00Z',attachments:[notePhoto,notePdf],updates:[{id:9897,noteId:9810,body:'Initial inspection photographed before repair.',createdBy:'Inspection Technician',createdAt:'2026-08-20T12:30:00Z',attachments:[updatePhoto]}]});
  if(primaryState==='resolved')Object.assign(primaryIssue,{status:'resolved',resolvedAt:'2026-08-20T14:00:00Z',resolvedBy:'Lifecycle Admin',resolutionSummary:'Repair verified under production load.',resolvedYear:'2026',permissions:{...permissions,canResolve:false,canReopen:true,canAddUpdate:false},lifecycle:[...primaryIssue.lifecycle,{id:98981,type:'issue_resolved',actor:'Lifecycle Admin',reason:'Repair verified under production load.',createdAt:'2026-08-20T14:00:00Z'}]});
  let notes=[primaryIssue,issue(9814,{assetId,assetNumber:asset.assetNumber,assetName:asset.assetName,title:`${library} second active warning`,body:'Secondary active issue for accordion coverage.'}),issue(9811,{assetId,assetNumber:asset.assetNumber,assetName:asset.assetName,title:`${library} resolved 2026`,status:'resolved',resolvedAt:'2026-05-10T14:00:00Z',resolvedBy:'Maintenance Manager',resolutionSummary:'Verified repair.',resolvedYear:'2026',permissions:{...permissions,canResolve:false,canReopen:true,canAddUpdate:false}}),issue(9812,{assetId,assetNumber:asset.assetNumber,assetName:asset.assetName,title:`${library} resolved 2025`,status:'resolved',resolvedAt:'2025-09-10T14:00:00Z',resolvedBy:'Maintenance Manager',resolutionSummary:'Prior-year repair.',resolvedYear:'2025',permissions:{...permissions,canResolve:false,canReopen:true,canAddUpdate:false}}),ordinary(9813).valueOf()];
  await page.route('**/api/auth/status',route=>route.fulfill({json:{setupRequired:false,user:{id:1,fullName:'Lifecycle Admin',email:'admin@example.com',role:'Admin',isOwnerAdmin:true,forcePasswordChange:false}}}));
  await page.route(new RegExp(`/api/${library}-library/assets(?:\\?.*)?$`),route=>route.fulfill({json:library==='machine'?{ok:true,assets:[asset],brandSettings:[],permissions:{canEdit:true,canDelete:true,canManagePm:true}}:{ok:true,assets:[asset],categories:['Dryer'],permissions:{canEdit:true,canDelete:true,canManagePm:true}}}));
  await page.route(new RegExp(`/api/${library}-library/assets/${assetId}/notes$`),route=>route.fulfill({json:{ok:true,notes,permissions:{canCreate:true}}}));
  await page.route(new RegExp(`/api/${library}-library/assets/${assetId}/history$`),route=>route.fulfill({json:{ok:true,records:[]}}));
  await page.route(new RegExp(`/api/${library}-library/assets/${assetId}/inspection-records$`),route=>route.fulfill({json:{ok:true,records:[]}}));
  await page.route(new RegExp(`/api/${library}-library/assets/${assetId}/component-images$`),route=>route.fulfill({json:{ok:true,images:[]}}));
  await page.route(new RegExp(`/api/${library}-library/assets/${assetId}/preventive-maintenance$`),route=>route.fulfill({json:{ok:true,tasks:[],summary:{total:0,dueSoon:0,overdue:0,nextDueDate:null,nextDueMeter:null}}}));
  await page.route(new RegExp(`/api/${library}-library/assets/${assetId}/document-folders$`),route=>route.fulfill({json:{ok:true,folders:[],summary:{folderCount:0,documentCount:0}}}));
  await page.route(new RegExp(`/api/${library}-library/assets/${assetId}/documents$`),route=>route.fulfill({json:{ok:true,documents:[]}}));
  await page.route(new RegExp(`/api/${library}-library/asset-note-attachments/(9901|9903)/content(?:\\?.*)?$`),route=>route.fulfill({contentType:'image/png',body:Buffer.from('iVBORw0KGgoAAAANSUhEUgAAAAEAAAABCAQAAAC1HAwCAAAAC0lEQVR42mNk+A8AAQUBAScY42YAAAAASUVORK5CYII=','base64')}));
  await page.route(new RegExp(`/api/${library}-library/asset-notes/9810/updates$`),route=>{const current=notes.find(note=>note.id===9810)!;const update={id:9898,noteId:9810,body:'Bearing replaced and vibration tested under load.',createdBy:'Lifecycle Admin',createdAt:'2026-08-20T13:00:00Z',attachments:[]};current.updates=[...current.updates,update];current.lifecycle=[...current.lifecycle,{id:98980,type:'update_added',actor:'Lifecycle Admin',reason:'',createdAt:update.createdAt}];return route.fulfill({status:201,json:{ok:true,update,note:current}});});
  await page.route(new RegExp(`/api/${library}-library/asset-notes/9810/resolve$`),route=>{const current=notes.find(note=>note.id===9810)!;Object.assign(current,{status:'resolved',resolvedAt:'2026-08-20T14:00:00Z',resolvedBy:'Lifecycle Admin',resolutionSummary:'Repair verified under production load.',resolvedYear:'2026',permissions:{...permissions,canResolve:false,canReopen:true,canAddUpdate:false}});current.lifecycle=[...current.lifecycle,{id:98981,type:'issue_resolved',actor:'Lifecycle Admin',reason:'Repair verified under production load.',createdAt:current.resolvedAt}];return route.fulfill({json:{ok:true,note:current}});});
  await page.route(new RegExp(`/api/${library}-library/asset-notes/9810/reopen$`),route=>{const current=notes.find(note=>note.id===9810)!;Object.assign(current,{status:'active',resolvedAt:null,resolvedBy:'',resolutionSummary:'',resolvedYear:'',permissions:{...permissions}});current.lifecycle=[...current.lifecycle,{id:98982,type:'issue_reopened',actor:'Lifecycle Admin',reason:'Follow-up reading moved.',createdAt:'2026-08-20T15:00:00Z'}];return route.fulfill({json:{ok:true,note:current}});});
  await page.route(new RegExp(`/api/${library}-library/asset-notes/9810$`),route=>{if(route.request().method()==='DELETE'){notes=notes.filter(note=>note.id!==9810);return route.fulfill({json:{ok:true,historyPreserved:true}});}return route.fallback();});
  return{asset,assetId};
}

async function getDeclaredTargetGlow(page:Page){
  return page.evaluate(()=>{
    const findRule=(rules:CSSRuleList):{animation:string}|null=>{
      for(const rule of Array.from(rules)){
        if(rule.type===CSSRule.STYLE_RULE){
          const styleRule=rule as CSSStyleRule;
          if(styleRule.selectorText.includes('.asset-note-active-issue-card.is-deep-link-target::after')&&styleRule.style.animation.includes('asset-note-target-glow-pulse'))return{animation:styleRule.style.animation};
        }
        const nestedRules=(rule as CSSMediaRule).cssRules;
        if(nestedRules){const match=findRule(nestedRules);if(match)return match;}
      }
      return null;
    };
    for(const sheet of Array.from(document.styleSheets)){try{const match=findRule(sheet.cssRules);if(match)return match;}catch{/* Cross-origin stylesheets are irrelevant to the application rule. */}}
    return null;
  });
}

for(const library of ['machine','equipment'] as const){
  test(`${library} warning issue deep link opens, reveals, and focuses the target note`,async({page})=>{
    await page.emulateMedia({reducedMotion:'no-preference'});
    const{assetId}=await mockLibrary(page,library);await page.goto(`/${library}-library?asset=${assetId}&note=9810`);
    const notesToggle=page.getByRole('button',{name:/Asset Notes & Attachments/});await expect(notesToggle).toHaveAttribute('aria-expanded','true');let target=page.locator(`#asset-note-${assetId}-9810`);await expect(target).toHaveClass(/is-deep-link-target/);
    const declaredGlow=await getDeclaredTargetGlow(page);expect(declaredGlow).not.toBeNull();expect(declaredGlow!.animation).toContain('asset-note-target-glow-pulse');expect(declaredGlow!.animation).toMatch(/(?:^|\s)0?\.72s(?:\s|$)/);expect(declaredGlow!.animation).toMatch(/(?:^|\s)2(?:\s|$)/);
    const normalHighlight=await target.evaluate(element=>{const card=getComputedStyle(element);const glow=getComputedStyle(element,'::after');return{background:glow.backgroundImage,transform:glow.transform,outlineStyle:card.outlineStyle,outlineWidth:card.outlineWidth,outlineColor:card.outlineColor,cardShadow:card.boxShadow,glowBorderStyle:glow.borderTopStyle,glowBorderWidth:glow.borderTopWidth,glowBorderColor:glow.borderTopColor,glowOpacity:Number(glow.opacity),glowShadow:glow.boxShadow};});expect(normalHighlight).toMatchObject({background:'none',transform:'none',outlineStyle:'solid',outlineWidth:'1px',glowBorderStyle:'solid',glowBorderWidth:'1px'});expect(normalHighlight.outlineColor).not.toBe('transparent');expect(normalHighlight.glowBorderColor).not.toBe('transparent');expect(normalHighlight.cardShadow).not.toBe('none');expect(normalHighlight.glowShadow).not.toBe('none');expect(normalHighlight.glowOpacity).toBeGreaterThanOrEqual(.4);let issueToggle=target.locator('.asset-note-issue-toggle');await expect(issueToggle).toHaveAttribute('aria-expanded','true');await expect(page.locator(`#asset-note-${assetId}-9814 .asset-note-issue-toggle`)).toHaveAttribute('aria-expanded','false');await expect(page.locator('.asset-note-issue-toggle[aria-expanded="true"]')).toHaveCount(1);await expect(issueToggle).toBeFocused();await expect(target.locator('.asset-note-body-preview')).toHaveText('Original bearing vibration problem statement.');await expect(target).toBeInViewport({ratio:.01});

    await page.emulateMedia({reducedMotion:'reduce'});await page.reload();target=page.locator(`#asset-note-${assetId}-9810`);await expect(target).toHaveClass(/is-deep-link-target/);
    const staticHighlight=await target.evaluate(element=>{const card=getComputedStyle(element);const glow=getComputedStyle(element,'::after');return{animation:glow.animationName,background:glow.backgroundImage,outlineStyle:card.outlineStyle,outlineWidth:card.outlineWidth,outlineColor:card.outlineColor,cardShadow:card.boxShadow,glowBorderStyle:glow.borderTopStyle,glowBorderWidth:glow.borderTopWidth,glowBorderColor:glow.borderTopColor,glowOpacity:Number(glow.opacity),glowShadow:glow.boxShadow};});
    expect(staticHighlight).toMatchObject({animation:'none',background:'none',outlineStyle:'solid',outlineWidth:'2px',glowBorderStyle:'solid',glowBorderWidth:'1px'});expect(staticHighlight.outlineColor).not.toBe('transparent');expect(staticHighlight.glowBorderColor).not.toBe('transparent');expect(staticHighlight.cardShadow).not.toBe('none');expect(staticHighlight.glowShadow).not.toBe('none');expect(staticHighlight.glowOpacity).toBeGreaterThanOrEqual(.6);issueToggle=target.locator('.asset-note-issue-toggle');await expect(issueToggle).toBeFocused();
    await page.goto(`/${library}-library?asset=${assetId}&note=9811`);const historyDialog=page.getByRole('dialog',{name:`Resolved History for ${library==='machine'?'PRESS-98':'EQ-98'}`});await expect(historyDialog).toBeVisible();const resolvedYear=historyDialog.getByRole('button',{name:/2026.*resolved issue/});await expect(resolvedYear).toHaveAttribute('aria-expanded','true');await expect(resolvedYear).toHaveCSS('animation-name','none');target=historyDialog.locator(`#asset-note-${assetId}-9811`);await expect(target).toHaveClass(/is-deep-link-target/);await expect(target.getByRole('button',{name:'Open Note PDF'})).toBeFocused();
  });

  test(`${library} image viewer provides complete bounded zoom and pan coverage`,async({page})=>{
    await page.emulateMedia({reducedMotion:'no-preference'});
    const{assetId}=await mockLibrary(page,library);await page.goto(`/${library}-library?asset=${assetId}`);await page.getByRole('button',{name:/Asset Notes & Attachments/}).click();
    const activeCard=page.locator('.asset-note-active-issue-card',{hasText:`${library} active warning`});await activeCard.locator('.asset-note-issue-toggle').click();const notePhoto=activeCard.locator('.asset-attachment-chip',{hasText:'bearing-photo.png'});await expect(notePhoto.locator('img.asset-attachment-thumbnail')).toHaveAttribute('src',new RegExp(`/api/${library}-library/asset-note-attachments/9901/content$`));await expect(notePhoto.locator('img.asset-attachment-thumbnail')).toHaveAttribute('loading','lazy');const pdfChip=activeCard.locator('.asset-attachment-chip',{hasText:'inspection-report.pdf'});await expect(pdfChip.locator('.asset-file-icon')).toHaveText('PDF');await expect(notePhoto.getByRole('button',{name:'Download'})).toBeVisible();await expect(notePhoto.getByRole('button',{name:/More actions/})).toBeVisible();const [cardBox,chipBox]=await Promise.all([activeCard.boundingBox(),notePhoto.boundingBox()]);expect(cardBox).not.toBeNull();expect(chipBox).not.toBeNull();if(page.viewportSize()!.width>700)expect(chipBox!.width).toBeLessThan(cardBox!.width*.7);else expect(chipBox!.width).toBeLessThanOrEqual(cardBox!.width);await expect(activeCard.locator('img.asset-attachment-thumbnail')).toHaveCount(2);
    await notePhoto.getByRole('button',{name:'Open bearing-photo.png'}).click();const imageViewer=page.getByRole('dialog',{name:'bearing-photo.png viewer'});const imageCanvas=imageViewer.getByRole('region',{name:/Image preview/});const zoomOutput=imageViewer.locator('output');await expect(imageViewer.locator('img')).toHaveAttribute('src',new RegExp('/asset-note-attachments/9901/content$'));await expect(zoomOutput).toHaveText('100%');await expect(imageViewer.getByRole('button',{name:'Zoom out'})).toBeDisabled();const wheelCancelled=await imageCanvas.evaluate(element=>!element.dispatchEvent(new WheelEvent('wheel',{deltaY:120,bubbles:true,cancelable:true})));expect(wheelCancelled).toBe(true);await expect(zoomOutput).toHaveText('100%');await imageCanvas.evaluate(element=>{for(let index=0;index<45;index+=1)element.dispatchEvent(new WheelEvent('wheel',{deltaY:-120,bubbles:true,cancelable:true}));});await expect(zoomOutput).toHaveText('1000%');await expect(imageViewer.getByRole('button',{name:'Zoom in'})).toBeDisabled();
    const beforePan=await imageViewer.locator('img').evaluate(element=>getComputedStyle(element).transform);const canvasBox=await imageCanvas.boundingBox();expect(canvasBox).not.toBeNull();await page.mouse.move(canvasBox!.x+canvasBox!.width/2,canvasBox!.y+canvasBox!.height/2);await page.mouse.down();await page.mouse.move(canvasBox!.x+canvasBox!.width*.7,canvasBox!.y+canvasBox!.height*.7,{steps:4});await page.mouse.up();const afterPan=await imageViewer.locator('img').evaluate(element=>getComputedStyle(element).transform);expect(afterPan).not.toBe(beforePan);expect(await imageViewer.locator('img').evaluate((image,canvas)=>{const imageRect=image.getBoundingClientRect();const canvasRect=(canvas as Element).getBoundingClientRect();return imageRect.right>=canvasRect.left&&imageRect.left<=canvasRect.right&&imageRect.bottom>=canvasRect.top&&imageRect.top<=canvasRect.bottom;},await imageCanvas.elementHandle())).toBe(true);
    await imageViewer.getByRole('button',{name:'Reset / 100%'}).click();await expect(zoomOutput).toHaveText('100%');await expect(imageViewer.locator('img')).toHaveCSS('transform','matrix(1, 0, 0, 1, 0, 0)');await imageViewer.getByRole('button',{name:'Zoom in'}).focus();await page.keyboard.press('Enter');await expect(zoomOutput).toHaveText('125%');await imageCanvas.focus();await page.keyboard.press('0');await expect(zoomOutput).toHaveText('100%');await page.emulateMedia({reducedMotion:'reduce'});await expect(imageViewer.locator('img')).toHaveCSS('transition-duration','0s');await page.keyboard.press('Escape');await expect(imageViewer).toHaveCount(0);
    await page.emulateMedia({reducedMotion:'no-preference'});const updatePhoto=activeCard.locator('.asset-attachment-chip',{hasText:'repair-result.webp'});await updatePhoto.getByRole('button',{name:'Open repair-result.webp'}).click();const updateViewer=page.getByRole('dialog',{name:'repair-result.webp viewer'});await expect(updateViewer.locator('output')).toHaveText('100%');await expect(updateViewer.getByRole('group',{name:'Image zoom controls'})).toBeVisible();await updateViewer.getByRole('button',{name:'Close'}).first().click();await expect(updateViewer).toHaveCount(0);
  });

  test(`${library} warning issue active lifecycle supports accordion, update, resolve, and history folders`,async({page})=>{
    await page.emulateMedia({reducedMotion:'no-preference'});
    const{asset,assetId}=await mockLibrary(page,library);await page.goto(`/${library}-library?asset=${assetId}`);await page.getByRole('button',{name:/Asset Notes & Attachments/}).click();
    const activeCard=page.locator('.asset-note-active-issue-card',{hasText:`${library} active warning`});const activeToggle=activeCard.locator('.asset-note-issue-toggle');const secondCard=page.locator('.asset-note-active-issue-card',{hasText:`${library} second active warning`});const secondToggle=secondCard.locator('.asset-note-issue-toggle');await expect(activeCard).toContainText(`WO-${library.toUpperCase()}-98`);const datePill=activeToggle.locator('.asset-note-date-pill');await expect(datePill).toBeVisible();await expect(datePill).toHaveCSS('color','rgb(255, 255, 255)');await expect(activeToggle).toHaveAttribute('aria-expanded','false');await expect(activeCard.getByRole('button',{name:'+ Add Update'})).toHaveCount(0);await activeToggle.focus();await page.keyboard.press('Enter');await expect(activeToggle).toHaveAttribute('aria-expanded','true');const createdMeta=activeCard.locator('.asset-note-created-meta');await expect(createdMeta).toContainText(/Created by Issue Creator.*record updated/);expect(Number.parseFloat(await createdMeta.evaluate(element=>getComputedStyle(element).fontSize))).toBeGreaterThanOrEqual(12);await secondToggle.click();await expect(secondToggle).toHaveAttribute('aria-expanded','true');await expect(activeToggle).toHaveAttribute('aria-expanded','false');await expect(page.locator('.asset-note-issue-toggle[aria-expanded="true"]')).toHaveCount(1);await activeToggle.click();await expect(activeToggle).toHaveAttribute('aria-expanded','true');await expect(secondToggle).toHaveAttribute('aria-expanded','false');await expect(page.locator('.asset-note-issue-toggle[aria-expanded="true"]')).toHaveCount(1);await expect(activeCard.locator('.asset-note-body-preview')).toHaveText('Original bearing vibration problem statement.');await expect(activeCard.getByRole('button',{name:'+ Add Update'})).toBeVisible();
    await activeCard.getByRole('button',{name:'+ Add Update'}).click();const updateField=activeCard.getByLabel('Maintenance work / progress update *');await expect(updateField).toBeFocused();await updateField.fill('Bearing replaced and vibration tested under load.');await activeCard.getByRole('button',{name:'Add Update',exact:true}).click();await expect(activeCard).toContainText('Bearing replaced and vibration tested under load.');await expect(activeCard).toContainText('Lifecycle Admin');await expect(activeCard.locator('.asset-note-body-preview')).toHaveText('Original bearing vibration problem statement.');
    await activeCard.getByRole('button',{name:'Issue is Resolved'}).click();await expect(activeCard.getByRole('checkbox',{name:/Issue is Resolved/})).toBeChecked();await activeCard.getByLabel('Resolution Summary *').fill('Repair verified under production load.');await activeCard.getByRole('button',{name:'Confirm Resolution'}).click();await expect(page.getByRole('status')).toContainText('removed from Dashboard attention');
    await expect(page.locator('.asset-note-resolved-history')).toHaveCount(0);await expect(page.getByText('Maintenance Archive')).toHaveCount(0);const historyControl=page.getByRole('button',{name:/Open Resolved History, 3 resolved issues/});await expect(historyControl).toBeVisible();await historyControl.click();let history=page.getByRole('dialog',{name:`Resolved History for ${asset.assetNumber}`});await expect(history).toBeVisible();await expect(history.getByRole('button',{name:'Close'})).toBeFocused();const year2026=history.getByRole('button',{name:/2026.*resolved issue/});const yearFolderIcon=year2026.locator('[data-file-type="folder"]');await expect(year2026).toHaveAttribute('aria-expanded','false');await expect(yearFolderIcon).toHaveAttribute('data-state','closed');await year2026.click();await expect(year2026).toHaveAttribute('aria-expanded','true');expect(await year2026.evaluate(element=>{const style=getComputedStyle(element);return{name:style.animationName,duration:style.animationDuration,count:style.animationIterationCount};})).toEqual({name:'asset-note-folder-glow-pulse',duration:'0.72s',count:'2'});await expect(yearFolderIcon).toHaveAttribute('data-state','open');await expect(history.getByText(`${library} active warning`)).toBeVisible();
    const year2025=history.getByRole('button',{name:/2025.*resolved issue/});await year2025.click();await expect(history.getByText(`${library} resolved 2025`)).toBeVisible();await page.keyboard.press('Escape');await expect(history).toHaveCount(0);await expect(historyControl).toBeFocused();
  });

  test(`${library} warning issue resolved lifecycle supports filtering, reopen, and audited delete`,async({page})=>{
    const{asset,assetId}=await mockLibrary(page,library,'resolved');await page.goto(`/${library}-library?asset=${assetId}`);await page.getByRole('button',{name:/Asset Notes & Attachments/}).click();
    await page.getByLabel('Search Asset Notes').fill(`WO-${library.toUpperCase()}-98`);await page.getByLabel('Note status').selectOption('resolved');const history=page.getByRole('dialog',{name:`Resolved History for ${asset.assetNumber}`});await expect(history).toBeVisible();await expect(history.getByText(`${library} resolved 2026`)).toHaveCount(0);const filteredYear=history.getByRole('button',{name:/2026.*1 resolved issue/});if(await filteredYear.getAttribute('aria-expanded')!=='true')await filteredYear.click();const resolvedCard=history.locator('.asset-note-entry',{hasText:`${library} active warning`});await expect(resolvedCard).toContainText(asset.assetNumber);await expect(resolvedCard).toContainText('Repair verified under production load.');await resolvedCard.getByRole('button',{name:'Reopen Issue'}).click();await resolvedCard.getByLabel('Reopen Reason *').fill('Follow-up reading moved.');await resolvedCard.getByRole('button',{name:'Reopen Issue'}).last().click();await expect(page.getByRole('status')).toContainText('restored to Dashboard attention');await page.keyboard.press('Escape');await expect(history).toHaveCount(0);
    await page.getByLabel('Search Asset Notes').fill('');await page.getByLabel('Note status').selectOption('all');const reopenedCard=page.locator('.asset-note-active-issue-card',{hasText:`${library} active warning`});const reopenedToggle=reopenedCard.locator('.asset-note-issue-toggle');await expect(reopenedToggle).toHaveAttribute('aria-expanded','false');await reopenedToggle.focus();await page.keyboard.press('Space');await expect(reopenedToggle).toHaveAttribute('aria-expanded','true');await expect(reopenedCard.getByRole('button',{name:'+ Add Update'})).toBeVisible();
    await reopenedCard.getByRole('button',{name:`More actions for ${library} active warning`}).click();await page.getByRole('menuitem',{name:'Delete Note'}).click();await expect(reopenedCard.getByLabel('Delete Reason *')).toBeVisible();await reopenedCard.getByLabel('Delete Reason *').fill('Duplicate issue retired after review.');page.once('dialog',dialog=>dialog.accept());await reopenedCard.getByRole('button',{name:'Delete Warning Issue'}).click();await expect(page.getByRole('status')).toContainText('audit evidence preserved');await expect(page.getByText(`${library} active warning`)).toHaveCount(0);
    const overflow=await page.evaluate(()=>document.documentElement.scrollWidth-document.documentElement.clientWidth);expect(overflow).toBeLessThanOrEqual(1);
  });
}
