import {expect,type Locator,type Page,test} from '@playwright/test';

type Library='machine'|'equipment';
async function expectPillAction(button:Locator){
  const geometry=await button.evaluate(element=>({radius:parseFloat(getComputedStyle(element).borderTopLeftRadius),height:element.getBoundingClientRect().height,touch:matchMedia('(pointer:coarse), (max-width:700px)').matches}));
  expect(geometry.radius).toBeGreaterThanOrEqual(geometry.height/2);
  if(geometry.touch)expect(geometry.height).toBeGreaterThanOrEqual(44);
}
const permissions={canEdit:true,canDelete:true,canResolve:true,canReopen:false,canAddUpdate:true,canDeleteAttachments:true};
const machineAsset={id:9801,assetNumber:'PRESS-98',assetName:'Lifecycle Press',brand:'Toyo',model:'M-98',serialNumber:'M98-SN',machineYear:'2022',machineType:'Injection Molding Machine',powerType:'Electric',setupType:'Standard Injection',shotSizeOz:12,tonnage:250,barrelDiameter:'35mm',location:'North Cell',department:'Molding',status:'active',voltageValue:'480',voltageType:'AC',fullLoadAmp:'120',machineLength:'20 ft',machineWidth:'7 ft',machineHeight:'8 ft',fullDieHeightLength:'48 in',screwType:'GP',screwTipType:'Ring',screwTipInstalledDate:'',screwInstalledDate:'',barrelInstalledDate:'',barrelEndCapInstalledDate:'',barrelLength:'96 in',screwLength:'92 in',screwRebuildRepaired:false,barrelRebuildRepaired:false,screwConditionStatus:'used',barrelConditionStatus:'used',hasDoubleShotInjection:false,hasPlungerInjection:false,screw2Type:'',screw2TipType:'',screw2RebuildRepaired:false,screw2ConditionStatus:'new',screw2InstalledDate:'',screw2TipInstalledDate:'',screw2Length:'',barrel2Diameter:'',barrel2RebuildRepaired:false,barrel2ConditionStatus:'new',barrel2InstalledDate:'',barrel2EndCapInstalledDate:'',barrel2Length:'',plungerType:'',plungerRebuildRepaired:false,plungerConditionStatus:'new',plungerInstalledDate:'',plungerLength:'',plungerDiameter:'',plungerBarrelType:'',plungerBarrelRebuildRepaired:false,plungerBarrelConditionStatus:'new',plungerBarrelInstalledDate:'',plungerBarrelEndCapInstalledDate:'',plungerBarrelLength:'',plungerBarrelDiameter:'',notes:'',criticalNotes:'',createdAt:'2026-01-01T12:00:00Z',updatedAt:'2026-08-20T12:00:00Z',brandColorHex:'#1E6BFF',historyPreview:[]};
const equipmentAsset={id:9802,assetNumber:'EQ-98',equipmentName:'Lifecycle Dryer',assetName:'Lifecycle Dryer',category:'Dryer',equipmentType:'Desiccant Dryer',manufacturer:'Matsui',brand:'Matsui',model:'E-98',serialNumber:'E98-SN',equipmentYear:'2023',year:'2023',location:'South Cell',department:'Molding',status:'active',criticality:'high',powerType:'Electric',voltage:'480 VAC',phase:'3 phase',amperage:'30 A',airRequirement:'90 PSI',waterRequirement:'N/A',capacityRating:'500 lb',dimensions:'48 x 36 x 84 in',weight:'825 lb',specificationNotes:'',createdAt:'2026-01-01T12:00:00Z',updatedAt:'2026-08-20T12:00:00Z'};

function issue(id:number,overrides:Record<string,unknown>={}){return{id,assetId:9800,title:`Warning issue ${id}`,noteDate:'2026-08-20',body:'Original bearing vibration problem statement.',warning:true,workOrder:`WO-${id}`,status:'active',createdBy:'Issue Creator',createdAt:'2026-08-20T12:00:00Z',updatedAt:'2026-08-20T12:00:00Z',resolvedAt:null,resolvedBy:'',resolutionSummary:'',resolvedYear:'',pdfFilename:`issue-${id}.pdf`,pdfUrl:`/api/machine-library/asset-notes/${id}/pdf`,pdfDownloadUrl:`/api/machine-library/asset-notes/${id}/pdf?download=true`,attachments:[],updates:[],lifecycle:[{id:id*10,type:'issue_created',actor:'Issue Creator',reason:'',createdAt:'2026-08-20T12:00:00Z'}],permissions:{...permissions},...overrides};}
function ordinary(id:number){return{id,assetId:9800,title:'Ordinary lubrication note',noteDate:'2026-08-19',body:'Lubrication checked with no warning condition.',warning:false,workOrder:'',status:'ordinary',createdBy:'Issue Creator',createdAt:'2026-08-19T12:00:00Z',updatedAt:'2026-08-19T12:00:00Z',pdfFilename:`ordinary-${id}.pdf`,pdfUrl:`/api/machine-library/asset-notes/${id}/pdf`,pdfDownloadUrl:`/api/machine-library/asset-notes/${id}/pdf?download=true`,attachments:[],updates:[],lifecycle:[],permissions:{...permissions,canResolve:false,canReopen:false,canAddUpdate:false}};}
function attachment(library:Library,id:number,filename:string,mimeType:string,fileSize:number){return{id,noteId:9810,filename,mimeType,fileSize,createdAt:'2026-08-20T12:10:00Z',contentUrl:`/api/${library}-library/asset-note-attachments/${id}/content`,downloadUrl:`/api/${library}-library/asset-note-attachments/${id}/content?download=true`};}

async function mockLibrary(page:Page,library:Library,primaryState:'active'|'resolved'='active',updateCanEdit=true,correctionWindow=false,daily=false,currentUserId=1,grouped=false){
  const asset=library==='machine'?machineAsset:equipmentAsset;const assetId=asset.id;const notePhoto=attachment(library,9901,'bearing-photo.png','image/png',43812);const notePdf=attachment(library,9902,'inspection-report.pdf','application/pdf',91820);const updatePhoto={...attachment(library,9903,'repair-result.webp','image/webp',35804),noteId:undefined,updateId:9897};
  const primaryIssue=issue(9810,{assetId,assetNumber:asset.assetNumber,assetName:asset.assetName,workOrder:`WO-${library.toUpperCase()}-98`,title:`${library} active warning`,hold:true,updatedAt:'2026-08-20T13:00:00Z',attachments:[notePhoto,notePdf],updates:[{id:9897,noteId:9810,body:'Initial inspection photographed before repair.',createdByUserId:1,createdBy:'Inspection Technician',createdAt:'2026-08-20T12:30:00Z',canEdit:primaryState==='active'&&updateCanEdit,attachments:[updatePhoto]}]});
  if(primaryState==='resolved')Object.assign(primaryIssue,{status:'resolved',resolvedAt:'2026-08-20T14:00:00Z',resolvedBy:'Lifecycle Admin',resolutionSummary:'Repair verified under production load.',resolvedYear:'2026',permissions:{...permissions,canResolve:false,canReopen:true,canAddUpdate:false},lifecycle:[...primaryIssue.lifecycle,{id:98981,type:'issue_resolved',actor:'Lifecycle Admin',reason:'Repair verified under production load.',createdAt:'2026-08-20T14:00:00Z'}]});
  if(correctionWindow){
    Object.assign(primaryIssue,{technicianUpdateWindowOpen:true,technicianUpdateLockAt:'2026-08-22T14:00:00Z',technicianUpdateServerTime:'2026-08-22T13:55:00Z',permissions:{...permissions,canResolve:false,canReopen:true,canAddUpdate:true}});
    primaryIssue.updates[0].canEdit=updateCanEdit;
  }
  if(daily){Object.assign(primaryIssue.updates[0],{createdBy:'Jeffery R Grove',createdByUserId:1,body:'Day A',laborHours:1.5,entries:[{id:111,updateId:9897,workDate:'2026-10-01',body:'Day A',laborHours:.5,createdAt:'2026-10-01T12:00:00Z'},{id:112,updateId:9897,workDate:'2026-10-02',body:'Day B',laborHours:.75,createdAt:'2026-10-02T12:00:00Z'},{id:113,updateId:9897,workDate:'2026-10-03',body:'Day C',laborHours:.25,createdAt:'2026-10-03T12:00:00Z'}]});
    primaryIssue.updates.push({id:9899,noteId:9810,body:'Assisted with motor alignment.',createdByUserId:2,createdBy:'Alex Smith',createdAt:'2026-10-03T13:00:00Z',canEdit:false,attachments:[],entries:[{id:201,updateId:9899,workDate:'2026-10-03',body:'Assisted with motor alignment.',laborHours:.75,createdAt:'2026-10-03T13:00:00Z'}],laborHours:.75} as typeof primaryIssue.updates[number]);
    Object.assign(primaryIssue,{labor:[{id:1,userId:1,displayName:'Jeffery R Grove',hours:1.5,manualHours:0,dailyHours:1.5,isPrimary:true,order:0},{id:0,userId:2,displayName:'Alex Smith',hours:.75,manualHours:0,dailyHours:.75,isPrimary:false,order:1}],totalLaborHours:2.25,technicianCompletionEntryId:null});
  }
  if(grouped){primaryIssue.updates.push({id:9905,noteId:9810,createdByUserId:1,createdBy:'Jeff Grove',body:'Historic same-owner work.',createdAt:'2026-10-02T14:00:00Z',canEdit:true,laborHours:.5,attachments:[{...attachment(library,9910,'entry-inspection.pdf','application/pdf',100),updateId:9905,entryId:501}],entries:[{id:501,updateId:9905,workDate:'2026-10-02',body:'Historic same-owner work.',laborHours:.5,createdAt:'2026-10-02T14:00:00Z'}]} as typeof primaryIssue.updates[number]);primaryIssue.updates.push({id:9906,noteId:9810,createdByUserId:3,createdBy:'Jeff Grove',body:'Separate identity work.',createdAt:'2026-10-02T15:00:00Z',canEdit:false,attachments:[],laborHours:.25,entries:[{id:502,updateId:9906,workDate:'2026-10-02',body:'Separate identity work.',laborHours:.25,createdAt:'2026-10-02T15:00:00Z'}]} as typeof primaryIssue.updates[number]);}
  let notes=[primaryIssue,issue(9814,{assetId,assetNumber:asset.assetNumber,assetName:asset.assetName,title:`${library} second active warning`,body:'Secondary active issue for accordion coverage.'}),issue(9811,{assetId,assetNumber:asset.assetNumber,assetName:asset.assetName,title:`${library} resolved 2026`,status:'resolved',resolvedAt:'2026-05-10T14:00:00Z',resolvedBy:'Maintenance Manager',resolutionSummary:'Verified repair.',resolvedYear:'2026',permissions:{...permissions,canResolve:false,canReopen:true,canAddUpdate:false}}),issue(9812,{assetId,assetNumber:asset.assetNumber,assetName:asset.assetName,title:`${library} resolved 2025`,status:'resolved',resolvedAt:'2025-09-10T14:00:00Z',resolvedBy:'Maintenance Manager',resolutionSummary:'Prior-year repair.',resolvedYear:'2025',permissions:{...permissions,canResolve:false,canReopen:true,canAddUpdate:false}}),ordinary(9813).valueOf()];
  await page.route('**/api/auth/status',route=>route.fulfill({json:{setupRequired:false,user:{id:1,fullName:'Lifecycle Admin',email:'admin@example.com',role:'Admin',isOwnerAdmin:true,forcePasswordChange:false}}}));
  await page.route(new RegExp(`/api/${library}-library/assets(?:\\?.*)?$`),route=>route.fulfill({json:library==='machine'?{ok:true,assets:[asset],brandSettings:[],permissions:{canEdit:true,canDelete:true,canManagePm:true}}:{ok:true,assets:[asset],categories:['Dryer'],permissions:{canEdit:true,canDelete:true,canManagePm:true}}}));
  await page.route(new RegExp(`/api/${library}-library/assets/${assetId}/notes$`),route=>route.fulfill({json:{ok:true,notes,currentUser:{id:currentUserId,fullName:'Current Technician',email:'technician@example.com',role:'Technician'},permissions:{canCreate:true}}}));
  await page.route(new RegExp(`/api/${library}-library/assets/${assetId}/history$`),route=>route.fulfill({json:{ok:true,records:[]}}));
  await page.route(new RegExp(`/api/${library}-library/assets/${assetId}/inspection-records$`),route=>route.fulfill({json:{ok:true,records:[]}}));
  await page.route(new RegExp(`/api/${library}-library/assets/${assetId}/component-images$`),route=>route.fulfill({json:{ok:true,images:[]}}));
  await page.route(new RegExp(`/api/${library}-library/assets/${assetId}/preventive-maintenance$`),route=>route.fulfill({json:{ok:true,tasks:[],summary:{total:0,dueSoon:0,overdue:0,nextDueDate:null,nextDueMeter:null}}}));
  await page.route(new RegExp(`/api/${library}-library/assets/${assetId}/document-folders$`),route=>route.fulfill({json:{ok:true,folders:[],summary:{folderCount:0,documentCount:0}}}));
  await page.route(new RegExp(`/api/${library}-library/assets/${assetId}/documents$`),route=>route.fulfill({json:{ok:true,documents:[]}}));
  await page.route(new RegExp(`/api/${library}-library/asset-note-attachments/(9901|9903)/content(?:\\?.*)?$`),route=>route.fulfill({contentType:'image/png',body:Buffer.from('iVBORw0KGgoAAAANSUhEUgAAAAEAAAABCAQAAAC1HAwCAAAAC0lEQVR42mNk+A8AAQUBAScY42YAAAAASUVORK5CYII=','base64')}));
  await page.route(new RegExp(`/api/${library}-library/asset-notes/9810/updates/\\d+/entries(?:/\\d+)?$`),route=>{
    const current=notes.find(note=>note.id===9810)!;const thread=current.updates.find(update=>update.id===Number(route.request().url().match(/updates\/(\d+)/)![1]))! as typeof current.updates[0]&{entries:Array<{id:number;updateId:number;workDate:string;body:string;laborHours:number;createdAt:string}>;laborHours:number};
    thread.entries??=[{id:0,updateId:thread.id,workDate:'2026-08-20',body:thread.body,laborHours:0,createdAt:thread.createdAt}];const multipart=route.request().postData()??'';const field=(name:string)=>multipart.match(new RegExp(`name="${name}"\\r\\n\\r\\n([^]*?)\\r\\n--`))?.[1]??'';
    const entryId=Number(route.request().url().split('/').at(-1));const correction=route.request().method()==='PATCH';const entry=correction?thread.entries.find(entry=>entry.id===entryId)!:{id:current.reopenedAt?401:300+thread.entries.length,updateId:thread.id,workDate:'',body:'',laborHours:0,createdAt:current.reopenedAt?'2026-10-06T12:00:00Z':'2026-10-04T12:00:00Z'};
    Object.assign(entry,{workDate:field('workDate'),body:field('body'),laborHours:Number(field('laborHours'))});const addedFile=multipart.match(/filename="([^"]+)"/);if(addedFile)thread.attachments.push({...attachment(library,9911,addedFile[1],'image/png',42),updateId:thread.id,entryId:entry.id} as typeof thread.attachments[number]);if(!correction)thread.entries.push(entry);thread.entries.sort((a,b)=>a.workDate.localeCompare(b.workDate)||a.id-b.id);if(entry.id===111||entry.id===0)thread.body=entry.body;thread.laborHours=thread.entries.reduce((sum,entry)=>sum+entry.laborHours,0);
    Object.assign(current,{labor:[{id:1,userId:1,displayName:'Jeffery R Grove',hours:thread.laborHours,manualHours:0,dailyHours:thread.laborHours,isPrimary:true,order:0},{id:0,userId:2,displayName:'Alex Smith',hours:.75,manualHours:0,dailyHours:.75,isPrimary:false,order:1}],totalLaborHours:thread.laborHours+.75});
    return route.fulfill({status:correction?200:201,json:{ok:true,entry,update:thread,note:current}});
  });
  await page.route(new RegExp(`/api/${library}-library/asset-notes/9810/updates$`),route=>{const current=notes.find(note=>note.id===9810)!;const update={id:9898,noteId:9810,body:'Bearing replaced and vibration tested under load.',createdByUserId:currentUserId,canEdit:true,createdBy:'Lifecycle Admin',createdAt:'2026-08-20T13:00:00Z',attachments:[]};if(daily)Object.assign(update,{createdBy:'Jeffery R Grove',canEdit:true,createdAt:'2026-10-06T13:00:00Z',entries:[{id:401,updateId:9898,workDate:'2026-10-06',body:update.body,laborHours:.25,createdAt:'2026-10-06T13:00:00Z'}],laborHours:.25});current.updates=[...current.updates,update];current.lifecycle=[...current.lifecycle,{id:98980,type:'update_added',actor:'Lifecycle Admin',reason:'',createdAt:update.createdAt}];return route.fulfill({status:201,json:{ok:true,update,note:current}});});
  await page.route(new RegExp(`/api/${library}-library/asset-notes/9810/updates/9897$`),route=>{const current=notes.find(note=>note.id===9810)!;const update=current.updates[0];Object.assign(update,{body:'Corrected inspection and final reading.',updatedAt:'2026-08-20T15:00:00Z',updatedBy:'Lifecycle Admin',attachments:[...update.attachments,{...attachment(library,9904,'later-photo.png','image/png',42),noteId:undefined,updateId:9897}]});return route.fulfill({json:{ok:true,update,note:current}});});
  await page.route(new RegExp(`/api/${library}-library/asset-notes/9810/resolve$`),route=>{const current=notes.find(note=>note.id===9810)!;Object.assign(current,{status:'resolved',resolvedAt:'2026-08-20T14:00:00Z',resolvedBy:'Lifecycle Admin',resolutionSummary:'Repair verified under production load.',resolvedYear:'2026',permissions:{...permissions,canResolve:false,canReopen:true,canAddUpdate:false}});if(daily)Object.assign(current,{resolvedAt:current.reopenedAt?'2026-10-07T14:00:00Z':'2026-10-04T14:00:00Z',technicianCompletionEntryId:current.reopenedAt?current.updates.at(-1)?.entries?.at(-1)?.id:201});current.lifecycle=[...current.lifecycle,{id:98981,type:'issue_resolved',actor:'Lifecycle Admin',reason:'Repair verified under production load.',createdAt:current.resolvedAt}];return route.fulfill({json:{ok:true,note:current}});});
  await page.route(new RegExp(`/api/${library}-library/asset-notes/9810/reopen$`),route=>{const current=notes.find(note=>note.id===9810)!;Object.assign(current,{status:'active',resolvedAt:null,resolvedBy:'',resolutionSummary:'',resolvedYear:'',permissions:{...permissions}});if(daily){Object.assign(current,{technicianCompletionEntryId:null,reopenedAt:'2026-10-05T14:00:00Z'});current.updates.push({id:9900,noteId:9810,body:'Follow-up reading moved.',createdByUserId:1,createdBy:'Jeffery R Grove',createdAt:'2026-10-05T14:00:00Z',canEdit:true,attachments:[],entries:[{id:303,updateId:9900,workDate:'2026-10-05',body:'Follow-up reading moved.',laborHours:0,createdAt:'2026-10-05T14:00:00Z'}]} as typeof current.updates[number]);}current.lifecycle=[...current.lifecycle,{id:98982,type:'issue_reopened',actor:'Lifecycle Admin',reason:'Follow-up reading moved.',createdAt:'2026-08-20T15:00:00Z'}];return route.fulfill({json:{ok:true,note:current}});});
  await page.route(new RegExp(`/api/${library}-library/asset-notes/9810$`),route=>{if(route.request().method()==='DELETE'){notes=notes.filter(note=>note.id!==9810);return route.fulfill({json:{ok:true,historyPreserved:true}});}return route.fallback();});
  return{asset,assetId};
}

async function getDeclaredTargetGlow(page:Page){
  return page.evaluate(()=>{
    const findRule=(rules:CSSRuleList):{animation:string}|null=>{
      for(const rule of Array.from(rules)){
        if(rule.type===CSSRule.STYLE_RULE){
          const styleRule=rule as CSSStyleRule;
          if(styleRule.selectorText.includes('.asset-note-active-issue-card.is-deep-link-target::after')&&styleRule.style.animation.includes('asset-note-target-glow-pulse'))return{animation:styleRule.style.animation};
        }
        const nestedRules=(rule as CSSMediaRule).cssRules;
        if(nestedRules){const match=findRule(nestedRules);if(match)return match;}
      }
      return null;
    };
    for(const sheet of Array.from(document.styleSheets)){try{const match=findRule(sheet.cssRules);if(match)return match;}catch{/* Cross-origin stylesheets are irrelevant to the application rule. */}}
    return null;
  });
}

function getRuntimeTargetHighlight(target:Locator,minimumOpacity:number){
  return target.evaluate((element,opacityFloor)=>{
    const card=getComputedStyle(element);const glow=getComputedStyle(element,'::after');const visibleColor=(color:string)=>color!=='transparent'&&color!=='rgba(0, 0, 0, 0)';
    return{highlighted:element.classList.contains('is-deep-link-target'),animation:glow.animationName,background:glow.backgroundImage,transform:glow.transform,outlineStyle:card.outlineStyle,outlineWidth:card.outlineWidth,outlineColorVisible:visibleColor(card.outlineColor),cardBorderStyle:card.borderTopStyle,cardBorderWidth:card.borderTopWidth,cardBorderColorVisible:visibleColor(card.borderTopColor),cardGlowPresent:card.boxShadow!=='none',glowBorderStyle:glow.borderTopStyle,glowBorderWidth:glow.borderTopWidth,glowBorderColorVisible:visibleColor(glow.borderTopColor),glowOpacityPresent:Number(glow.opacity)>=opacityFloor,glowShadowPresent:glow.boxShadow!=='none'};
  },minimumOpacity);
}

for(const library of ['machine','equipment'] as const){
  test(`${library} technician controls center icons and preserve compact focus, touch and calendar behavior`,async({page})=>{
    const{assetId}=await mockLibrary(page,library,'active',true,false,true);await page.goto(`/${library}-library?asset=${assetId}`);await page.getByRole('button',{name:/Work Orders & Notes/}).click();const issueCard=page.locator('.asset-note-active-issue-card',{hasText:`${library} active warning`});await issueCard.locator('.asset-note-issue-toggle').click();const technician=issueCard.locator('.asset-technician-card[data-technician-id="1"]');
    const centering=await technician.locator('.asset-note-issue-chevron').evaluate(circle=>{const bounds=circle.getBoundingClientRect();const svg=circle.querySelector('svg')!;const icon=svg.getBoundingClientRect();const path=svg.querySelector('path')!.getBBox();return {dx:Math.abs(bounds.x+bounds.width/2-icon.x-icon.width/2),dy:Math.abs(bounds.y+bounds.height/2-icon.y-icon.height/2),pathX:path.x+path.width/2,pathY:path.y+path.height/2};});expect(centering.dx).toBeLessThan(.6);expect(centering.dy).toBeLessThan(.6);expect(centering.pathX).toBe(12);expect(centering.pathY).toBe(12);
    await technician.locator('.asset-technician-toggle').click();const update=technician.getByRole('button',{name:'Update Entry'});const size=await update.boundingBox();expect(size!.width).toBeLessThan(120);expect(size!.height).toBeGreaterThanOrEqual(44);await page.keyboard.press('Tab');await update.focus();await expect(update).toHaveCSS('outline-style','solid');await expect(update).toHaveCSS('outline-width','2px');if(page.viewportSize()!.width>700){await update.hover();await expect(update).toHaveCSS('transform','matrix(1, 0, 0, 1, 0, -1)');}
    await update.click();const date=technician.getByLabel('Work Date',{exact:true});await date.fill('2026-10-02');const trigger=technician.getByRole('button',{name:'Open Work Date calendar'});await trigger.focus();await expect(trigger).toHaveCSS('outline-width','2px');const iconCenter=await trigger.evaluate(button=>{const b=button.getBoundingClientRect();const icon=button.querySelector('.mcc-date-icon')!;const i=icon.getBoundingClientRect();return{dx:Math.abs(b.x+b.width/2-i.x-i.width/2),dy:Math.abs(b.y+b.height/2-i.y-i.height/2),mask:getComputedStyle(icon).maskImage,height:b.height};});expect(iconCenter.dx).toBeLessThan(.6);expect(iconCenter.dy).toBeLessThan(.6);expect(iconCenter.mask).toBe('none');expect(iconCenter.height).toBeGreaterThanOrEqual(44);await expect(trigger.locator('.mcc-date-icon-day')).toHaveText('2');await expect(trigger).toHaveAttribute('title',/October 2, 2026/);
    await page.keyboard.press('Enter');const calendar=page.getByRole('dialog',{name:'Work Date calendar'});await expect(calendar).toBeVisible();await calendar.getByRole('button',{name:'Today',exact:true}).click();await expect(calendar).toHaveCount(0);await expect(date).not.toHaveValue('');await trigger.focus();await page.keyboard.press('ArrowDown');await expect(calendar).toBeVisible();await page.keyboard.press('ArrowRight');await page.keyboard.press('Enter');await expect(calendar).toHaveCount(0);await expect(trigger).toBeFocused();await page.emulateMedia({reducedMotion:'reduce'});await expect(trigger).toHaveCSS('transition-duration','0s');await technician.locator('.asset-work-log-fields').screenshot({path:`tmp/issue-166-date-polish-${library}-${page.viewportSize()!.width}.png`});await technician.getByRole('button',{name:'Cancel',exact:true}).click();await update.hover();await expect(update).toHaveCSS('transform','none');await expect(technician.locator('.asset-technician-details')).toHaveCSS('transition-duration','0s');
    await page.evaluate(()=>{document.querySelectorAll('.mcc-page-topbar,.command-launcher').forEach(element=>{(element as HTMLElement).style.visibility='hidden';});});await technician.screenshot({path:`tmp/issue-166-control-polish-${library}-${page.viewportSize()!.width}.png`});
  });
  test(`${library} technician cards group IDs, preserve threads and entry attachments, and guard single-open drafts`,async({page})=>{
    const{assetId}=await mockLibrary(page,library,'active',true,false,true,1,true);await page.goto(`/${library}-library?asset=${assetId}`);await page.getByRole('button',{name:/Work Orders & Notes/}).click();const issueCard=page.locator('.asset-note-active-issue-card',{hasText:`${library} active warning`});await issueCard.locator('.asset-note-issue-toggle').click();const cards=issueCard.locator('.asset-technician-card');await expect(cards).toHaveCount(3);await expect(issueCard.getByRole('button',{name:'+ Add Update'})).toHaveCount(0);await expect(issueCard.getByRole('button',{name:/^(Correct Entry|\+ Add Daily Entry|Edit Update)$/})).toHaveCount(0);
    const own=cards.filter({has:page.locator('[data-update-id="9905"]')});const sameName=issueCard.locator('.asset-technician-card[data-technician-id="3"]');await expect(own.locator('.asset-technician-toggle')).toContainText('Jeff Grove');await expect(own.locator('.asset-technician-toggle')).toContainText('2.00 Hrs');await expect(sameName.locator('.asset-technician-toggle')).toContainText('Jeff Grove');await expect(sameName.locator('.asset-technician-toggle')).toContainText('0.25 Hrs');await expect(own.locator('.asset-work-log-entry').first()).not.toBeVisible();await issueCard.locator('.asset-technician-grid').screenshot({path:`tmp/issue-166-collapsed-cards-${library}-${page.viewportSize()!.width}.png`});if(page.viewportSize()!.width>700)expect(await own.evaluate(element=>element.getBoundingClientRect().width)).toBeLessThanOrEqual(320);
    await own.locator('.asset-technician-toggle').click();await expect(own.locator('.asset-work-log-entry > p')).toHaveText(['Day A','Day B','Historic same-owner work.','Day C']);await expect(own.locator('.asset-note-update-meta')).toHaveCount(2);const linked=own.locator('[data-entry-id="501"]');await expect(linked.getByLabel('Attachment entry-inspection.pdf')).toBeVisible();await expect(own.getByLabel('Attachment entry-inspection.pdf')).toHaveCount(1);await expect(own.locator('[data-thread-attachments="9897"]').getByLabel('Attachment repair-result.webp')).toBeVisible();
    await sameName.locator('.asset-technician-toggle').click();await expect(own.locator('.asset-technician-toggle')).toHaveAttribute('aria-expanded','false');await expect(sameName.getByRole('button',{name:'Update Entry'})).toHaveCount(0);await sameName.locator('.asset-technician-toggle').click();await expect(sameName.locator('.asset-technician-toggle')).toHaveAttribute('aria-expanded','false');await own.locator('.asset-technician-toggle').click();await own.getByRole('button',{name:'Update Entry'}).click();await expect(own.getByLabel('Entry',{exact:true})).toHaveValue('new');await expect(own.getByLabel('Maintenance work / progress update *')).toHaveValue('');await own.getByLabel('Entry',{exact:true}).selectOption('9905:501');await expect(own.getByLabel('Maintenance work / progress update *')).toHaveValue('Historic same-owner work.');await expect(own.getByLabel('Labor Added (Hrs)')).toHaveValue('0.5');await own.getByLabel('Maintenance work / progress update *').fill('Corrected historic entry only.');await own.locator('.asset-note-update-form input[type=file]').setInputFiles({name:'entry-added-photo.png',mimeType:'image/png',buffer:Buffer.from('photo')});
    page.once('dialog',dialog=>dialog.dismiss());await own.locator('.asset-technician-toggle').click();await expect(own.locator('.asset-technician-toggle')).toHaveAttribute('aria-expanded','true');page.once('dialog',dialog=>dialog.dismiss());await sameName.locator('.asset-technician-toggle').click();await expect(own.getByLabel('Maintenance work / progress update *')).toHaveValue('Corrected historic entry only.');await expect(own.getByText('entry-added-photo.png',{exact:true})).toBeVisible();await own.getByRole('button',{name:'Save Update',exact:true}).click();await expect(linked.locator('p')).toHaveText('Corrected historic entry only.');await expect(linked.getByLabel('Attachment entry-added-photo.png')).toBeVisible();await expect(own.locator('[data-entry-id="111"] > p')).toHaveText('Day A');await expect(own.locator('[data-entry-id="113"] > p')).toHaveText('Day C');
    await page.emulateMedia({reducedMotion:'reduce'});await expect(own.locator('.asset-technician-details')).toHaveCSS('transition-duration','0s');await page.setViewportSize({width:820,height:1180});expect(await page.evaluate(()=>document.documentElement.scrollWidth-document.documentElement.clientWidth)).toBeLessThanOrEqual(1);await page.setViewportSize({width:390,height:844});expect(await own.getByRole('button',{name:'Update Entry'}).evaluate(button=>button.getBoundingClientRect().height)).toBeGreaterThanOrEqual(44);expect(await page.evaluate(()=>document.documentElement.scrollWidth-document.documentElement.clientWidth)).toBeLessThanOrEqual(1);
    await page.evaluate(()=>{document.querySelectorAll('.mcc-page-topbar,.command-launcher').forEach(element=>{(element as HTMLElement).style.visibility='hidden';});});await issueCard.locator('.asset-note-update-section').screenshot({path:`tmp/issue-166-technician-cards-${library}-${page.viewportSize()!.width}.png`});
  });
  test(`${library} daily work logs append and correct one entry, roll up labor, and remain compact`,async({page})=>{
    const{assetId}=await mockLibrary(page,library,'active',true,false,true);await page.goto(`/${library}-library?asset=${assetId}`);await page.getByRole('button',{name:/Work Orders & Notes/}).click();
    const card=page.locator('.asset-note-active-issue-card',{hasText:`${library} active warning`});await card.locator('.asset-note-issue-toggle').click();
    const own=card.locator('.asset-technician-card[data-technician-id="1"]');const other=card.locator('.asset-technician-card[data-technician-id="2"]');
    await own.locator('.asset-technician-toggle').click();await expect(own.locator('.asset-work-log-entry > p')).toHaveText(['Day A','Day B','Day C']);await expect(own.getByText('Technician labor: 1.50 Hrs')).toBeVisible();await expect(card.getByText('2.25 total hours')).toBeVisible();await expect(other.getByRole('button',{name:'Update Entry'})).toHaveCount(0);
    await own.getByRole('button',{name:'Update Entry'}).click();await expect(own.getByLabel('Entry',{exact:true})).toHaveValue('new');const form=own.locator('.asset-note-update-form');await expect(form.getByLabel('Maintenance work / progress update *')).toHaveValue('');await form.getByLabel('Work Date',{exact:true}).fill('2026-10-04');await form.getByLabel('Labor Added (Hrs)').fill('0.25');await form.getByLabel('Maintenance work / progress update *').fill('Day D');await form.getByRole('button',{name:'Save Entry',exact:true}).click();
    await expect(own.locator('.asset-work-log-entry > p')).toHaveText(['Day A','Day B','Day C','Day D']);await expect(card.getByText('2.50 total hours')).toBeVisible();
    await own.getByRole('button',{name:'Update Entry'}).click();await own.getByLabel('Entry',{exact:true}).selectOption('9897:112');await own.getByLabel('Labor Added (Hrs)').fill('0.50');await own.getByLabel('Maintenance work / progress update *').fill('Day B corrected');await own.getByRole('button',{name:'Save Update',exact:true}).click();await expect(own.locator('.asset-work-log-entry > p')).toHaveText(['Day A','Day B corrected','Day C','Day D']);await expect(card.getByText('2.25 total hours')).toBeVisible();
    const labor=card.locator('.asset-note-labor-section');await expect(labor).toContainText('Jeffery R Grove');await expect(labor).toContainText('/ 1.50 Hrs');await expect(labor).toContainText('Alex Smith');
    if(page.viewportSize()!.width>700){const width=await labor.evaluate(element=>element.getBoundingClientRect().width);expect(width).toBeLessThanOrEqual(440);}
    await page.evaluate(()=>{document.querySelectorAll('.mcc-page-topbar,.command-launcher').forEach(element=>{(element as HTMLElement).style.visibility='hidden';});});await card.locator('.asset-note-update-section').screenshot({path:`tmp/issue-166-daily-${library}-${page.viewportSize()!.width}.png`});await labor.screenshot({path:`tmp/issue-166-labor-${library}-${page.viewportSize()!.width}.png`});
    await page.setViewportSize({width:820,height:1180});expect(await page.evaluate(()=>document.documentElement.scrollWidth-document.documentElement.clientWidth)).toBeLessThanOrEqual(1);await page.setViewportSize({width:390,height:844});expect(await page.evaluate(()=>document.documentElement.scrollWidth-document.documentElement.clientWidth)).toBeLessThanOrEqual(1);expect(await own.getByRole('button',{name:'Update Entry'}).evaluate(element=>element.getBoundingClientRect().height)).toBeGreaterThanOrEqual(44);
  });
  test(`${library} daily work draft protects labor, date, attachments and accordion switches`,async({page})=>{
    const{assetId}=await mockLibrary(page,library,'active',true,false,true);await page.goto(`/${library}-library?asset=${assetId}`);const toggle=page.getByRole('button',{name:/Work Orders & Notes/});await toggle.click();const card=page.locator('.asset-note-active-issue-card',{hasText:`${library} active warning`});await card.locator('.asset-note-issue-toggle').click();await card.locator('.asset-technician-card[data-technician-id="1"] .asset-technician-toggle').click();await card.getByRole('button',{name:'Update Entry'}).click();const labor=card.getByLabel('Labor Added (Hrs)');await labor.fill('0.75');
    const second=page.locator('.asset-note-active-issue-card',{hasText:`${library} second active warning`}).locator('.asset-note-issue-toggle');page.once('dialog',dialog=>dialog.dismiss());await second.click();await expect(labor).toHaveValue('0.75');
    page.once('dialog',dialog=>dialog.dismiss());await page.getByRole('button',{name:/Preventive Maintenance Tracking/}).click();await expect(toggle).toHaveAttribute('aria-expanded','true');await expect(labor).toHaveValue('0.75');
    await card.getByLabel('Work Date',{exact:true}).fill('2026-10-02');await card.getByLabel('Maintenance work / progress update *').fill('Draft work');await card.locator('.asset-note-update-form input[type=file]').setInputFiles({name:'draft.pdf',mimeType:'application/pdf',buffer:Buffer.from('%PDF-1.4\nDraft\n%%EOF')});page.once('dialog',dialog=>dialog.dismiss());await card.getByRole('button',{name:'Issue is Resolved'}).click();await expect(card.getByLabel('Maintenance work / progress update *')).toHaveValue('Draft work');await expect(card.getByText('draft.pdf',{exact:true})).toBeVisible();
  });
  test(`${library} resolution marks one final daily entry, animates once, and clears on reopen`,async({page})=>{
    await page.clock.install({time:new Date('2026-10-04T14:00:00Z')});const{assetId}=await mockLibrary(page,library,'active',true,false,true);await page.goto(`/${library}-library?asset=${assetId}`);await page.getByRole('button',{name:/Work Orders & Notes/}).click();let card=page.locator('.asset-note-active-issue-card',{hasText:`${library} active warning`});await card.locator('.asset-note-issue-toggle').click();await expect(card.locator('.asset-work-log-completion')).toHaveCount(0);
    await card.getByRole('button',{name:'Issue is Resolved'}).click();await card.getByLabel('Resolution Summary *').fill('Repair verified under production load.');await card.getByRole('button',{name:'Confirm Resolution'}).click();await page.getByRole('alertdialog').getByRole('button',{name:'No',exact:true}).click();
    await page.clock.pauseAt(new Date('2026-10-04T14:01:00Z'));await page.getByRole('button',{name:/Open Resolved History/}).click();let history=page.getByRole('dialog',{name:/Resolved History for/});await history.getByRole('button',{name:/2026.*resolved issue/}).click();card=history.locator('.asset-note-entry',{hasText:`${library} active warning`});await card.locator('.asset-technician-card[data-technician-id="2"] .asset-technician-toggle').click();const completion=card.locator('.asset-work-log-completion');await expect(completion).toHaveCount(1);await expect(card.locator('[data-entry-id="201"] .asset-work-log-completion')).toBeVisible();await expect(completion).toHaveCSS('color','rgb(84, 223, 162)');await expect(completion).toHaveClass(/is-completing/);await expect(completion).toHaveCSS('animation-duration','0.4s');await page.emulateMedia({reducedMotion:'reduce'});await expect(completion).toHaveCSS('animation-name','none');await page.clock.fastForward(401);await expect(completion).not.toHaveClass(/is-completing/);
    await history.getByRole('button',{name:'Close',exact:true}).click();await page.getByRole('button',{name:/Open Resolved History/}).click();history=page.getByRole('dialog',{name:/Resolved History for/});card=history.locator('.asset-note-entry',{hasText:`${library} active warning`});await expect(card.locator('.asset-work-log-completion')).not.toHaveClass(/is-completing/);
    await card.getByRole('button',{name:'Reopen Issue',exact:true}).click();await card.getByLabel('Reopen Reason *').fill('Follow-up reading moved.');await card.getByRole('button',{name:'Reopen Issue',exact:true}).last().click();await history.getByRole('button',{name:'Close',exact:true}).click();const active=page.locator('.asset-note-active-issue-card',{hasText:`${library} active warning`});await active.locator('.asset-note-issue-toggle').click();await expect(active.locator('.asset-work-log-completion')).toHaveCount(0);
    await active.locator('.asset-technician-card[data-technician-id="1"] .asset-technician-toggle').click();await active.getByRole('button',{name:'Update Entry'}).click();await active.getByLabel('Work Date',{exact:true}).fill('2026-10-06');await active.getByLabel('Maintenance work / progress update *').fill('Bearing replaced and vibration tested under load.');await active.getByRole('button',{name:'Save Entry',exact:true}).click();await expect(active.getByRole('button',{name:'Update Added',exact:true})).toBeVisible();await page.clock.fastForward(1500);await expect(active.locator('[data-entry-id="401"]')).toBeVisible();await active.getByRole('button',{name:'Issue is Resolved'}).click();await active.getByLabel('Resolution Summary *').fill('Repair verified under production load.');await active.getByRole('button',{name:'Confirm Resolution'}).click();await page.getByRole('alertdialog').getByRole('button',{name:'No',exact:true}).click();await page.getByRole('button',{name:/Open Resolved History/}).click();const final=page.getByRole('dialog',{name:/Resolved History for/}).locator('.asset-note-entry',{hasText:`${library} active warning`});await expect(final.locator('.asset-work-log-completion')).toHaveCount(1);await final.locator('.asset-technician-card[data-technician-id="1"] .asset-technician-toggle').click();await expect(final.locator('[data-entry-id="401"] .asset-work-log-completion')).toBeVisible();

  });
  test(`${library} resolved correction supports editing, attachments, and live locking without reload`,async({page})=>{
    await page.clock.install();
    // The browser wall clock deliberately differs from the server clock.
    await page.clock.setSystemTime(new Date('2040-01-01T00:00:00Z'));
    const{assetId}=await mockLibrary(page,library,'resolved',true,true);
    await page.goto(`/${library}-library?asset=${assetId}`);await page.getByRole('button',{name:/Work Orders & Notes/}).click();
    await page.getByRole('button',{name:/Open Resolved History/}).click();const history=page.getByRole('dialog',{name:/Resolved History for/});await history.getByRole('button',{name:/2026.*resolved issue/}).click();
    const card=history.locator('.asset-note-entry',{hasText:`${library} active warning`});
    await expect(card.getByRole('button',{name:'+ Add Update'})).toHaveCount(0);await card.locator('.asset-technician-toggle').first().click();await expect(card.getByRole('button',{name:'Update Entry'})).toBeVisible();
    const body=card.locator('.asset-work-log-entry > p').first();await expect(body).toHaveCSS('color','rgb(255, 196, 102)');await expect(card.locator('.asset-note-update-section')).toHaveCSS('border-color','rgba(210, 235, 255, 0.2)');
    const created=await card.locator('.asset-note-update-meta time').first().textContent();await card.getByRole('button',{name:'Update Entry'}).click();await card.getByLabel('Entry',{exact:true}).selectOption('9897:0');await card.getByLabel('Maintenance work / progress update *').fill('Corrected inspection and final reading.');
    await expect(card.getByRole('button',{name:'Add Attachments / Add Photos'})).toBeVisible();await card.locator('.asset-note-update-form input[type=file]').setInputFiles({name:'later-photo.png',mimeType:'image/png',buffer:Buffer.from('iVBORw0KGgoAAAANSUhEUgAAAAEAAAABCAQAAAC1HAwCAAAAC0lEQVR42mNk+A8AAQUBAScY42YAAAAASUVORK5CYII=','base64')});await card.getByRole('button',{name:'Save Update',exact:true}).click();await expect(body).toHaveText('Corrected inspection and final reading.');
    await expect(card.locator('.asset-note-update-edited')).toHaveCount(0);await expect(card.locator('.asset-note-update-meta time').first()).toHaveText(created!);
    await expect(card.getByLabel('Attachment later-photo.png')).toBeVisible();
    await card.getByRole('button',{name:'Update Entry'}).click();await card.getByLabel('Maintenance work / progress update *').fill('Bearing replaced and vibration tested under load.');await card.getByRole('button',{name:'Save Entry',exact:true}).click();await expect(card.getByRole('button',{name:'Update Added',exact:true})).toBeVisible();await page.clock.fastForward(1000);await expect(card.locator('.asset-work-log-entry > p').last()).toHaveText('Bearing replaced and vibration tested under load.');await card.getByRole('button',{name:'Update Entry'}).click();
    await page.clock.fastForward(300001);
    await expect(card.getByRole('button',{name:'Update Entry'})).toHaveCount(0);await expect(card.getByRole('button',{name:'+ Add Update'})).toHaveCount(0);await expect(card.locator('.asset-note-update-form')).toHaveCount(0);
    await expect(body).toHaveText('Corrected inspection and final reading.');await expect(card.getByLabel('Attachment later-photo.png').getByRole('button',{name:'Download'})).toBeVisible();await expect(card.getByRole('button',{name:'Reopen Issue'})).toBeVisible();
    expect(await page.evaluate(()=>document.documentElement.scrollWidth-document.documentElement.clientWidth)).toBeLessThanOrEqual(1);
  });
  test(`${library} hides Update Entry when the actor lacks permission or the issue is resolved`,async({page})=>{
    const{assetId}=await mockLibrary(page,library,'active',false);await page.goto(`/${library}-library?asset=${assetId}`);await page.getByRole('button',{name:/Work Orders & Notes/}).click();const card=page.locator('.asset-note-active-issue-card',{hasText:`${library} active warning`});await card.locator('.asset-note-issue-toggle').click();await card.locator('.asset-technician-toggle').first().click();await expect(card.getByRole('button',{name:'Update Entry'})).toHaveCount(0);
    await mockLibrary(page,library,'resolved');await page.reload();await page.getByRole('button',{name:/Work Orders & Notes/}).click();await page.getByRole('button',{name:/Open Resolved History/}).click();const history=page.getByRole('dialog',{name:/Resolved History for/});await history.getByRole('button',{name:/2026.*resolved issue/}).click();await history.locator('.asset-technician-toggle').first().click();await expect(history.getByRole('button',{name:'Update Entry'})).toHaveCount(0);
  });
  test(`${library} edits an existing update and protects unsaved accordion work`,async({page})=>{
    const{assetId}=await mockLibrary(page,library);await page.goto(`/${library}-library?asset=${assetId}`);
    const notesToggle=page.getByRole('button',{name:/Work Orders & Notes/});await notesToggle.click();
    await page.getByRole('button',{name:/Preventive Maintenance Tracking/}).click();await expect(notesToggle).toHaveAttribute('aria-expanded','false');
    await notesToggle.click();await expect(page.getByRole('button',{name:/Preventive Maintenance Tracking/})).toHaveAttribute('aria-expanded','false');
    const card=page.locator('.asset-note-active-issue-card',{hasText:`${library} active warning`});const warningBadge=card.locator('.asset-note-issue-toggle .asset-note-warning-badge');await expect(warningBadge).toHaveCSS('border-color','rgba(255, 196, 102, 0.76)');await expect(warningBadge).toHaveCSS('background-color','rgba(255, 196, 102, 0.19)');await card.locator('.asset-note-issue-toggle').click();
    const technician=card.locator('.asset-technician-card').first();await technician.locator('.asset-technician-toggle').click();const editButton=technician.getByRole('button',{name:'Update Entry'});await expect(editButton).toBeVisible();const layout=await editButton.evaluate(button=>({buttonWidth:button.getBoundingClientRect().width,cardWidth:button.closest('.asset-technician-card')!.getBoundingClientRect().width,height:button.getBoundingClientRect().height,overflow:document.documentElement.scrollWidth-document.documentElement.clientWidth}));expect(layout.buttonWidth).toBeLessThan(layout.cardWidth*.6);expect(layout.overflow).toBeLessThanOrEqual(1);expect(layout.height).toBeGreaterThanOrEqual(44);expect(layout.height).toBeLessThanOrEqual(48);
    await editButton.click();await card.getByLabel('Entry',{exact:true}).selectOption('9897:0');const editor=card.getByLabel('Maintenance work / progress update *');await expect(editor).toHaveValue('Initial inspection photographed before repair.');
    await editor.fill('Unsaved correction');await card.locator('.asset-note-update-attachment-row input[type=file]').setInputFiles({name:'pending.pdf',mimeType:'application/pdf',buffer:Buffer.from('%PDF-1.4\npending\n%%EOF')});await expect(card).toContainText('pending.pdf');
    page.once('dialog',dialog=>dialog.dismiss());await page.locator('.asset-note-active-issue-card',{hasText:`${library} second active warning`}).locator('.asset-note-issue-toggle').click();await expect(editor).toHaveValue('Unsaved correction');
    page.once('dialog',dialog=>dialog.dismiss());await page.getByRole('button',{name:/Asset Document Library/}).click();await expect(notesToggle).toHaveAttribute('aria-expanded','true');await expect(card).toContainText('pending.pdf');
    await card.getByRole('button',{name:'Cancel'}).click();await card.getByRole('button',{name:'Update Entry'}).click();await card.getByLabel('Entry',{exact:true}).selectOption('9897:0');await card.getByLabel('Maintenance work / progress update *').fill('Corrected inspection and final reading.');
    await card.getByRole('button',{name:'Save Update'}).click();await expect(card.locator('.asset-note-update-edited')).toHaveCount(0);await expect(card).toContainText('Corrected inspection and final reading.');await expect(card.getByLabel('Attachment repair-result.webp')).toBeVisible();
    await expect(card.getByLabel('Attachment later-photo.png')).toBeVisible();await expect(card.locator('.asset-technician-card')).toHaveCount(1);
    await card.getByRole('button',{name:'Update Entry'}).click();await card.getByLabel('Maintenance work / progress update *').fill('Unsaved new progress');page.once('dialog',dialog=>dialog.dismiss());await page.locator('.asset-note-active-issue-card',{hasText:`${library} second active warning`}).locator('.asset-note-issue-toggle').click();await expect(card.getByLabel('Maintenance work / progress update *')).toHaveValue('Unsaved new progress');
    expect(await page.evaluate(()=>document.documentElement.scrollWidth-document.documentElement.clientWidth)).toBeLessThanOrEqual(1);
  });
  test(`${library} warning issue deep link opens, reveals, and focuses the target note`,async({page})=>{
    await page.emulateMedia({reducedMotion:'no-preference'});
    const{assetId}=await mockLibrary(page,library);await page.goto(`/${library}-library?asset=${assetId}&note=9810`);
    let target=page.locator(`#asset-note-${assetId}-9810`);await expect.poll(()=>getRuntimeTargetHighlight(target,.4),{message:`${library} target should expose its normal-motion highlight while the deep-link class is active`}).toMatchObject({highlighted:true,background:'none',transform:'none',outlineStyle:'solid',outlineWidth:'1px',outlineColorVisible:true,cardBorderStyle:'solid',cardBorderWidth:'1px',cardBorderColorVisible:true,cardGlowPresent:true,glowBorderStyle:'solid',glowBorderWidth:'1px',glowBorderColorVisible:true,glowOpacityPresent:true,glowShadowPresent:true});
    const declaredGlow=await getDeclaredTargetGlow(page);expect(declaredGlow).not.toBeNull();expect(declaredGlow!.animation).toContain('asset-note-target-glow-pulse');expect(declaredGlow!.animation).toMatch(/(?:^|\s)0?\.72s(?:\s|$)/);expect(declaredGlow!.animation).toMatch(/(?:^|\s)2(?:\s|$)/);
    const notesToggle=page.getByRole('button',{name:/Work Orders & Notes/});await expect(notesToggle).toHaveAttribute('aria-expanded','true');let issueToggle=target.locator('.asset-note-issue-toggle');await expect(issueToggle).toHaveAttribute('aria-expanded','true');await expect(page.locator(`#asset-note-${assetId}-9814 .asset-note-issue-toggle`)).toHaveAttribute('aria-expanded','false');await expect(page.locator('.asset-note-issue-toggle[aria-expanded="true"]')).toHaveCount(1);await expect(issueToggle).toBeFocused();await expect(target.locator('.asset-note-body-preview')).toHaveText('Original bearing vibration problem statement.');await expect(target).toBeInViewport({ratio:.01});

    await page.emulateMedia({reducedMotion:'reduce'});await page.reload();target=page.locator(`#asset-note-${assetId}-9810`);await expect.poll(()=>getRuntimeTargetHighlight(target,.6),{message:`${library} target should expose its reduced-motion static highlight while the deep-link class is active`}).toMatchObject({highlighted:true,animation:'none',background:'none',transform:'none',outlineStyle:'solid',outlineWidth:'2px',outlineColorVisible:true,cardBorderStyle:'solid',cardBorderWidth:'1px',cardBorderColorVisible:true,cardGlowPresent:true,glowBorderStyle:'solid',glowBorderWidth:'1px',glowBorderColorVisible:true,glowOpacityPresent:true,glowShadowPresent:true});issueToggle=target.locator('.asset-note-issue-toggle');await expect(issueToggle).toBeFocused();
    await page.goto(`/${library}-library?asset=${assetId}&note=9811`);const historyDialog=page.getByRole('dialog',{name:`Resolved History for ${library==='machine'?'PRESS-98':'EQ-98'}`});await expect(historyDialog).toBeVisible();const resolvedYear=historyDialog.getByRole('button',{name:/2026.*resolved issue/});await expect(resolvedYear).toHaveAttribute('aria-expanded','true');await expect(resolvedYear).toHaveCSS('animation-name','none');target=historyDialog.locator(`#asset-note-${assetId}-9811`);await expect(target).toHaveClass(/is-deep-link-target/);await expect(target.getByRole('button',{name:/More actions for/})).toBeFocused();
  });

  test(`${library} image viewer provides complete bounded zoom and pan coverage`,async({page})=>{
    await page.emulateMedia({reducedMotion:'no-preference'});
    const{assetId}=await mockLibrary(page,library);await page.goto(`/${library}-library?asset=${assetId}`);await page.getByRole('button',{name:/Work Orders & Notes/}).click();
    const activeCard=page.locator('.asset-note-active-issue-card',{hasText:`${library} active warning`});await activeCard.locator('.asset-note-issue-toggle').click();const notePhoto=activeCard.locator('.asset-attachment-chip',{hasText:'bearing-photo.png'});await expect(notePhoto.locator('img.asset-attachment-thumbnail')).toHaveAttribute('src',new RegExp(`/api/${library}-library/asset-note-attachments/9901/content$`));await expect(notePhoto.locator('img.asset-attachment-thumbnail')).toHaveAttribute('loading','lazy');const pdfChip=activeCard.locator('.asset-attachment-chip',{hasText:'inspection-report.pdf'});await expect(pdfChip.locator('[data-file-type=pdf] .mcc-file-type-icon__pdf-ribbon')).toBeVisible();await expect(notePhoto.getByRole('button',{name:'Preview'})).toBeVisible();await expect(notePhoto.getByRole('button',{name:'Download'})).toBeVisible();await expect(notePhoto.getByRole('button',{name:'Remove'})).toBeVisible();const [cardBox,chipBox]=await Promise.all([activeCard.boundingBox(),notePhoto.boundingBox()]);expect(cardBox).not.toBeNull();expect(chipBox).not.toBeNull();if(page.viewportSize()!.width>700)expect(chipBox!.width).toBeLessThan(cardBox!.width*.7);else expect(chipBox!.width).toBeLessThanOrEqual(cardBox!.width);await expect(activeCard.locator('img.asset-attachment-thumbnail')).toHaveCount(2);
    await notePhoto.getByRole('button',{name:'Preview'}).click();const imageViewer=page.getByRole('dialog',{name:'bearing-photo.png viewer'});const imageCanvas=imageViewer.getByRole('region',{name:/Image preview/});const zoomOutput=imageViewer.locator('output');await expect(imageViewer.locator('img')).toHaveAttribute('src',new RegExp('/asset-note-attachments/9901/content$'));await expect(zoomOutput).toHaveText('100%');await expect(imageViewer.getByRole('button',{name:'Zoom out'})).toBeDisabled();const wheelCancelled=await imageCanvas.evaluate(element=>!element.dispatchEvent(new WheelEvent('wheel',{deltaY:120,bubbles:true,cancelable:true})));expect(wheelCancelled).toBe(true);await expect(zoomOutput).toHaveText('100%');await imageCanvas.evaluate(element=>{for(let index=0;index<45;index+=1)element.dispatchEvent(new WheelEvent('wheel',{deltaY:-120,bubbles:true,cancelable:true}));});await expect(zoomOutput).toHaveText('1000%');await expect(imageViewer.getByRole('button',{name:'Zoom in'})).toBeDisabled();
    const beforePan=await imageViewer.locator('img').evaluate(element=>getComputedStyle(element).transform);const canvasBox=await imageCanvas.boundingBox();expect(canvasBox).not.toBeNull();await page.mouse.move(canvasBox!.x+canvasBox!.width/2,canvasBox!.y+canvasBox!.height/2);await page.mouse.down();await page.mouse.move(canvasBox!.x+canvasBox!.width*.7,canvasBox!.y+canvasBox!.height*.7,{steps:4});await page.mouse.up();const afterPan=await imageViewer.locator('img').evaluate(element=>getComputedStyle(element).transform);expect(afterPan).not.toBe(beforePan);expect(await imageViewer.locator('img').evaluate((image,canvas)=>{const imageRect=image.getBoundingClientRect();const canvasRect=(canvas as Element).getBoundingClientRect();return imageRect.right>=canvasRect.left&&imageRect.left<=canvasRect.right&&imageRect.bottom>=canvasRect.top&&imageRect.top<=canvasRect.bottom;},await imageCanvas.elementHandle())).toBe(true);
    await imageViewer.getByRole('button',{name:'Reset / 100%'}).click();await expect(zoomOutput).toHaveText('100%');await expect(imageViewer.locator('img')).toHaveCSS('transform','matrix(1, 0, 0, 1, 0, 0)');await imageViewer.getByRole('button',{name:'Zoom in'}).focus();await page.keyboard.press('Enter');await expect(zoomOutput).toHaveText('125%');await imageCanvas.focus();await page.keyboard.press('0');await expect(zoomOutput).toHaveText('100%');await page.emulateMedia({reducedMotion:'reduce'});await expect(imageViewer.locator('img')).toHaveCSS('transition-duration','0s');await page.keyboard.press('Escape');await expect(imageViewer).toHaveCount(0);
    await page.emulateMedia({reducedMotion:'no-preference'});await activeCard.locator('.asset-technician-toggle').first().click();const updatePhoto=activeCard.locator('.asset-attachment-chip',{hasText:'repair-result.webp'});await updatePhoto.getByRole('button',{name:'Preview'}).click();const updateViewer=page.getByRole('dialog',{name:'repair-result.webp viewer'});await expect(updateViewer.locator('output')).toHaveText('100%');await expect(updateViewer.getByRole('group',{name:'Image zoom controls'})).toBeVisible();await updateViewer.getByRole('button',{name:'Close'}).first().click();await expect(updateViewer).toHaveCount(0);
  });

  test(`${library} warning issue active lifecycle supports accordion, update, resolve, and history folders`,async({page})=>{
    await page.emulateMedia({reducedMotion:'no-preference'});
    const{asset,assetId}=await mockLibrary(page,library,'active',true,false,false,3);await page.goto(`/${library}-library?asset=${assetId}`);await page.getByRole('button',{name:/Work Orders & Notes/}).click();
    const activeCard=page.locator('.asset-note-active-issue-card',{hasText:`${library} active warning`});const activeToggle=activeCard.locator('.asset-note-issue-toggle');const secondCard=page.locator('.asset-note-active-issue-card',{hasText:`${library} second active warning`});const secondToggle=secondCard.locator('.asset-note-issue-toggle');await expect(activeCard).toContainText(`WO-${library.toUpperCase()}-98`);const datePill=activeToggle.locator('.asset-note-date-pill');await expect(datePill).toBeVisible();await expect(datePill).toHaveCSS('color','rgb(255, 255, 255)');await expect(activeToggle).toHaveAttribute('aria-expanded','false');await expect(activeCard.getByRole('button',{name:'+ Add Update'})).toHaveCount(0);await activeToggle.focus();await page.keyboard.press('Enter');await expect(activeToggle).toHaveAttribute('aria-expanded','true');const createdMeta=activeCard.locator('.asset-note-created-meta');await expect(createdMeta).toContainText(/Created by Issue Creator.*record updated/);expect(Number.parseFloat(await createdMeta.evaluate(element=>getComputedStyle(element).fontSize))).toBeGreaterThanOrEqual(12);await secondToggle.click();await expect(secondToggle).toHaveAttribute('aria-expanded','true');await expect(activeToggle).toHaveAttribute('aria-expanded','false');await expect(page.locator('.asset-note-issue-toggle[aria-expanded="true"]')).toHaveCount(1);await activeToggle.click();await expect(activeToggle).toHaveAttribute('aria-expanded','true');await expect(secondToggle).toHaveAttribute('aria-expanded','false');await expect(page.locator('.asset-note-issue-toggle[aria-expanded="true"]')).toHaveCount(1);await expect(activeCard.locator('.asset-note-body-preview')).toHaveText('Original bearing vibration problem statement.');await expect(activeCard.getByRole('button',{name:'+ Add Update'})).toBeVisible();
    await activeCard.getByRole('button',{name:'+ Add Update'}).click();const updateField=activeCard.getByLabel('Maintenance work / progress update *');await expect(updateField).toBeFocused();await updateField.fill('Bearing replaced and vibration tested under load.');await activeCard.getByRole('button',{name:'Add Update',exact:true}).click();await expect(activeCard).toContainText('Bearing replaced and vibration tested under load.');await expect(activeCard).toContainText('Lifecycle Admin');await expect(activeCard.getByRole('button',{name:'+ Add Update'})).toHaveCount(0);const joined=activeCard.locator('.asset-technician-card[data-technician-id="3"]');await joined.locator('.asset-technician-toggle').click();await expect(joined.getByRole('button',{name:'Update Entry'})).toBeVisible();await expect(activeCard.locator('.asset-technician-card[data-technician-id="1"]').getByRole('button',{name:'Update Entry'})).toHaveCount(0);await expect(activeCard.locator('.asset-note-body-preview')).toHaveText('Original bearing vibration problem statement.');
    await activeCard.getByRole('button',{name:'Issue is Resolved'}).click();await expect(activeCard.getByRole('checkbox',{name:/Issue is Resolved/})).toBeChecked();await activeCard.getByLabel('Resolution Summary *').fill('Repair verified under production load.');await activeCard.getByRole('button',{name:'Confirm Resolution'}).click();await expect(page.locator('.asset-notes-panel .form-message[role=status]')).toContainText('removed from Dashboard attention');const pdfPrompt=page.getByRole('alertdialog',{name:/Print \/ save the Maintenance Record PDF now/});await expect(pdfPrompt).toBeVisible();await pdfPrompt.getByRole('button',{name:'No',exact:true}).click();await expect(pdfPrompt).toHaveCount(0);
    await expect(page.locator('.asset-note-resolved-history')).toHaveCount(0);await expect(page.getByText('Maintenance Archive')).toHaveCount(0);const historyControl=page.getByRole('button',{name:/Open Resolved History, 3 resolved issues/});await expect(historyControl).toBeVisible();await historyControl.click();let history=page.getByRole('dialog',{name:`Resolved History for ${asset.assetNumber}`});await expect(history).toBeVisible();await expect(history.getByRole('button',{name:'Close'})).toBeFocused();const year2026=history.getByRole('button',{name:/2026.*resolved issue/});const yearFolderIcon=year2026.locator('[data-file-type="folder"]');await expect(year2026).toHaveAttribute('aria-expanded','false');await expect(yearFolderIcon).toHaveAttribute('data-state','closed');await year2026.click();await expect(year2026).toHaveAttribute('aria-expanded','true');expect(await year2026.evaluate(element=>{const style=getComputedStyle(element);return{name:style.animationName,duration:style.animationDuration,count:style.animationIterationCount};})).toEqual({name:'asset-note-folder-glow-pulse',duration:'0.72s',count:'2'});await expect(yearFolderIcon).toHaveAttribute('data-state','open');await expect(history.getByText(`${library} active warning`)).toBeVisible();
    const year2025=history.getByRole('button',{name:/2025.*resolved issue/});await year2025.click();await expect(history.getByText(`${library} resolved 2025`)).toBeVisible();await page.keyboard.press('Escape');await expect(history).toHaveCount(0);await expect(historyControl).toBeFocused();
  });

  test(`${library} warning issue resolved lifecycle supports filtering, reopen, and audited delete`,async({page})=>{
    const{asset,assetId}=await mockLibrary(page,library,'resolved');await page.goto(`/${library}-library?asset=${assetId}`);await page.getByRole('button',{name:/Work Orders & Notes/}).click();
    await page.getByLabel('Search Asset Notes').fill(`WO-${library.toUpperCase()}-98`);await page.getByLabel('Note status').selectOption('resolved');const history=page.getByRole('dialog',{name:`Resolved History for ${asset.assetNumber}`});await expect(history).toBeVisible();await expect(history.getByText(`${library} resolved 2026`)).toHaveCount(0);const filteredYear=history.getByRole('button',{name:/2026.*1 resolved issue/});if(await filteredYear.getAttribute('aria-expanded')!=='true')await filteredYear.click();const resolvedCard=history.locator('.asset-note-entry',{hasText:`${library} active warning`});await expect(resolvedCard).toContainText(asset.assetNumber);await expect(resolvedCard).toContainText('Repair verified under production load.');await expectPillAction(resolvedCard.getByRole('button',{name:'Reopen Issue'}));await resolvedCard.getByRole('button',{name:'Reopen Issue'}).click();await resolvedCard.getByLabel('Reopen Reason *').fill('Follow-up reading moved.');await resolvedCard.getByRole('button',{name:'Reopen Issue'}).last().click();await expect(page.locator('.asset-notes-panel .form-message[role=status]')).toContainText('restored to Dashboard attention');await page.keyboard.press('Escape');await expect(history).toHaveCount(0);
    await page.getByLabel('Search Asset Notes').fill('');await page.getByLabel('Note status').selectOption('all');const reopenedCard=page.locator('.asset-note-active-issue-card',{hasText:`${library} active warning`});const reopenedToggle=reopenedCard.locator('.asset-note-issue-toggle');await expect(reopenedToggle).toHaveAttribute('aria-expanded','false');await reopenedToggle.focus();await page.keyboard.press('Space');await expect(reopenedToggle).toHaveAttribute('aria-expanded','true');await expect(reopenedCard.getByRole('button',{name:'+ Add Update'})).toHaveCount(0);
    await reopenedCard.getByRole('button',{name:`More actions for ${library} active warning`}).click();await page.getByRole('menuitem',{name:'Delete Note'}).click();await expect(reopenedCard.getByLabel('Delete Reason *')).toBeVisible();await reopenedCard.getByLabel('Delete Reason *').fill('Duplicate issue retired after review.');page.once('dialog',dialog=>dialog.accept());await reopenedCard.getByRole('button',{name:'Delete Warning Issue'}).click();await expect(page.locator('.asset-notes-panel .form-message[role=status]')).toContainText('audit evidence preserved');await expect(page.getByText(`${library} active warning`)).toHaveCount(0);
    const overflow=await page.evaluate(()=>document.documentElement.scrollWidth-document.documentElement.clientWidth);expect(overflow).toBeLessThanOrEqual(1);
  });
}

for(const library of ['machine','equipment'] as const){
  test(`${library} Update Entry glow and focus fit inside accordion clipping bounds`,async({page},testInfo)=>{
    const {assetId}=await mockLibrary(page,library,'active',true);
    await page.goto(`/${library}-library?asset=${assetId}`);
    await page.getByRole('button',{name:/Work Orders & Notes/}).click();
    const card=page.locator('.asset-note-active-issue-card',{hasText:`${library} active warning`});
    await card.locator('.asset-note-issue-toggle').click();
    const technician=card.locator('.asset-technician-card').first();
    const toggle=technician.locator('.asset-technician-toggle');
    await toggle.click();
    const button=technician.getByRole('button',{name:'Update Entry'});
    await expectPillAction(button);await expectPillAction(card.getByRole('button',{name:'Issue is Resolved',exact:true}));
    const chevron=toggle.locator('.asset-note-issue-chevron');await expect(chevron).toHaveCSS('border-top-left-radius','50%');
    const chevronSize=await chevron.boundingBox();expect(Math.abs(chevronSize!.width-chevronSize!.height)).toBeLessThanOrEqual(.5);
    await button.hover();
    await expect.poll(()=>button.evaluate(element=>getComputedStyle(element).transform)).toBe('matrix(1, 0, 0, 1, 0, -1)');
    const metrics=await button.evaluate(element=>{
      const box=element.getBoundingClientRect();const bounds=[];
      for(let ancestor=element.parentElement;ancestor;ancestor=ancestor.parentElement){
        const style=getComputedStyle(ancestor);
        // #176's display:contents wrappers have no box and cannot clip descendants.
        if(style.display==='contents')continue;
        if(/hidden|clip|auto|scroll/.test(`${style.overflowX} ${style.overflowY}`)){
          const clip=ancestor.getBoundingClientRect();
          bounds.push({top:box.top-clip.top,right:clip.right-box.right,bottom:clip.bottom-box.bottom,left:box.left-clip.left});
        }
      }
      return {height:box.height,width:box.width,cardWidth:element.closest('.asset-technician-card')!.getBoundingClientRect().width,shadow:getComputedStyle(element).boxShadow,bounds,touch:matchMedia('(pointer:coarse), (max-width:700px)').matches};
    });
    expect(metrics.shadow).toContain('10px');expect(metrics.width).toBeLessThan(metrics.cardWidth*.6);
    expect(metrics.height).toBeGreaterThanOrEqual(44);
    expect(metrics.bounds.length).toBeGreaterThan(0);
    for(const clip of metrics.bounds)for(const space of Object.values(clip))expect(space).toBeGreaterThanOrEqual(10);
    await technician.screenshot({path:testInfo.outputPath('update-entry-hover.png')});
    await page.mouse.move(0,0);await toggle.focus();await page.keyboard.press('Tab');
    await expect(button).toBeFocused();expect(await button.evaluate(element=>element.matches(':focus-visible'))).toBe(true);
    await expect(button).toHaveCSS('outline-style','solid');await expect(button).toHaveCSS('outline-width','2px');
    await page.emulateMedia({reducedMotion:'reduce'});await button.hover();await expect(button).toHaveCSS('transform','none');
    await toggle.click();await expect(button).not.toBeVisible();
  });
}
