import {expect,type Page,test} from '@playwright/test';

type Library='machine'|'equipment';
const permissions={canEdit:true,canDelete:true,canResolve:true,canReopen:false,canAddUpdate:true,canDeleteAttachments:true};
const machineAsset={id:9801,assetNumber:'PRESS-98',assetName:'Lifecycle Press',brand:'Toyo',model:'M-98',serialNumber:'M98-SN',machineYear:'2022',machineType:'Injection Molding Machine',powerType:'Electric',setupType:'Standard Injection',shotSizeOz:12,tonnage:250,barrelDiameter:'35mm',location:'North Cell',department:'Molding',status:'active',voltageValue:'480',voltageType:'AC',fullLoadAmp:'120',machineLength:'20 ft',machineWidth:'7 ft',machineHeight:'8 ft',fullDieHeightLength:'48 in',screwType:'GP',screwTipType:'Ring',screwTipInstalledDate:'',screwInstalledDate:'',barrelInstalledDate:'',barrelEndCapInstalledDate:'',barrelLength:'96 in',screwLength:'92 in',screwRebuildRepaired:false,barrelRebuildRepaired:false,screwConditionStatus:'used',barrelConditionStatus:'used',hasDoubleShotInjection:false,hasPlungerInjection:false,screw2Type:'',screw2TipType:'',screw2RebuildRepaired:false,screw2ConditionStatus:'new',screw2InstalledDate:'',screw2TipInstalledDate:'',screw2Length:'',barrel2Diameter:'',barrel2RebuildRepaired:false,barrel2ConditionStatus:'new',barrel2InstalledDate:'',barrel2EndCapInstalledDate:'',barrel2Length:'',plungerType:'',plungerRebuildRepaired:false,plungerConditionStatus:'new',plungerInstalledDate:'',plungerLength:'',plungerDiameter:'',plungerBarrelType:'',plungerBarrelRebuildRepaired:false,plungerBarrelConditionStatus:'new',plungerBarrelInstalledDate:'',plungerBarrelEndCapInstalledDate:'',plungerBarrelLength:'',plungerBarrelDiameter:'',notes:'',criticalNotes:'',createdAt:'2026-01-01T12:00:00Z',updatedAt:'2026-08-20T12:00:00Z',brandColorHex:'#1E6BFF',historyPreview:[]};
const equipmentAsset={id:9802,assetNumber:'EQ-98',equipmentName:'Lifecycle Dryer',assetName:'Lifecycle Dryer',category:'Dryer',equipmentType:'Desiccant Dryer',manufacturer:'Matsui',brand:'Matsui',model:'E-98',serialNumber:'E98-SN',equipmentYear:'2023',year:'2023',location:'South Cell',department:'Molding',status:'active',criticality:'high',powerType:'Electric',voltage:'480 VAC',phase:'3 phase',amperage:'30 A',airRequirement:'90 PSI',waterRequirement:'N/A',capacityRating:'500 lb',dimensions:'48 x 36 x 84 in',weight:'825 lb',specificationNotes:'',createdAt:'2026-01-01T12:00:00Z',updatedAt:'2026-08-20T12:00:00Z'};

function issue(id:number,overrides:Record<string,unknown>={}){return{id,assetId:9800,title:`Warning issue ${id}`,noteDate:'2026-08-20',body:'Original bearing vibration problem statement.',warning:true,workOrder:`WO-${id}`,status:'active',createdBy:'Issue Creator',createdAt:'2026-08-20T12:00:00Z',updatedAt:'2026-08-20T12:00:00Z',resolvedAt:null,resolvedBy:'',resolutionSummary:'',resolvedYear:'',pdfFilename:`issue-${id}.pdf`,pdfUrl:`/api/machine-library/asset-notes/${id}/pdf`,pdfDownloadUrl:`/api/machine-library/asset-notes/${id}/pdf?download=true`,attachments:[],updates:[],lifecycle:[{id:id*10,type:'issue_created',actor:'Issue Creator',reason:'',createdAt:'2026-08-20T12:00:00Z'}],permissions:{...permissions},...overrides};}
function ordinary(id:number){return{id,assetId:9800,title:'Ordinary lubrication note',noteDate:'2026-08-19',body:'Lubrication checked with no warning condition.',warning:false,workOrder:'',status:'ordinary',createdBy:'Issue Creator',createdAt:'2026-08-19T12:00:00Z',updatedAt:'2026-08-19T12:00:00Z',pdfFilename:`ordinary-${id}.pdf`,pdfUrl:`/api/machine-library/asset-notes/${id}/pdf`,pdfDownloadUrl:`/api/machine-library/asset-notes/${id}/pdf?download=true`,attachments:[],updates:[],lifecycle:[],permissions:{...permissions,canResolve:false,canReopen:false,canAddUpdate:false}};}

async function mockLibrary(page:Page,library:Library){
  const asset=library==='machine'?machineAsset:equipmentAsset;const assetId=asset.id;let notes=[issue(9810,{assetId,assetNumber:asset.assetNumber,assetName:asset.assetName,workOrder:`WO-${library.toUpperCase()}-98`,title:`${library} active warning`}),issue(9811,{assetId,assetNumber:asset.assetNumber,assetName:asset.assetName,title:`${library} resolved 2026`,status:'resolved',resolvedAt:'2026-05-10T14:00:00Z',resolvedBy:'Maintenance Manager',resolutionSummary:'Verified repair.',resolvedYear:'2026',permissions:{...permissions,canResolve:false,canReopen:true,canAddUpdate:false}}),issue(9812,{assetId,assetNumber:asset.assetNumber,assetName:asset.assetName,title:`${library} resolved 2025`,status:'resolved',resolvedAt:'2025-09-10T14:00:00Z',resolvedBy:'Maintenance Manager',resolutionSummary:'Prior-year repair.',resolvedYear:'2025',permissions:{...permissions,canResolve:false,canReopen:true,canAddUpdate:false}}),ordinary(9813).valueOf()];
  await page.route('**/api/auth/status',route=>route.fulfill({json:{setupRequired:false,user:{id:1,fullName:'Lifecycle Admin',email:'admin@example.com',role:'Admin',isOwnerAdmin:true,forcePasswordChange:false}}}));
  await page.route(new RegExp(`/api/${library}-library/assets(?:\\?.*)?$`),route=>route.fulfill({json:library==='machine'?{ok:true,assets:[asset],brandSettings:[],permissions:{canEdit:true,canDelete:true,canManagePm:true}}:{ok:true,assets:[asset],categories:['Dryer'],permissions:{canEdit:true,canDelete:true,canManagePm:true}}}));
  await page.route(new RegExp(`/api/${library}-library/assets/${assetId}/notes$`),route=>route.fulfill({json:{ok:true,notes,permissions:{canCreate:true}}}));
  await page.route(new RegExp(`/api/${library}-library/assets/${assetId}/history$`),route=>route.fulfill({json:{ok:true,records:[]}}));
  await page.route(new RegExp(`/api/${library}-library/assets/${assetId}/inspection-records$`),route=>route.fulfill({json:{ok:true,records:[]}}));
  await page.route(new RegExp(`/api/${library}-library/assets/${assetId}/component-images$`),route=>route.fulfill({json:{ok:true,images:[]}}));
  await page.route(new RegExp(`/api/${library}-library/assets/${assetId}/preventive-maintenance$`),route=>route.fulfill({json:{ok:true,tasks:[],summary:{total:0,dueSoon:0,overdue:0,nextDueDate:null,nextDueMeter:null}}}));
  await page.route(new RegExp(`/api/${library}-library/assets/${assetId}/document-folders$`),route=>route.fulfill({json:{ok:true,folders:[],summary:{folderCount:0,documentCount:0}}}));
  await page.route(new RegExp(`/api/${library}-library/assets/${assetId}/documents$`),route=>route.fulfill({json:{ok:true,documents:[]}}));
  await page.route(new RegExp(`/api/${library}-library/asset-notes/9810/updates$`),route=>{const current=notes.find(note=>note.id===9810)!;const update={id:9898,noteId:9810,body:'Bearing replaced and vibration tested under load.',createdBy:'Lifecycle Admin',createdAt:'2026-08-20T13:00:00Z',attachments:[]};current.updates=[...current.updates,update];current.lifecycle=[...current.lifecycle,{id:98980,type:'update_added',actor:'Lifecycle Admin',reason:'',createdAt:update.createdAt}];return route.fulfill({status:201,json:{ok:true,update,note:current}});});
  await page.route(new RegExp(`/api/${library}-library/asset-notes/9810/resolve$`),route=>{const current=notes.find(note=>note.id===9810)!;Object.assign(current,{status:'resolved',resolvedAt:'2026-08-20T14:00:00Z',resolvedBy:'Lifecycle Admin',resolutionSummary:'Repair verified under production load.',resolvedYear:'2026',permissions:{...permissions,canResolve:false,canReopen:true,canAddUpdate:false}});current.lifecycle=[...current.lifecycle,{id:98981,type:'issue_resolved',actor:'Lifecycle Admin',reason:'Repair verified under production load.',createdAt:current.resolvedAt}];return route.fulfill({json:{ok:true,note:current}});});
  await page.route(new RegExp(`/api/${library}-library/asset-notes/9810/reopen$`),route=>{const current=notes.find(note=>note.id===9810)!;Object.assign(current,{status:'active',resolvedAt:null,resolvedBy:'',resolutionSummary:'',resolvedYear:'',permissions:{...permissions}});current.lifecycle=[...current.lifecycle,{id:98982,type:'issue_reopened',actor:'Lifecycle Admin',reason:'Follow-up reading moved.',createdAt:'2026-08-20T15:00:00Z'}];return route.fulfill({json:{ok:true,note:current}});});
  await page.route(new RegExp(`/api/${library}-library/asset-notes/9810$`),route=>{if(route.request().method()==='DELETE'){notes=notes.filter(note=>note.id!==9810);return route.fulfill({json:{ok:true,historyPreserved:true}});}return route.fallback();});
  return{asset,assetId};
}

for(const library of ['machine','equipment'] as const){
  test(`${library} warning issue UI provides equivalent accessible lifecycle history`,async({page})=>{
    const{asset,assetId}=await mockLibrary(page,library);await page.goto(`/${library}-library?asset=${assetId}`);await page.getByRole('button',{name:/Asset Notes & Attachments/}).click();
    const activeCard=page.locator('.asset-note-entry',{hasText:`${library} active warning`});await expect(activeCard).toContainText(`WO-${library.toUpperCase()}-98`);await expect(activeCard.getByText('Original bearing vibration problem statement.')).toBeVisible();await expect(activeCard.getByRole('button',{name:'+ Add Update'})).toBeVisible();
    await activeCard.getByRole('button',{name:'+ Add Update'}).click();const updateField=activeCard.getByLabel('Maintenance work / progress update *');await expect(updateField).toBeFocused();await updateField.fill('Bearing replaced and vibration tested under load.');await activeCard.getByRole('button',{name:'Add Update',exact:true}).click();await expect(activeCard).toContainText('Bearing replaced and vibration tested under load.');await expect(activeCard).toContainText('Lifecycle Admin');await expect(activeCard.getByText('Original bearing vibration problem statement.')).toBeVisible();
    await activeCard.getByRole('button',{name:'Issue is Resolved'}).click();await expect(activeCard.getByRole('checkbox',{name:/Issue is Resolved/})).toBeChecked();await activeCard.getByLabel('Resolution Summary *').fill('Repair verified under production load.');await activeCard.getByRole('button',{name:'Confirm Resolution'}).click();await expect(page.getByRole('status')).toContainText('removed from Dashboard attention');
    const history=page.getByRole('heading',{name:'Resolved History'});await expect(history).toBeVisible();const year2026=page.getByRole('button',{name:/2026.*resolved issue/});await expect(year2026).toHaveAttribute('aria-expanded','false');await year2026.click();await expect(year2026).toHaveAttribute('aria-expanded','true');await expect(page.getByText(`${library} active warning`)).toBeVisible();
    const year2025=page.getByRole('button',{name:/2025.*resolved issue/});await year2025.click();await expect(page.getByText(`${library} resolved 2025`)).toBeVisible();
    await page.getByLabel('Search Asset Notes').fill(`WO-${library.toUpperCase()}-98`);await page.getByLabel('Note status').selectOption('resolved');await expect(page.getByText(`${library} resolved 2026`)).toHaveCount(0);const filteredYear=page.getByRole('button',{name:/2026.*1 resolved issue/});if(await filteredYear.getAttribute('aria-expanded')!=='true')await filteredYear.click();const resolvedCard=page.locator('.asset-note-entry',{hasText:`${library} active warning`});await expect(resolvedCard).toContainText(asset.assetNumber);await expect(resolvedCard).toContainText('Repair verified under production load.');await resolvedCard.getByRole('button',{name:'Reopen Issue'}).click();await resolvedCard.getByLabel('Reopen Reason *').fill('Follow-up reading moved.');await resolvedCard.getByRole('button',{name:'Reopen Issue'}).last().click();await expect(page.getByRole('status')).toContainText('restored to Dashboard attention');
    await page.getByLabel('Search Asset Notes').fill('');await page.getByLabel('Note status').selectOption('all');const reopenedCard=page.locator('.asset-note-entry',{hasText:`${library} active warning`});await expect(reopenedCard.getByRole('button',{name:'+ Add Update'})).toBeVisible();
    await reopenedCard.getByRole('button',{name:`More actions for ${library} active warning`}).click();await page.getByRole('menuitem',{name:'Delete Note'}).click();await expect(reopenedCard.getByLabel('Delete Reason *')).toBeVisible();await reopenedCard.getByLabel('Delete Reason *').fill('Duplicate issue retired after review.');page.once('dialog',dialog=>dialog.accept());await reopenedCard.getByRole('button',{name:'Delete Warning Issue'}).click();await expect(page.getByRole('status')).toContainText('audit evidence preserved');await expect(page.getByText(`${library} active warning`)).toHaveCount(0);
    const overflow=await page.evaluate(()=>document.documentElement.scrollWidth-document.documentElement.clientWidth);expect(overflow).toBeLessThanOrEqual(1);
  });
}
