import { useRef, useState } from 'react';
import { createPortal } from 'react-dom';

type ArchiveEntry={key:string;path:string;sha256:string;sizeBytes:number;mimeType:string;kind:string;library:'machine'|'equipment';assetId:number;recordId:number;attachmentId?:number;updateId?:number;downloadUrl?:string;content?:string};
type ArchiveManifestEntry=Omit<ArchiveEntry,'downloadUrl'|'content'>;
type ArchivePlan={schemaVersion:1;year:number;directoryName:string;generatedAt:string;libraries:Array<'machine'|'equipment'>;conflictPolicy:string;totals:{assetCount:number;recordCount:number;attachmentCount:number;recordPdfCount:number;fileCount:number;totalBytes:number};entries:ArchiveEntry[];failures:Array<{key:string;path:string;message:string}>};
type ArchiveManifest=Omit<ArchivePlan,'entries'>&{entries:ArchiveManifestEntry[]};
type ExportCounts={added:number;updated:number;skipped:number;failed:number};
type ExportProgress=ExportCounts&{state:'preparing'|'running'|'success'|'error'|'canceled';mode:'directory'|'download';message:string;current:string;processedFiles:number;processedBytes:number;totalFiles:number;totalBytes:number;plan:ArchivePlan|null};

type WritableFileLike={write:(data:BufferSource|Blob|string)=>Promise<void>;close:()=>Promise<void>;abort?:()=>Promise<void>};
type FileHandleLike={getFile:()=>Promise<File>;createWritable:()=>Promise<WritableFileLike>};
type DirectoryHandleLike={name?:string;getDirectoryHandle:(name:string,options?:{create?:boolean})=>Promise<DirectoryHandleLike>;getFileHandle:(name:string,options?:{create?:boolean})=>Promise<FileHandleLike>};
type DirectoryPickerWindow=Window&{showDirectoryPicker?:(options?:{mode?:'read'|'readwrite'})=>Promise<DirectoryHandleLike>};

const emptyProgress:ExportProgress={state:'preparing',mode:'download',message:'Preparing work-order records…',current:'',processedFiles:0,processedBytes:0,totalFiles:0,totalBytes:0,added:0,updated:0,skipped:0,failed:0,plan:null};

function formatBytes(bytes:number){if(bytes<1024)return`${bytes} B`;if(bytes<1024*1024)return`${(bytes/1024).toFixed(bytes<10*1024?1:0)} KB`;return`${(bytes/1024/1024).toFixed(1)} MB`;}
function isCanceled(error:unknown){return error instanceof DOMException&&(error.name==='AbortError'||error.name==='NotAllowedError')||(error instanceof Error&&/cancel|aborted/i.test(error.message));}
function safeRelativePath(value:string){const segments=value.replace(/\\/g,'/').split('/');return Boolean(value)&&segments.every(segment=>Boolean(segment)&&segment!=='.'&&segment!=='..'&&!/[\x00-\x1f\x7f]/.test(segment));}
function manifestEntry(entry:ArchiveEntry):ArchiveManifestEntry{const{downloadUrl:_downloadUrl,content:_content,...stored}=entry;return stored;}
function recordKey(entry:{key:string}){return /^.+?:record:\d+/.exec(entry.key)?.[0]??'';}
function parentPath(value:string){return value.split('/').slice(0,-1).join('/');}
function assetRoot(entry:{path:string}){return entry.path.split('/').slice(0,2).join('/');}
async function sha256(bytes:ArrayBuffer){const digest=await crypto.subtle.digest('SHA-256',bytes);return [...new Uint8Array(digest)].map(value=>value.toString(16).padStart(2,'0')).join('');}
async function responseError(response:Response,fallback:string){const data=await response.json().catch(()=>({})) as{error?:string};return new Error(data.error||fallback);}
async function fetchPlan(year:number,signal:AbortSignal){const response=await fetch(`/api/work-order-records/export-plan?year=${year}`,{credentials:'include',cache:'no-store',signal});if(!response.ok)throw await responseError(response,'Work-order export could not be prepared.');const data=await response.json() as{plan?:ArchivePlan};if(!data.plan)throw new Error('Work-order export plan is missing.');return data.plan;}
async function responseBytes(response:Response,signal:AbortSignal,onBytes:(bytes:number)=>void){
  if(!response.ok)throw await responseError(response,'An export file could not be downloaded.');if(!response.body){const buffer=await response.arrayBuffer();onBytes(buffer.byteLength);return buffer;}
  const reader=response.body.getReader();const chunks:Uint8Array[]=[];let length=0;
  try{for(;;){if(signal.aborted)throw new DOMException('Work-order export was canceled.','AbortError');const{done,value}=await reader.read();if(done)break;if(value){chunks.push(value);length+=value.byteLength;onBytes(value.byteLength);}}}finally{reader.releaseLock();}
  const bytes=new Uint8Array(length);let offset=0;for(const chunk of chunks){bytes.set(chunk,offset);offset+=chunk.byteLength;}return bytes.buffer;
}
async function entryBytes(entry:ArchiveEntry,signal:AbortSignal,onBytes:(bytes:number)=>void){if(entry.content!==undefined){const bytes=new TextEncoder().encode(entry.content);onBytes(bytes.byteLength);return bytes.buffer;}if(!entry.downloadUrl)throw new Error('Export file URL is missing.');return responseBytes(await fetch(entry.downloadUrl,{credentials:'include',cache:'no-store',signal}),signal,onBytes);}
async function nestedDirectory(root:DirectoryHandleLike,relativePath:string){const segments=relativePath.split('/');segments.pop();let current=root;for(const segment of segments)current=await current.getDirectoryHandle(segment,{create:true});return current;}
async function existingFile(root:DirectoryHandleLike,relativePath:string){try{const segments=relativePath.split('/');const name=segments.pop()!;let current=root;for(const segment of segments)current=await current.getDirectoryHandle(segment);return await current.getFileHandle(name);}catch(error){if(error instanceof DOMException&&error.name!=='NotFoundError')throw error;return null;}}
async function writeFile(root:DirectoryHandleLike,relativePath:string,data:BufferSource|string){if(!safeRelativePath(relativePath))throw new Error('The export plan contains an unsafe path.');const directory=await nestedDirectory(root,relativePath);const name=relativePath.split('/').pop()!;const handle=await directory.getFileHandle(name,{create:true});const writable=await handle.createWritable();try{await writable.write(data);await writable.close();}catch(error){try{await writable.abort?.();}catch{}throw error;}}
async function readManifest(root:DirectoryHandleLike):Promise<ArchiveManifest|null>{try{const handle=await root.getFileHandle('WO_EXPORT_MANIFEST.json');const data=JSON.parse(await(await handle.getFile()).text()) as ArchiveManifest;if(data.schemaVersion!==1||!Array.isArray(data.entries))return null;return data;}catch(error){if(error instanceof DOMException&&error.name!=='NotFoundError')throw error;return null;}}
function sameDirectoryName(left:string|undefined,right:string){return Boolean(left)&&left!.toLocaleLowerCase()===right.toLocaleLowerCase();}
function isArchiveManifest(manifest:ArchiveManifest|null,plan:ArchivePlan){return Boolean(manifest&&manifest.year===plan.year&&manifest.directoryName===plan.directoryName);}
async function resolveArchiveRoot(selected:DirectoryHandleLike,plan:ArchivePlan){
  const selectedManifest=await readManifest(selected);
  if(sameDirectoryName(selected.name,plan.directoryName)||isArchiveManifest(selectedManifest,plan))return{root:selected,previous:selectedManifest};
  const root=await selected.getDirectoryHandle(plan.directoryName,{create:true});
  return{root,previous:await readManifest(root)};
}
function manifestSignature(manifest:ArchiveManifest){const{generatedAt:_generatedAt,...stable}=manifest;return JSON.stringify(stable);}
function downloadBlob(blob:Blob,filename:string){const url=URL.createObjectURL(blob);const link=document.createElement('a');link.href=url;link.download=filename;document.body.appendChild(link);link.click();link.remove();window.setTimeout(()=>URL.revokeObjectURL(url),1000);}
function exportInfo(plan:ArchivePlan,counts:ExportCounts){return['Maintenance Command Center - Work Order Records Export','',`Year: ${plan.year}`,`Export timestamp: ${new Date().toISOString()}`,'Export mode: directory',`Libraries: ${plan.libraries.join(', ')||'none'}`,`Assets: ${plan.totals.assetCount}`,`Records: ${plan.totals.recordCount}`,`Attachments: ${plan.totals.attachmentCount}`,`Generated record PDFs: ${plan.totals.recordPdfCount}`,`Files: ${plan.totals.fileCount}`,`Total uncompressed bytes: ${plan.totals.totalBytes}`,`New: ${counts.added}`,`Updated: ${counts.updated}`,`Unchanged / skipped: ${counts.skipped}`,`Failed: ${counts.failed}`,'',`Conflict policy: ${plan.conflictPolicy}`,'Integrity: WO_EXPORT_MANIFEST.json records a SHA-256 digest and byte size for every exported record and file.','Prior manifest entries absent from the current MCC plan are retained and are not automatically deleted.',''].join('\n');}

export function WorkOrderRecordsExport({canExport}:{canExport:boolean}){
  const [progress,setProgress]=useState<ExportProgress|null>(null);const abortRef=useRef<AbortController|null>(null);const picker=(window as DirectoryPickerWindow).showDirectoryPicker;const directorySupported=Boolean(window.isSecureContext&&picker);
  function update(values:Partial<ExportProgress>){setProgress(current=>current?{...current,...values}:current);}
  async function runDirectoryExport(selected:DirectoryHandleLike,year:number,controller:AbortController){
    const plan=await fetchPlan(year,controller.signal);const{root,previous}=await resolveArchiveRoot(selected,plan);const priorEntries=new Map((previous?.entries??[]).filter(entry=>safeRelativePath(entry.path)).map(entry=>[entry.key,entry]));const merged=new Map(priorEntries);const currentRecordRoots=new Map(plan.entries.filter(entry=>entry.kind==='record').map(entry=>[recordKey(entry),parentPath(entry.path)]));const priorRecordRoots=new Map([...priorEntries.values()].filter(entry=>entry.kind==='record').map(entry=>[recordKey(entry),parentPath(entry.path)]));const priorAssetRoots=new Map([...priorEntries.values()].map(entry=>[`${entry.library}:${entry.assetId}`,assetRoot(entry)]));const counts:ExportCounts={added:0,updated:0,skipped:0,failed:plan.failures.length};let processedBytes=0;let processedFiles=0;
    update({state:'running',mode:'directory',message:`Updating ${plan.directoryName} in the selected destination.`,plan,totalFiles:plan.totals.fileCount,totalBytes:plan.totals.totalBytes,failed:counts.failed});
    for(const entry of plan.entries){if(controller.signal.aborted)throw new DOMException('Work-order export was canceled.','AbortError');const prior=priorEntries.get(entry.key);const stableRecordRoot=priorRecordRoots.get(recordKey(entry));const currentRecordRoot=currentRecordRoots.get(recordKey(entry));const stableAssetRoot=priorAssetRoots.get(`${entry.library}:${entry.assetId}`);const currentAssetRoot=assetRoot(entry);const inheritedPath=stableRecordRoot&&currentRecordRoot&&entry.path.startsWith(`${currentRecordRoot}/`)?`${stableRecordRoot}${entry.path.slice(currentRecordRoot.length)}`:stableAssetRoot&&entry.path.startsWith(`${currentAssetRoot}/`)?`${stableAssetRoot}${entry.path.slice(currentAssetRoot.length)}`:entry.path;const targetPath=prior?.path&&safeRelativePath(prior.path)?prior.path:inheritedPath;update({current:targetPath,processedBytes,processedFiles,...counts});
      try{
        const handle=await existingFile(root,targetPath);let unchanged=false;if(handle){const file=await handle.getFile();if(file.size===entry.sizeBytes)unchanged=await sha256(await file.arrayBuffer())===entry.sha256;}
        if(unchanged){counts.skipped+=1;processedBytes+=entry.sizeBytes;processedFiles+=1;merged.set(entry.key,{...manifestEntry(entry),path:targetPath});update({processedBytes,processedFiles,...counts});continue;}
        let transferBytes=0;const bytes=await entryBytes(entry,controller.signal,count=>{transferBytes+=count;update({processedBytes:processedBytes+Math.min(transferBytes,entry.sizeBytes)});});if(bytes.byteLength!==entry.sizeBytes)throw new Error(`Downloaded ${bytes.byteLength} bytes; expected ${entry.sizeBytes}.`);if(await sha256(bytes)!==entry.sha256)throw new Error('Downloaded bytes did not match the export SHA-256 digest.');await writeFile(root,targetPath,new Uint8Array(bytes));if(prior||handle)counts.updated+=1;else counts.added+=1;processedBytes+=entry.sizeBytes;processedFiles+=1;merged.set(entry.key,{...manifestEntry(entry),path:targetPath});
      }catch(error){if(isCanceled(error))throw error;counts.failed+=1;processedFiles+=1;}
      update({processedBytes,processedFiles,...counts});
    }
    if(controller.signal.aborted)throw new DOMException('Work-order export was canceled.','AbortError');const manifest:ArchiveManifest={...plan,generatedAt:new Date().toISOString(),entries:[...merged.values()].sort((left,right)=>left.path.localeCompare(right.path))};const archiveUnchanged=Boolean(previous&&manifestSignature(previous)===manifestSignature(manifest));if(!archiveUnchanged){await writeFile(root,'WO_EXPORT_MANIFEST.json',`${JSON.stringify(manifest,null,2)}\n`);await writeFile(root,'MCC_WORK_ORDER_EXPORT_INFO.txt',exportInfo(plan,counts));}
    update({state:counts.failed?'error':'success',message:counts.failed?`${plan.directoryName} was updated with ${counts.failed} failed item${counts.failed===1?'':'s'}.`:`${plan.directoryName} is up to date.`,current:archiveUnchanged?'No destination writes required':'Export manifest complete',processedBytes,processedFiles,...counts});
    void fetch('/api/work-order-records/export-complete',{method:'POST',credentials:'include',headers:{'Content-Type':'application/json'},body:JSON.stringify({year,added:counts.added,updated:counts.updated,skipped:counts.skipped,failed:counts.failed,totalBytes:processedBytes})}).catch(()=>undefined);
  }
  async function runDownloadExport(year:number,controller:AbortController){const plan=await fetchPlan(year,controller.signal);let downloaded=0;update({state:'running',mode:'download',message:'This browser cannot update a folder in place. Creating a new structure-preserving download.',current:`Downloading ${plan.directoryName}.zip`,plan,totalFiles:plan.totals.fileCount,totalBytes:plan.totals.totalBytes,failed:plan.failures.length});const response=await fetch(`/api/work-order-records/export.zip?year=${year}`,{credentials:'include',cache:'no-store',signal:controller.signal});const bytes=await responseBytes(response,controller.signal,count=>{downloaded+=count;update({processedBytes:downloaded});});downloadBlob(new Blob([bytes],{type:'application/zip'}),`${plan.directoryName}.zip`);update({state:plan.failures.length?'error':'success',mode:'download',message:plan.failures.length?`Downloaded a new package with ${plan.failures.length} source failure${plan.failures.length===1?'':'s'}.`:'Downloaded a new package. No existing destination was updated in place.',current:'Download complete',processedFiles:plan.totals.fileCount,processedBytes:downloaded,added:plan.totals.fileCount,updated:0,skipped:0,failed:plan.failures.length,plan});}
  async function begin(){if(!canExport)return;const controller=new AbortController();abortRef.current=controller;const year=new Date().getFullYear();setProgress({...emptyProgress,mode:directorySupported?'directory':'download',message:directorySupported?'Choose the drive or folder that should contain the yearly archive.':'Preparing a new downloadable yearly archive.'});try{if(directorySupported&&picker){const parent=await picker.call(window,{mode:'readwrite'});await runDirectoryExport(parent,year,controller);}else await runDownloadExport(year,controller);}catch(error){if(isCanceled(error))update({state:'canceled',message:'Export canceled. No partial file was committed; completed files remain safe for the next incremental run.',current:''});else update({state:'error',message:(error as Error).message||'Work-order records could not be exported.',current:''});}finally{abortRef.current=null;}}
  function cancel(){abortRef.current?.abort();}
  if(!canExport)return null;
  const running=progress?.state==='preparing'||progress?.state==='running';const percent=progress&&progress.totalBytes>0?Math.min(100,Math.round(progress.processedBytes/progress.totalBytes*100)):0;
  return <><button className="secondary-button compact-button glass-button glass-button--secondary" type="button" onClick={()=>void begin()}>Export Work Order Records</button>{progress&&createPortal(<div className="modal-backdrop glass-modal-backdrop work-order-export-backdrop" role="presentation"><section className="mcc-card glass-modal-shell work-order-export-modal" role="dialog" aria-modal="true" aria-labelledby="work-order-export-title"><div className="modal-heading"><div><p className="eyebrow">Yearly work-order archive</p><h3 id="work-order-export-title">{progress.plan?.directoryName??`WO_${new Date().getFullYear()}_records`}</h3><p>{progress.mode==='directory'?'Safe incremental folder update':'Download fallback · not an in-place update'}</p></div>{!running&&<button className="link-button compact-button glass-button glass-button--secondary" type="button" onClick={()=>setProgress(null)}>Close</button>}</div><div className={`work-order-export-status is-${progress.state}`} role={progress.state==='error'?'alert':'status'} aria-live="polite"><strong>{progress.message}</strong>{progress.current&&<span title={progress.current}>{progress.current}</span>}</div>{progress.plan&&<><div className="work-order-export-totals"><span><strong>{progress.plan.totals.assetCount}</strong> assets</span><span><strong>{progress.plan.totals.recordCount}</strong> records</span><span><strong>{progress.plan.totals.attachmentCount}</strong> attachments</span><span><strong>{formatBytes(progress.plan.totals.totalBytes)}</strong> source bytes</span></div><div className="work-order-export-progress" aria-label={`Work-order export ${percent}%`}><i style={{width:`${percent}%`}} /></div><p className="work-order-export-meter">{progress.processedFiles} / {progress.totalFiles} files · {formatBytes(progress.processedBytes)} processed</p><div className="work-order-export-counts"><span>New <strong>{progress.added}</strong></span><span>Updated <strong>{progress.updated}</strong></span><span>Skipped <strong>{progress.skipped}</strong></span><span>Failed <strong>{progress.failed}</strong></span></div><p className="form-help">{progress.plan.conflictPolicy}</p>{progress.mode==='download'&&<p className="form-help">Your browser will receive a new ZIP with the same Machine Library / Equipment Library hierarchy. Merge it at the destination if you need an accumulating archive; MCC cannot truthfully perform an in-place update here.</p>}</>}<div className="modal-actions glass-modal__actions">{running?<button className="danger-button glass-button" type="button" onClick={cancel}>Cancel Export</button>:<button className="primary-button glass-button glass-button--primary" type="button" onClick={()=>setProgress(null)}>Done</button>}</div></section></div>,document.body)}</>;
}
