import { type FormEvent, type ReactNode, useEffect, useMemo, useState } from 'react';
import { createPortal } from 'react-dom';
import { ActionButtonProgress, type ActionProgressPhase, useActionProgress } from '../../components/ActionProgress';
import { MccFilePath } from '../../components/MccFilePath';
import { fileTypeIconLabel } from '../../components/MccFileTypeIcon';
import { MccFolderIcon } from '../../components/MccFolderIcon';
import { MccFolderTreeChevron, MccFolderTreeItem } from '../../components/MccFolderTree';
import { MccLibraryFileVisual } from '../../components/MccLibraryFileVisual';
import { MccPillCard, MccStatusPill } from '../../components/MccPills';
import { MccActionGroup, MccOverflowMenu, MccResourceRow, MccResponsiveToolbar } from '../../components/MccResourceRow';
import { MccSummaryToken, MccSummaryTokenGroup } from '../../components/MccSummaryToken';
import { LibraryUploadModal, uploadFormDataWithProgress } from '../../components/LibraryUploadModal';
import { folderImportFailureMessage, LibraryFolderImportError, runLibraryFolderImport } from '../../components/libraryFolderImport';

type AreaSummary={folderCount:number;documentCount:number;pictureCount:number;videoCount:number;fileCount:number};
type FacilityArea={id:number;name:string;description:string;building:string;location:string;department:string;status:string;createdAt:string;updatedAt:string;summary:AreaSummary};
type FacilityFolder={id:number;areaId:number;parentId:number|null;name:string;description:string;path:string;itemCount:number;childCount:number;createdAt:string;updatedAt:string};
type FacilitySearchFolder=FacilityFolder&{facilityName:string};
type FacilityItem={id:number;areaId:number;folderId:number;facilityName:string;folderName:string;folderPath:string;mediaType:'document'|'picture'|'video'|'file';originalFilename:string;displayFilename:string;extension:string;mimeType:string;sizeBytes:number;description:string;caption:string;revision:string;date:string;durationSeconds:number|null;uploadedAt:string;updatedAt:string;uploadedBy:string;contentUrl:string;downloadUrl:string;canPrint:boolean};
type Limits={documentsMb:number;picturesMb:number;videosMb:number};
type AreaEditor={area?:FacilityArea;name:string;description:string;building:string;location:string;department:string;status:string};
type FolderEditor={folder?:FacilityFolder;name:string;description:string;parentId:string};
type ItemEditor={item:FacilityItem;displayFilename:string;description:string;caption:string;revision:string;date:string};
type ApiError=Error&{code?:string};
const apiBase='/api/facility-info';

async function responseJson<T>(response:Response):Promise<T>{
  const data=await response.json().catch(()=>({error:`Request failed (${response.status}).`})) as Record<string,unknown>;
  if(!response.ok){const error=new Error(String(data.error??`Request failed (${response.status}).`)) as ApiError;error.code=String(data.code??'');throw error;}
  return data as T;
}
function formatDate(value:string){if(!value)return 'Not recorded';const date=new Date(value);return Number.isNaN(date.getTime())?value:date.toLocaleDateString();}
function formatDateTime(value:string){if(!value)return 'Not recorded';const date=new Date(value);return Number.isNaN(date.getTime())?value:date.toLocaleString();}
function formatBytes(value:number){if(value<1024)return `${value} B`;if(value<1024**2)return `${(value/1024).toFixed(1)} KB`;if(value<1024**3)return `${(value/1024**2).toFixed(1)} MB`;return `${(value/1024**3).toFixed(1)} GB`;}
function triggerDownload(url:string,filename:string){const link=document.createElement('a');link.href=url;link.download=filename;document.body.appendChild(link);link.click();link.remove();}
function locationLine(area:FacilityArea){return [area.building,area.location,area.department].filter(Boolean).join(' · ');}

export function FacilityInfoPage(){
  const [areas,setAreas]=useState<FacilityArea[]>([]);const [selectedAreaId,setSelectedAreaId]=useState<number|null>(null);const [folders,setFolders]=useState<FacilityFolder[]>([]);const [items,setItems]=useState<FacilityItem[]>([]);
  const [permissions,setPermissions]=useState({canWrite:false,canRecoveryExport:false});const [limits,setLimits]=useState<Limits>({documentsMb:500,picturesMb:500,videosMb:1024});
  const [loading,setLoading]=useState(true);const [error,setError]=useState('');const [notice,setNotice]=useState('');const [search,setSearch]=useState('');const [typeFilter,setTypeFilter]=useState('all');const [fileType,setFileType]=useState('');const [sort,setSort]=useState('name');const [searchResults,setSearchResults]=useState<FacilityItem[]>([]);const [searchAreas,setSearchAreas]=useState<FacilityArea[]>([]);const [searchFolders,setSearchFolders]=useState<FacilitySearchFolder[]>([]);const [searching,setSearching]=useState(false);
  const [openFolders,setOpenFolders]=useState<Set<number>>(new Set());const [viewMode,setViewMode]=useState<'list'|'gallery'>('list');
  const [areaEditor,setAreaEditor]=useState<AreaEditor|null>(null);const [folderEditor,setFolderEditor]=useState<FolderEditor|null>(null);const [uploadOpen,setUploadOpen]=useState(false);const [uploadFolder,setUploadFolder]=useState<FacilityFolder|null>(null);const [pendingFiles,setPendingFiles]=useState<File[]>([]);const [uploadMeta,setUploadMeta]=useState({description:'',caption:'',revision:'',date:''});const [duplicate,setDuplicate]=useState(false);const [itemEditor,setItemEditor]=useState<ItemEditor|null>(null);const [moveItem,setMoveItem]=useState<FacilityItem|null>(null);const [moveAreaId,setMoveAreaId]=useState('');const [moveFolderId,setMoveFolderId]=useState('');const [moveDuplicate,setMoveDuplicate]=useState(false);const [viewerItem,setViewerItem]=useState<FacilityItem|null>(null);const [busy,setBusy]=useState(false);const [uploadProgress,setUploadProgress]=useState<number|null>(null);const [uploadCurrent,setUploadCurrent]=useState('');const [uploadCompleted,setUploadCompleted]=useState(0);
  const areaAction=useActionProgress();const folderAction=useActionProgress();const itemAction=useActionProgress();
  const selectedArea=areas.find(area=>area.id===selectedAreaId)??null;

  async function loadHome(){
    setLoading(true);setError('');
    try{
      const [home,access]=await Promise.all([responseJson<{areas:FacilityArea[];limits:Limits}>(await fetch(apiBase,{credentials:'include'})),responseJson<{canWrite:boolean;canRecoveryExport:boolean}>(await fetch(`${apiBase}/permissions`,{credentials:'include'}))]);
      setAreas(home.areas);setLimits(home.limits);setPermissions(access);
    }catch(value){setError((value as Error).message||'Facility Info could not be loaded.');}
    finally{setLoading(false);}
  }
  async function loadArea(areaId:number){
    setLoading(true);setError('');
    try{const data=await responseJson<{area:FacilityArea;folders:FacilityFolder[];items:FacilityItem[]}>(await fetch(`${apiBase}/areas/${areaId}`,{credentials:'include'}));setAreas(current=>current.map(area=>area.id===areaId?data.area:area));setFolders(data.folders);setItems(data.items);setOpenFolders(current=>current.size?current:new Set(data.folders.filter(folder=>folder.parentId===null).map(folder=>folder.id)));}
    catch(value){setError((value as Error).message||'Facility area could not be loaded.');}
    finally{setLoading(false);}
  }
  useEffect(()=>{void loadHome();},[]);
  useEffect(()=>{if(selectedAreaId)void loadArea(selectedAreaId);},[selectedAreaId]);
  useEffect(()=>{
    if(!search.trim()&&!selectedAreaId){setSearchResults([]);setSearchAreas([]);setSearchFolders([]);return;}
    const timeout=window.setTimeout(async()=>{setSearching(true);try{const params=new URLSearchParams({q:search,type:typeFilter,sort});if(fileType)params.set('fileType',fileType);if(selectedAreaId)params.set('areaId',String(selectedAreaId));const data=await responseJson<{items:FacilityItem[];areas?:FacilityArea[];folders?:FacilitySearchFolder[]}>(await fetch(`${apiBase}/search?${params}`,{credentials:'include'}));setSearchResults(data.items);setSearchAreas(data.areas??[]);setSearchFolders(data.folders??[]);}catch(value){setError((value as Error).message);}finally{setSearching(false);}},220);
    return()=>window.clearTimeout(timeout);
  },[search,typeFilter,fileType,sort,selectedAreaId]);

  const visibleItems=useMemo(()=>selectedAreaId?(search.trim()||typeFilter!=='all'||fileType?searchResults:items):searchResults,[selectedAreaId,search,typeFilter,fileType,searchResults,items]);
  const pictureViewerItems=visibleItems.filter(item=>item.mediaType==='picture');const videoViewerItems=visibleItems.filter(item=>item.mediaType==='video');
  const rootFolders=folders.filter(folder=>folder.parentId===null);
  function descendants(parentId:number,depth=1):Array<{folder:FacilityFolder;depth:number}>{return folders.filter(folder=>folder.parentId===parentId).flatMap(folder=>[{folder,depth},...descendants(folder.id,depth+1)]);}
  const orderedFolders=rootFolders.flatMap(folder=>[{folder,depth:0},...descendants(folder.id)]);

  async function saveArea(event:FormEvent){event.preventDefault();if(!areaEditor)return;setError('');const editing=Boolean(areaEditor.area);const result=await areaAction.run(async()=>responseJson<{area:FacilityArea}>(await fetch(editing?`${apiBase}/areas/${areaEditor.area!.id}`:`${apiBase}/areas`,{method:editing?'PATCH':'POST',credentials:'include',headers:{'Content-Type':'application/json'},body:JSON.stringify(areaEditor)})));if(result.status==='duplicate')return;if(result.status==='error'){setError((result.error as Error).message);return;}setAreaEditor(null);setNotice(editing?'Facility area updated.':'Facility area created.');await loadHome();if(editing&&selectedAreaId===result.value.area.id)await loadArea(result.value.area.id);}
  async function deleteArea(area:FacilityArea){const content=area.summary.documentCount+area.summary.pictureCount+area.summary.videoCount+area.summary.fileCount;let body={};if(content){const confirmation=window.prompt(`“${area.name}” contains ${content} file(s). Export or move them first, then type PERMANENTLY DELETE to permanently remove all remaining content.`);if(confirmation!=='PERMANENTLY DELETE')return;body={confirmation,contentDisposition:'exported_or_moved'};}else if(!window.confirm(`Delete empty Facility area “${area.name}”?`))return;try{await responseJson(await fetch(`${apiBase}/areas/${area.id}`,{method:'DELETE',credentials:'include',headers:{'Content-Type':'application/json'},body:JSON.stringify(body)}));if(selectedAreaId===area.id)setSelectedAreaId(null);setNotice(`Facility area deleted: ${area.name}`);await loadHome();}catch(value){setError((value as Error).message);}}
  async function saveFolder(event:FormEvent){event.preventDefault();if(!selectedArea||!folderEditor)return;setError('');const editing=Boolean(folderEditor.folder);const result=await folderAction.run(async()=>responseJson(await fetch(editing?`${apiBase}/areas/${selectedArea.id}/folders/${folderEditor.folder!.id}`:`${apiBase}/areas/${selectedArea.id}/folders`,{method:editing?'PATCH':'POST',credentials:'include',headers:{'Content-Type':'application/json'},body:JSON.stringify({name:folderEditor.name,description:folderEditor.description,parentId:folderEditor.parentId?Number(folderEditor.parentId):null})})));if(result.status==='duplicate')return;if(result.status==='error'){setError((result.error as Error).message);return;}setFolderEditor(null);setNotice(editing?'Folder updated.':'Folder created.');await loadArea(selectedArea.id);await loadHome();}
  async function deleteFolder(folder:FacilityFolder){if(folder.itemCount||folder.childCount){setError('Folder is not empty. Move or delete its files and child folders first.');return;}if(!window.confirm(`Delete empty folder “${folder.name}”?`))return;try{await responseJson(await fetch(`${apiBase}/areas/${folder.areaId}/folders/${folder.id}`,{method:'DELETE',credentials:'include'}));setNotice(`Folder deleted: ${folder.name}`);await loadArea(folder.areaId);await loadHome();}catch(value){setError((value as Error).message);}}
  function beginUpload(folder:FacilityFolder|null){setUploadFolder(folder);setUploadOpen(true);setPendingFiles([]);setUploadMeta({description:'',caption:'',revision:'',date:''});setDuplicate(false);setUploadProgress(null);setUploadCurrent('');setUploadCompleted(0);setError('');}
  function addFiles(files:File[],replace=false){if(replace){const invalid=files.find(file=>folderFileError(file));setError(invalid?`${String((invalid as File&{webkitRelativePath?:string}).webkitRelativePath??invalid.name)}: ${folderFileError(invalid)}`:'');setPendingFiles(files);return;}const accepted:File[]=[];let message='';for(const file of files){const issue=folderFileError(file);if(issue){message=issue;continue;}accepted.push(file);}const combined=[...pendingFiles,...accepted];if(combined.length>20)message='Select no more than 20 individual files per upload.';setError(message);setPendingFiles(combined.slice(0,20));}
  function folderFileError(file:File){
    const match=/\.([^.\\/]+)$/.exec(file.name.trim());
    const extension=match?.[1].toLowerCase()??'';

    const mediaType=
      ['jpg','jpeg','png','webp'].includes(extension)?'picture':
      ['mp4','webm','mov'].includes(extension)?'video':
      ['pdf','doc','docx','xls','xlsx','txt'].includes(extension)?'document':
      'file';

    const limit=
      mediaType==='video'
        ?limits.videosMb
        :mediaType==='picture'
          ?limits.picturesMb
          :limits.documentsMb;

    return file.size>limit*1024*1024
      ?`${file.name} must be ${limit} MB or smaller.`
      :'';
  }
  async function uploadFacilityFolder(selected:File[],action=''){if(!selectedArea||!selected.length)return;const areaId=selectedArea.id;const baseFolderId=uploadFolder?.id??null;setBusy(true);setError('');setNotice('');setUploadProgress(0);setUploadCompleted(0);setDuplicate(false);try{const result=await runLibraryFolderImport({files:selected,baseFolderId,validateFile:folderFileError,listFolders:async()=>{const data=await responseJson<{folders:FacilityFolder[]}>(await fetch(`${apiBase}/areas/${areaId}`,{credentials:'include'}));return data.folders.map(folder=>({id:folder.id,parentId:folder.parentId??null,name:folder.name}));},createFolder:async(name,parentId)=>{const data=await responseJson<{folder:FacilityFolder}>(await fetch(`${apiBase}/areas/${areaId}/folders`,{method:'POST',credentials:'include',headers:{'Content-Type':'application/json'},body:JSON.stringify({name,parentId,description:''})}));return{id:data.folder.id,parentId:data.folder.parentId??null,name:data.folder.name};},uploadFile:async(entry,folderId,onProgress)=>{const body=new FormData();body.append('files',entry.file,entry.file.name);Object.entries(uploadMeta).forEach(([key,value])=>body.append(key,value));if(action)body.append('duplicateAction',action);await uploadFormDataWithProgress(`${apiBase}/areas/${areaId}/folders/${folderId}/items`,body,onProgress);},onCurrent:(stage,path)=>setUploadCurrent(stage==='folder'?`Creating ${path}`:path),onProgress:setUploadProgress,onFileComplete:completed=>setUploadCompleted(completed)});setUploadOpen(false);setUploadFolder(null);setPendingFiles([]);setDuplicate(false);await loadArea(areaId);await loadHome();setOpenFolders(current=>new Set([...current,...(baseFolderId===null?[]:[baseFolderId]),...result.resolvedFolderIds]));setNotice(`${result.completedFiles} file${result.completedFiles===1?'':'s'} uploaded with folder structure preserved.`);}catch(value){const failure=value instanceof LibraryFolderImportError?value:null;if(failure){setPendingFiles(failure.remainingFiles);setUploadCompleted(0);if(failure.code==='FACILITY_DUPLICATE')setDuplicate(true);}await loadArea(areaId);await loadHome();if(failure)setOpenFolders(current=>new Set([...current,...(baseFolderId===null?[]:[baseFolderId]),...failure.resolvedFolderIds]));setError(folderImportFailureMessage(value));}finally{setBusy(false);setUploadCurrent('');setUploadProgress(null);}}
  async function submitUpload(action=''){if(!pendingFiles.length)return;if(pendingFiles.some(file=>Boolean((file as File&{webkitRelativePath?:string}).webkitRelativePath))){await uploadFacilityFolder(pendingFiles,action);return;}if(!uploadFolder){setError('Choose a destination folder for individual files.');return;}const targetFolder=uploadFolder;const selected=[...pendingFiles];const totalBytes=selected.reduce((sum,file)=>sum+file.size,0)||1;let completed=0;let completedBytes=0;setBusy(true);setError('');setUploadProgress(0);setUploadCompleted(0);try{for(const file of selected){setUploadCurrent(file.name);const body=new FormData();body.append('files',file,file.name);Object.entries(uploadMeta).forEach(([key,value])=>body.append(key,value));if(action)body.append('duplicateAction',action);await uploadFormDataWithProgress(`${apiBase}/areas/${targetFolder.areaId}/folders/${targetFolder.id}/items`,body,percent=>setUploadProgress((completedBytes+file.size*percent/100)/totalBytes*100));completed+=1;completedBytes+=file.size;setUploadCompleted(completed);setUploadProgress(completedBytes/totalBytes*100);}const areaId=targetFolder.areaId;setUploadOpen(false);setUploadFolder(null);setPendingFiles([]);setDuplicate(false);setNotice(`${selected.length} file${selected.length===1?'':'s'} uploaded.`);await loadArea(areaId);await loadHome();}catch(value){if(completed){setPendingFiles(selected.slice(completed));setUploadCompleted(0);}const uploadError=value as ApiError;if(uploadError.code==='FACILITY_DUPLICATE')setDuplicate(true);else setError(uploadError.message);}finally{setBusy(false);setUploadCurrent('');setUploadProgress(null);}}
  async function saveItem(event:FormEvent){event.preventDefault();if(!itemEditor)return;setError('');const result=await itemAction.run(async()=>responseJson(await fetch(`${apiBase}/items/${itemEditor.item.id}`,{method:'PATCH',credentials:'include',headers:{'Content-Type':'application/json'},body:JSON.stringify(itemEditor)})));if(result.status==='duplicate')return;if(result.status==='error'){setError((result.error as Error).message);return;}const areaId=itemEditor.item.areaId;setItemEditor(null);setNotice('File details updated.');await loadArea(areaId);await loadHome();}
  function beginMove(item:FacilityItem){const destinationArea=areas.find(area=>area.id===item.areaId)??areas[0];setMoveItem(item);setMoveAreaId(String(destinationArea?.id??''));const destination=folders.find(folder=>folder.id!==item.folderId);setMoveFolderId(String(destination?.id??''));setMoveDuplicate(false);setError('');}
  async function saveMove(action=''){if(!moveItem||!moveAreaId||!moveFolderId)return;setBusy(true);setError('');try{await responseJson(await fetch(`${apiBase}/items/${moveItem.id}/move`,{method:'POST',credentials:'include',headers:{'Content-Type':'application/json'},body:JSON.stringify({areaId:Number(moveAreaId),folderId:Number(moveFolderId),duplicateAction:action})}));const areaId=moveItem.areaId;setMoveItem(null);setMoveDuplicate(false);setNotice('File moved.');if(selectedAreaId)await loadArea(selectedAreaId);else if(areaId)await loadArea(areaId);await loadHome();}catch(value){const moveError=value as ApiError;if(moveError.code==='FACILITY_DUPLICATE')setMoveDuplicate(true);else setError(moveError.message);}finally{setBusy(false);}}
  async function deleteItem(item:FacilityItem){if(!window.confirm(`Delete “${item.displayFilename}”?`))return;try{await responseJson(await fetch(`${apiBase}/items/${item.id}`,{method:'DELETE',credentials:'include'}));setNotice(`Deleted: ${item.displayFilename}`);if(selectedAreaId)await loadArea(selectedAreaId);await loadHome();}catch(value){setError((value as Error).message);}}
  function openItem(item:FacilityItem){if(item.mediaType==='picture'||item.mediaType==='video')setViewerItem(item);else if(item.extension==='.pdf')window.open(item.contentUrl,'_blank','noopener,noreferrer');else triggerDownload(item.downloadUrl,item.displayFilename);}
  async function printItem(item:FacilityItem){
    if(item.mediaType==='video')return;
    if(item.extension==='.pdf'){window.open(item.contentUrl,'_blank','noopener,noreferrer');return;}
    const printWindow=window.open('','_blank');if(!printWindow)return;
    try{
      const response=await fetch(item.contentUrl,{credentials:'include'});if(!response.ok)throw new Error(`Image could not be loaded (${response.status}).`);
      const imageUrl=URL.createObjectURL(await response.blob());
      printWindow.document.write(`<!doctype html><html lang="en"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>${escapeHtml(item.displayFilename)}</title><style>@page{size:Letter portrait;margin:.45in}:root{color-scheme:light}*{box-sizing:border-box}html,body{margin:0;padding:0;background:#fff!important;color:#111!important}body{font-family:Arial,Helvetica,sans-serif;font-size:11pt;line-height:1.35;-webkit-print-color-adjust:exact;print-color-adjust:exact}h1{margin:0 0 .16in;color:#111;font-size:15pt;line-height:1.2;overflow-wrap:anywhere}main{display:flex;align-items:center;justify-content:center;width:100%;height:9.35in;overflow:hidden;border:1px solid #707070;background:#fff}img{display:block;width:auto;height:auto;max-width:100%;max-height:100%;object-fit:contain}@media print{h1,main{break-inside:avoid;page-break-inside:avoid}}</style></head><body data-facility-print="image"><h1>${escapeHtml(item.displayFilename)}</h1><main><img alt="${escapeHtml(item.caption||item.displayFilename)}"></main></body></html>`);
      printWindow.document.close();
      const image=printWindow.document.querySelector<HTMLImageElement>('img');if(!image){URL.revokeObjectURL(imageUrl);printWindow.close();return;}
      const releaseImage=()=>URL.revokeObjectURL(imageUrl);
      image.addEventListener('load',()=>{printWindow.opener=null;printWindow.document.documentElement.dataset.ready='true';printWindow.addEventListener('afterprint',releaseImage,{once:true});printWindow.addEventListener('beforeunload',releaseImage,{once:true});printWindow.print();},{once:true});
      image.addEventListener('error',()=>{printWindow.opener=null;printWindow.document.documentElement.dataset.error='image';releaseImage();},{once:true});
      image.src=imageUrl;
    }catch(value){
      printWindow.opener=null;
      printWindow.document.write(`<!doctype html><html lang="en"><head><meta charset="utf-8"><title>${escapeHtml(item.displayFilename)}</title><style>:root{color-scheme:light}html,body{background:#fff;color:#111;font-family:Arial,Helvetica,sans-serif}</style></head><body data-facility-print="image-error"><h1>Image could not be printed</h1><p>${escapeHtml((value as Error).message)}</p></body></html>`);
      printWindow.document.close();
    }
  }
  function printArea(){if(!selectedArea)return;const printWindow=window.open('','_blank');if(!printWindow)return;const rows=items.map(item=>`<tr><td>${escapeHtml(item.folderPath)}</td><td>${escapeHtml(item.displayFilename)}</td><td>${escapeHtml(item.mediaType)}</td><td>${escapeHtml(formatBytes(item.sizeBytes))}</td><td>${escapeHtml(formatDate(item.uploadedAt))}</td></tr>`).join('');printWindow.document.write(`<!doctype html><html lang="en"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>${escapeHtml(selectedArea.name)} contents</title><style>@page{size:Letter landscape;margin:.45in}:root{color-scheme:light}*{box-sizing:border-box}html,body{margin:0;padding:0;background:#fff!important;color:#111!important}body{font-family:Arial,Helvetica,sans-serif;font-size:9pt;line-height:1.35;-webkit-print-color-adjust:exact;print-color-adjust:exact}h1{margin:0 0 3px;color:#111;font-size:17pt;line-height:1.2;overflow-wrap:anywhere}p{margin:0;color:#303030;font-size:9.5pt;overflow-wrap:anywhere}table{width:100%;table-layout:fixed;border-collapse:collapse;margin-top:.2in;color:#111;background:#fff}col.folder{width:29%}col.name{width:33%}col.type{width:11%}col.size{width:11%}col.uploaded{width:16%}thead{display:table-header-group}th,td{text-align:left;padding:7px 8px;border:1px solid #707070;color:#111;vertical-align:top;font-size:9pt;line-height:1.25;overflow-wrap:anywhere;word-break:normal}th{background:#e8edf2;font-weight:700}td{background:#fff}tbody tr:nth-child(even) td{background:#f7f8fa}tr{break-inside:avoid;page-break-inside:avoid}@media print{table{break-inside:auto}}</style></head><body data-facility-print="content-list"><h1>${escapeHtml(selectedArea.name)}</h1><p>${escapeHtml(locationLine(selectedArea)||selectedArea.description||'Facility Info content list')}</p><table><colgroup><col class="folder"><col class="name"><col class="type"><col class="size"><col class="uploaded"></colgroup><thead><tr><th>Folder</th><th>Name</th><th>Type</th><th>Size</th><th>Uploaded</th></tr></thead><tbody>${rows}</tbody></table><script>window.opener=null;document.documentElement.dataset.ready='true';window.print()<\/script></body></html>`);printWindow.document.close();}

  return <div className="page-stack facility-info-page">
    <MccResponsiveToolbar className="facility-toolbar glass-toolbar">
      {selectedArea&&<button className="secondary-button compact-button glass-button glass-button--secondary" type="button" onClick={()=>{setSelectedAreaId(null);setFolders([]);setItems([]);setSearch('');}}>Back to Facilities</button>}
      <label className="form-field facility-search"><span>Search Facility Info</span><input className="glass-input" value={search} onChange={event=>setSearch(event.target.value)} placeholder="Facility, folder, filename, caption, revision, uploader" /></label>
      <label className="form-field"><span>Type</span><select className="glass-input" value={typeFilter} onChange={event=>setTypeFilter(event.target.value)}><option value="all">All</option><option value="document">Documents</option><option value="picture">Pictures</option><option value="video">Videos</option><option value="file">Other Files</option></select></label>
      <label className="form-field"><span>File Type</span><input className="glass-input" value={fileType} onChange={event=>setFileType(event.target.value)} placeholder="e.g. PDF, MOV, STEP" aria-label="Filter by file extension" /></label>
      <label className="form-field"><span>Sort</span><select className="glass-input" value={sort} onChange={event=>setSort(event.target.value)}><option value="name">Name</option><option value="newest">Newest</option><option value="oldest">Oldest</option><option value="file_type">File Type</option><option value="size">Size</option></select></label>
      {!selectedArea&&permissions.canWrite&&<button className="primary-button compact-button glass-button glass-button--primary" type="button" onClick={()=>setAreaEditor({name:'',description:'',building:'',location:'',department:'',status:'active'})}>Create Facility Area</button>}
    </MccResponsiveToolbar>
    {error&&<p className="form-message error" role="alert">{error}</p>}{notice&&<p className="form-message facility-notice" role="status">{notice}</p>}{loading&&<div className="glass-empty-state">Loading Facility Info...</div>}
    {!loading&&!selectedArea&&!search.trim()&&<><div className="facility-home-heading"><div><p className="eyebrow">Searchable folder and media library</p><h2>Facility Areas</h2></div>{permissions.canRecoveryExport&&<a className="secondary-button compact-button glass-button glass-button--secondary" href={`${apiBase}/recovery-export`} download>Full Recovery ZIP</a>}</div><div className="facility-card-grid">{areas.map(area=><MccPillCard className="facility-area-card" variant="info" accentColor="#F3B72F" key={area.id} onActivate={()=>setSelectedAreaId(area.id)} ariaLabel={`Open ${area.name}`}>
      <div className="facility-area-card__heading"><MccFolderIcon size="standard" /><div><strong>{area.name}</strong>{locationLine(area)&&<span>{locationLine(area)}</span>}</div>{area.status!=='active'&&<MccStatusPill variant={area.status==='archived'?'muted':'warning'}>{area.status}</MccStatusPill>}</div>
      {area.description&&<p>{area.description}</p>}<MccSummaryTokenGroup><MccSummaryToken tone="folder">{area.summary.folderCount} folder{area.summary.folderCount===1?'':'s'}</MccSummaryToken><MccSummaryToken tone="document">{area.summary.documentCount} document{area.summary.documentCount===1?'':'s'}</MccSummaryToken><MccSummaryToken tone="attachment">{area.summary.pictureCount} picture{area.summary.pictureCount===1?'':'s'}</MccSummaryToken><MccSummaryToken tone="history">{area.summary.videoCount} video{area.summary.videoCount===1?'':'s'}</MccSummaryToken><MccSummaryToken tone="attachment">{area.summary.fileCount} other file{area.summary.fileCount===1?'':'s'}</MccSummaryToken></MccSummaryTokenGroup>
      <div className="facility-area-card__footer"><span>Updated {formatDate(area.updatedAt)}</span>{permissions.canWrite&&<MccOverflowMenu ariaLabel={`Manage ${area.name}`} items={[{label:'Edit Facility Area',onSelect:()=>setAreaEditor({area,name:area.name,description:area.description,building:area.building,location:area.location,department:area.department,status:area.status})},{label:'Delete Facility Area',onSelect:()=>void deleteArea(area),danger:true}]} />}</div>
    </MccPillCard>)}</div></>}
    {!loading&&!selectedArea&&search.trim()&&<><FacilityContextResults areas={searchAreas} folders={searchFolders} onArea={areaId=>setSelectedAreaId(areaId)} onFolder={(areaId,folderId)=>{setOpenFolders(new Set([folderId]));setSelectedAreaId(areaId);}} /><SearchResults items={visibleItems} searching={searching} canWrite={permissions.canWrite} onOpen={item=>{setSelectedAreaId(item.areaId);openItem(item);}} onDownload={item=>triggerDownload(item.downloadUrl,item.displayFilename)} onEdit={item=>setItemEditor({item,displayFilename:item.displayFilename,description:item.description,caption:item.caption,revision:item.revision,date:item.date})} onMove={beginMove} onDelete={deleteItem} /></>}
    {!loading&&selectedArea&&<section className="facility-area-shell">
      <div className="facility-area-heading"><div><p className="eyebrow">Facility / Area</p><h2>{selectedArea.name}</h2><p>{locationLine(selectedArea)||selectedArea.description||'Facility file and media library'}</p><MccSummaryTokenGroup><MccSummaryToken tone="folder">{selectedArea.summary.folderCount} folders</MccSummaryToken><MccSummaryToken tone="document">{selectedArea.summary.documentCount} documents</MccSummaryToken><MccSummaryToken tone="attachment">{selectedArea.summary.pictureCount} pictures</MccSummaryToken><MccSummaryToken tone="history">{selectedArea.summary.videoCount} videos</MccSummaryToken><MccSummaryToken tone="attachment">{selectedArea.summary.fileCount} other files</MccSummaryToken></MccSummaryTokenGroup></div><MccActionGroup>{permissions.canWrite&&<button className="secondary-button compact-button glass-button glass-button--secondary" type="button" disabled={busy} onClick={()=>beginUpload(null)}>Upload Folder</button>}<button className="secondary-button compact-button glass-button glass-button--secondary" type="button" onClick={printArea}>Print Content List</button><a className="secondary-button compact-button glass-button glass-button--secondary" href={`${apiBase}/areas/${selectedArea.id}/export`} download>Export Facility ZIP</a><MccOverflowMenu items={[...(permissions.canWrite?[{label:'Edit Facility Area',onSelect:()=>setAreaEditor({area:selectedArea,name:selectedArea.name,description:selectedArea.description,building:selectedArea.building,location:selectedArea.location,department:selectedArea.department,status:selectedArea.status})},{label:'Create Folder',onSelect:()=>setFolderEditor({name:'',description:'',parentId:''})}]:[])]} /></MccActionGroup></div>
      {(search.trim()||typeFilter!=='all'||fileType)&&<SearchResults items={visibleItems} searching={searching} canWrite={permissions.canWrite} onOpen={openItem} onDownload={item=>triggerDownload(item.downloadUrl,item.displayFilename)} onEdit={item=>setItemEditor({item,displayFilename:item.displayFilename,description:item.description,caption:item.caption,revision:item.revision,date:item.date})} onMove={beginMove} onDelete={deleteItem} />}
      {!search.trim()&&typeFilter==='all'&&!fileType&&<><div className="facility-view-switch"><span>{folders.length} folder{folders.length===1?'':'s'}</span><div><button className={`secondary-button compact-button glass-button ${viewMode==='list'?'is-selected':'glass-button--secondary'}`} type="button" onClick={()=>setViewMode('list')}>List</button><button className={`secondary-button compact-button glass-button ${viewMode==='gallery'?'is-selected':'glass-button--secondary'}`} type="button" onClick={()=>setViewMode('gallery')}>Gallery</button></div></div>
      {!folders.length&&<div className="glass-empty-state"><strong>No folders yet</strong><span>{permissions.canWrite?'Create a custom folder before uploading Facility files.':'No Facility content has been added.'}</span></div>}
      <div className="facility-folder-list mcc-folder-tree">{orderedFolders.map(({folder,depth})=>{const open=openFolders.has(folder.id);const folderItems=items.filter(item=>item.folderId===folder.id);return <MccFolderTreeItem className="facility-folder-card glass-card glass-card--nested" depth={depth} open={open} key={folder.id}><MccResourceRow className="facility-folder-header" icon={<MccFolderIcon size="compact" open={open} />} title={folder.name} titleText={folder.path} metadata={<><span>{folder.itemCount} file{folder.itemCount===1?'':'s'}</span>{depth>0&&<span>{folder.path}</span>}</>} trailingContent={<MccFolderTreeChevron open={open} />} onActivate={()=>setOpenFolders(current=>{const next=new Set(current);if(next.has(folder.id))next.delete(folder.id);else next.add(folder.id);return next;})} activateLabel={`${open?'Close':'Open'} ${folder.name}`} expanded={open} controls={`facility-folder-${folder.id}`} actions={<MccActionGroup>{permissions.canWrite&&<button className="primary-button compact-button glass-button glass-button--primary" type="button" onClick={()=>beginUpload(folder)}>Upload</button>}<MccOverflowMenu label="Manage" items={[{label:'Export Folder ZIP',onSelect:()=>triggerDownload(`${apiBase}/areas/${folder.areaId}/folders/${folder.id}/export`,`${folder.name}.zip`)},...(permissions.canWrite?[{label:'Create Subfolder',onSelect:()=>setFolderEditor({name:'',description:'',parentId:String(folder.id)})},{label:'Rename / Edit',onSelect:()=>setFolderEditor({folder,name:folder.name,description:folder.description,parentId:String(folder.parentId??'')})},{label:'Delete Empty Folder',onSelect:()=>void deleteFolder(folder),disabled:Boolean(folder.itemCount||folder.childCount),danger:true}]:[])]} /></MccActionGroup>} />{open&&<div className="facility-folder-body" id={`facility-folder-${folder.id}`}>{(folder.description||permissions.canWrite)&&<div className="mcc-folder-content-overview">{folder.description&&<p>{folder.description}</p>}{permissions.canWrite&&<div className="facility-folder-toolbar mcc-folder-content-toolbar" role="toolbar" aria-label={`Add content to ${folder.name}`}><button className="secondary-button compact-button glass-button glass-button--secondary" type="button" onClick={()=>beginUpload(folder)}>Add Files or Folder Here</button></div>}</div>}<div className="mcc-folder-file-content">{!folderItems.length&&<div className="glass-empty-state">No files in this folder.</div>}{viewMode==='gallery'?<Gallery items={folderItems} onOpen={openItem} />:<ItemList items={folderItems} canWrite={permissions.canWrite} onOpen={openItem} onDownload={item=>triggerDownload(item.downloadUrl,item.displayFilename)} onPrint={printItem} onEdit={item=>setItemEditor({item,displayFilename:item.displayFilename,description:item.description,caption:item.caption,revision:item.revision,date:item.date})} onMove={beginMove} onDelete={deleteItem} />}</div></div>}</MccFolderTreeItem>;})}</div></>}</section>}
    {areaEditor&&<AreaModal editor={areaEditor} setEditor={setAreaEditor} busy={areaAction.active} phase={areaAction.phase} error={error} onSave={saveArea} onClose={()=>{areaAction.reset();setAreaEditor(null);setError('');}} />}
    {folderEditor&&selectedArea&&<FolderModal editor={folderEditor} folders={folders} setEditor={setFolderEditor} busy={folderAction.active} phase={folderAction.phase} error={error} onSave={saveFolder} onClose={()=>{folderAction.reset();setFolderEditor(null);setError('');}} />}
    {uploadOpen&&selectedArea&&<LibraryUploadModal eyebrow="Facility Info" title="Upload Files" destination={[selectedArea.name,...(uploadFolder?.path.split(' / ')??['Facility root'])]} files={pendingFiles} limits={limits} busy={busy} error={error} progress={uploadProgress} completedCount={uploadCompleted} currentFile={uploadCurrent} allowLooseFiles={Boolean(uploadFolder)} onPickFiles={files=>addFiles(files)} onPickFolder={files=>addFiles(files,true)} onRemove={index=>setPendingFiles(current=>current.filter((_,itemIndex)=>itemIndex!==index))} metadata={<div className="library-upload-metadata-grid facility-upload-metadata"><label className="form-field library-upload-metadata-wide"><span>Description</span><textarea className="glass-input" rows={3} maxLength={2000} value={uploadMeta.description} onChange={event=>setUploadMeta({...uploadMeta,description:event.target.value})} /></label><label className="form-field"><span>Caption</span><input className="glass-input" maxLength={500} value={uploadMeta.caption} onChange={event=>setUploadMeta({...uploadMeta,caption:event.target.value})} /></label><label className="form-field"><span>Revision</span><input className="glass-input" maxLength={80} value={uploadMeta.revision} onChange={event=>setUploadMeta({...uploadMeta,revision:event.target.value})} /></label><label className="form-field"><span>Date</span><input className="glass-input" type="date" value={uploadMeta.date} onChange={event=>setUploadMeta({...uploadMeta,date:event.target.value})} /></label></div>} conflictActions={duplicate?<DuplicateActions busy={busy} onAction={action=>void submitUpload(action)} onClose={()=>{setUploadOpen(false);setUploadFolder(null);setDuplicate(false);setError('');}} />:undefined} onUpload={()=>void submitUpload()} onClose={()=>{if(busy)return;setUploadOpen(false);setUploadFolder(null);setDuplicate(false);setError('');}} />}
    {itemEditor&&<ItemModal editor={itemEditor} setEditor={setItemEditor} busy={itemAction.active} phase={itemAction.phase} error={error} onSave={saveItem} onClose={()=>{itemAction.reset();setItemEditor(null);setError('');}} />}
    {moveItem&&<MoveModal item={moveItem} areas={areas} folders={folders.filter(folder=>folder.areaId===Number(moveAreaId)&&folder.id!==moveItem.folderId)} areaId={moveAreaId} folderId={moveFolderId} setAreaId={value=>{setMoveAreaId(value);setMoveFolderId('');if(Number(value)!==selectedAreaId)void fetch(`${apiBase}/areas/${value}`,{credentials:'include'}).then(response=>responseJson<{folders:FacilityFolder[]}>(response)).then(data=>setFolders(data.folders));}} setFolderId={setMoveFolderId} duplicate={moveDuplicate} busy={busy} error={error} onMove={saveMove} onClose={()=>{setMoveItem(null);setMoveDuplicate(false);setError('');if(selectedAreaId)void loadArea(selectedAreaId);}} />}
    {viewerItem&&<MediaViewer item={viewerItem} siblings={viewerItem.mediaType==='picture'?pictureViewerItems:videoViewerItems} onSelect={setViewerItem} onDownload={()=>triggerDownload(viewerItem.downloadUrl,viewerItem.displayFilename)} onPrint={()=>printItem(viewerItem)} onClose={()=>setViewerItem(null)} />}
  </div>;
}

function ItemVisual({item,className='',preview=false}:{item:FacilityItem;className?:string;preview?:boolean}){if(preview&&item.mediaType==='video')return <span className={`facility-media-icon facility-media-icon--video ${className}`} aria-hidden="true">{'\u25b6'}</span>;return <MccLibraryFileVisual filename={item.displayFilename} src={item.contentUrl} mimeType={item.mimeType} mediaType={item.mediaType} className={className} thumbnailClassName={preview?'facility-thumbnail facility-thumbnail--gallery':'facility-thumbnail'} />;}
function ItemList({items,canWrite,onOpen,onDownload,onPrint,onEdit,onMove,onDelete}:{items:FacilityItem[];canWrite:boolean;onOpen:(item:FacilityItem)=>void;onDownload:(item:FacilityItem)=>void;onPrint:(item:FacilityItem)=>void;onEdit:(item:FacilityItem)=>void;onMove:(item:FacilityItem)=>void;onDelete:(item:FacilityItem)=>void}){return <div className="facility-item-list">{items.map(item=><MccResourceRow className="facility-item-row mcc-library-file-row glass-attachment" key={item.id} icon={<ItemVisual item={item} />} title={item.displayFilename} titleText={item.displayFilename} secondary={<MccFilePath rootLabel={item.facilityName} path={item.folderPath} />} metadata={<><span>{fileTypeIconLabel(item.displayFilename)}</span><span>{formatBytes(item.sizeBytes)}</span><span>Uploaded {formatDateTime(item.uploadedAt)}</span><span>{item.uploadedBy}</span>{item.revision&&<span className="mcc-library-file-row__revision">Revision {item.revision}</span>}</>} description={item.caption||item.description} actions={<MccActionGroup>{item.mediaType!=='file'&&<button className="secondary-button compact-button glass-button glass-button--secondary" type="button" onClick={()=>onOpen(item)}>Open</button>}<button className="secondary-button compact-button glass-button glass-button--secondary" type="button" onClick={()=>onDownload(item)}>Download</button><MccOverflowMenu ariaLabel={`More actions for ${item.displayFilename}`} items={[...(item.canPrint?[{label:item.mediaType==='picture'?'Print Image':'Print PDF',onSelect:()=>onPrint(item)}]:[]),...(canWrite?[{label:'Rename / Edit',onSelect:()=>onEdit(item)},{label:'Move to Folder',onSelect:()=>onMove(item)},{label:'Delete',onSelect:()=>void onDelete(item),danger:true}]:[])]} /></MccActionGroup>} />)}</div>;}
function Gallery({items,onOpen}:{items:FacilityItem[];onOpen:(item:FacilityItem)=>void}){return <div className="facility-gallery">{items.map(item=><button type="button" className="facility-gallery-card" key={item.id} onClick={()=>onOpen(item)}><span className="facility-gallery-card__visual"><ItemVisual item={item} preview /></span><strong title={item.displayFilename}>{item.displayFilename}</strong><MccFilePath rootLabel={item.facilityName} path={item.folderPath} /><span>{item.mediaType} {'\u00b7'} {formatBytes(item.sizeBytes)}</span></button>)}</div>;}
function FacilityContextResults({areas,folders,onArea,onFolder}:{areas:FacilityArea[];folders:FacilitySearchFolder[];onArea:(areaId:number)=>void;onFolder:(areaId:number,folderId:number)=>void}){if(!areas.length&&!folders.length)return null;return <section className="facility-context-results"><p className="eyebrow">Matching Facilities and folders</p><div>{areas.map(area=><button type="button" key={`area-${area.id}`} onClick={()=>onArea(area.id)}><MccFolderIcon size="compact" /><span><strong>{area.name}</strong><small>{locationLine(area)||area.description||'Facility Area'}</small></span></button>)}{folders.map(folder=><button type="button" key={`folder-${folder.id}`} onClick={()=>onFolder(folder.areaId,folder.id)}><MccFolderIcon size="compact" /><span><strong>{folder.name}</strong><small>{folder.facilityName} / {folder.path}</small></span></button>)}</div></section>;}
function SearchResults({items,searching,canWrite,onOpen,onDownload,onEdit,onMove,onDelete}:{items:FacilityItem[];searching:boolean;canWrite:boolean;onOpen:(item:FacilityItem)=>void;onDownload:(item:FacilityItem)=>void;onEdit:(item:FacilityItem)=>void;onMove:(item:FacilityItem)=>void;onDelete:(item:FacilityItem)=>void}){return <section className="facility-search-results"><div className="facility-home-heading"><div><p className="eyebrow">Global Facility Info search</p><h2>{searching?'Searching...':`${items.length} result${items.length===1?'':'s'}`}</h2></div></div>{!searching&&!items.length&&<div className="glass-empty-state">No Facility files match this search.</div>}<ItemList items={items} canWrite={canWrite} onOpen={onOpen} onDownload={onDownload} onPrint={item=>item.mediaType==='video'?undefined:window.open(item.contentUrl,'_blank','noopener,noreferrer')} onEdit={onEdit} onMove={onMove} onDelete={onDelete} />{items.map(item=><span className="facility-search-context" key={`context-${item.id}`}>{item.facilityName} / {item.folderPath}</span>)}</section>;}

function ModalShell({title,eyebrow='Facility Info',children,onClose}:{title:string;eyebrow?:string;children:ReactNode;onClose:()=>void}){useEffect(()=>{const close=(event:KeyboardEvent)=>{if(event.key==='Escape')onClose();};document.addEventListener('keydown',close);return()=>document.removeEventListener('keydown',close);},[onClose]);return createPortal(<div className="modal-backdrop glass-modal-backdrop" role="presentation" onMouseDown={event=>{if(event.target===event.currentTarget)onClose();}}><section className="mcc-card glass-modal-shell facility-modal mcc-wide-modal" role="dialog" aria-modal="true" aria-label={title}><div className="modal-heading"><div><p className="eyebrow">{eyebrow}</p><h3>{title}</h3></div><button className="link-button compact-button glass-button glass-button--secondary" type="button" onClick={onClose}>Close</button></div>{children}</section></div>,document.body);}
function AreaModal({editor,setEditor,busy,phase,error,onSave,onClose}:{editor:AreaEditor;setEditor:(editor:AreaEditor|null)=>void;busy:boolean;phase:ActionProgressPhase;error:string;onSave:(event:FormEvent)=>void;onClose:()=>void}){return <ModalShell title={editor.area?'Edit Facility Area':'Create Facility Area'} onClose={onClose}><form className="facility-form" onSubmit={onSave}><label className="form-field"><span>Facility / Area Name *</span><input className="glass-input" maxLength={120} value={editor.name} onChange={event=>setEditor({...editor,name:event.target.value})} required autoFocus /></label><label className="form-field facility-form-wide"><span>Description</span><textarea className="glass-input" rows={3} maxLength={2000} value={editor.description} onChange={event=>setEditor({...editor,description:event.target.value})} /></label><label className="form-field"><span>Building</span><input className="glass-input" maxLength={160} value={editor.building} onChange={event=>setEditor({...editor,building:event.target.value})} /></label><label className="form-field"><span>Location</span><input className="glass-input" maxLength={160} value={editor.location} onChange={event=>setEditor({...editor,location:event.target.value})} /></label><label className="form-field"><span>Department</span><input className="glass-input" maxLength={160} value={editor.department} onChange={event=>setEditor({...editor,department:event.target.value})} /></label><label className="form-field"><span>Status</span><select className="glass-input" value={editor.status} onChange={event=>setEditor({...editor,status:event.target.value})}><option value="active">Active</option><option value="archived">Archived</option><option value="disabled">Disabled</option></select></label>{error&&<p className="form-message error facility-form-wide">{error}</p>}<ModalActions busy={busy} phase={phase} onClose={onClose} label={editor.area?'Save Facility':'Create Facility'} pendingLabel={editor.area?'Saving Facility...':'Creating Facility...'} successLabel={editor.area?'Facility Saved':'Facility Created'} /></form></ModalShell>;}
function FolderModal({editor,folders,setEditor,busy,phase,error,onSave,onClose}:{editor:FolderEditor;folders:FacilityFolder[];setEditor:(editor:FolderEditor|null)=>void;busy:boolean;phase:ActionProgressPhase;error:string;onSave:(event:FormEvent)=>void;onClose:()=>void}){return <ModalShell title={editor.folder?'Rename / Edit Folder':'Create Folder'} onClose={onClose}><form className="facility-form" onSubmit={onSave}><label className="form-field"><span>Folder Name *</span><input className="glass-input" maxLength={120} value={editor.name} onChange={event=>setEditor({...editor,name:event.target.value})} required autoFocus /></label><label className="form-field"><span>Parent Folder</span><select className="glass-input" value={editor.parentId} onChange={event=>setEditor({...editor,parentId:event.target.value})}><option value="">Facility root</option>{folders.filter(folder=>folder.id!==editor.folder?.id).map(folder=><option key={folder.id} value={folder.id}>{folder.path}</option>)}</select></label><label className="form-field facility-form-wide"><span>Description</span><textarea className="glass-input" rows={3} maxLength={2000} value={editor.description} onChange={event=>setEditor({...editor,description:event.target.value})} /></label>{error&&<p className="form-message error facility-form-wide">{error}</p>}<ModalActions busy={busy} phase={phase} onClose={onClose} label={editor.folder?'Save Folder':'Create Folder'} pendingLabel={editor.folder?'Saving Folder...':'Creating Folder...'} successLabel={editor.folder?'Folder Saved':'Folder Created'} /></form></ModalShell>;}
function ItemModal({editor,setEditor,busy,phase,error,onSave,onClose}:{editor:ItemEditor;setEditor:(editor:ItemEditor|null)=>void;busy:boolean;phase:ActionProgressPhase;error:string;onSave:(event:FormEvent)=>void;onClose:()=>void}){return <ModalShell title="Rename / Edit File" onClose={onClose}><form className="facility-form" onSubmit={onSave}><label className="form-field facility-form-wide"><span>Display Filename *</span><input className="glass-input" maxLength={180} value={editor.displayFilename} onChange={event=>setEditor({...editor,displayFilename:event.target.value})} required /></label><label className="form-field"><span>Caption</span><input className="glass-input" value={editor.caption} onChange={event=>setEditor({...editor,caption:event.target.value})} /></label><label className="form-field"><span>Revision</span><input className="glass-input" maxLength={80} value={editor.revision} onChange={event=>setEditor({...editor,revision:event.target.value})} /></label><label className="form-field"><span>Date</span><input className="glass-input" type="date" value={editor.date} onChange={event=>setEditor({...editor,date:event.target.value})} /></label><label className="form-field facility-form-wide"><span>Description</span><textarea className="glass-input" rows={3} value={editor.description} onChange={event=>setEditor({...editor,description:event.target.value})} /></label>{error&&<p className="form-message error facility-form-wide">{error}</p>}<ModalActions busy={busy} phase={phase} onClose={onClose} label="Save File" pendingLabel="Saving File..." successLabel="File Saved" /></form></ModalShell>;}
function MoveModal({item,areas,folders,areaId,folderId,setAreaId,setFolderId,duplicate,busy,error,onMove,onClose}:{item:FacilityItem;areas:FacilityArea[];folders:FacilityFolder[];areaId:string;folderId:string;setAreaId:(value:string)=>void;setFolderId:(value:string)=>void;duplicate:boolean;busy:boolean;error:string;onMove:(action?:string)=>void;onClose:()=>void}){return <ModalShell title={`Move ${item.displayFilename}`} onClose={onClose}><div className="facility-form"><label className="form-field"><span>Facility / Area</span><select className="glass-input" value={areaId} onChange={event=>setAreaId(event.target.value)}>{areas.map(area=><option key={area.id} value={area.id}>{area.name}</option>)}</select></label><label className="form-field"><span>Destination Folder</span><select className="glass-input" value={folderId} onChange={event=>setFolderId(event.target.value)}><option value="">Choose folder</option>{folders.map(folder=><option key={folder.id} value={folder.id}>{folder.path}</option>)}</select></label>{error&&<p className="form-message error facility-form-wide">{error}</p>}{duplicate?<DuplicateActions busy={busy} onAction={onMove} onClose={onClose} />:<div className="modal-actions glass-modal__actions facility-form-wide"><button className="secondary-button glass-button glass-button--secondary" type="button" onClick={onClose}>Cancel</button><button className="primary-button glass-button glass-button--primary" type="button" disabled={busy||!folderId} onClick={()=>onMove()}>{busy?'Moving...':'Move to Folder'}</button></div>}</div></ModalShell>;}
function DuplicateActions({busy,onAction,onClose}:{busy:boolean;onAction:(action:string)=>void;onClose:()=>void}){return <div className="machine-document-conflict glass-card glass-card--nested"><strong>A file with this name already exists.</strong><span>Choose Replace, Keep Both, or Cancel.</span><div className="glass-button-group"><button className="danger-button glass-button glass-button--danger" type="button" onClick={()=>onAction('replace')} disabled={busy}>Replace</button><button className="secondary-button glass-button glass-button--secondary" type="button" onClick={()=>onAction('keep_both')} disabled={busy}>Keep Both</button><button className="link-button glass-button glass-button--secondary" type="button" onClick={onClose}>Cancel</button></div></div>;}
function ModalActions({busy,phase,onClose,label,pendingLabel,successLabel}:{busy:boolean;phase:ActionProgressPhase;onClose:()=>void;label:string;pendingLabel:string;successLabel:string}){return <div className="modal-actions glass-modal__actions facility-form-wide"><button className="secondary-button glass-button glass-button--secondary" type="button" onClick={onClose} disabled={busy}>Cancel</button><button className="primary-button glass-button glass-button--primary" type="submit" disabled={busy} aria-busy={phase==='pending'}><ActionButtonProgress phase={phase} idleLabel={label} pendingLabel={pendingLabel} successLabel={successLabel} errorLabel="Try Save" /></button></div>;}
const interactiveViewerTarget='a[href],button,input,select,textarea,summary,video,audio,[contenteditable]:not([contenteditable="false"]),[tabindex]:not([tabindex="-1"]),[role="button"],[role="checkbox"],[role="combobox"],[role="link"],[role="listbox"],[role="menuitem"],[role="option"],[role="radio"],[role="slider"],[role="spinbutton"],[role="switch"],[role="tab"],[role="textbox"],[role="treeitem"]';
function MediaViewer({item,siblings,onSelect,onDownload,onPrint,onClose}:{item:FacilityItem;siblings:FacilityItem[];onSelect:(item:FacilityItem)=>void;onDownload:()=>void;onPrint:()=>void;onClose:()=>void}){
  const [zoom,setZoom]=useState(1);
  const [mediaError,setMediaError]=useState(false);
  const index=Math.max(0,siblings.findIndex(candidate=>candidate.id===item.id));
  useEffect(()=>{setZoom(1);setMediaError(false);},[item.id]);
  useEffect(()=>{
    const key=(event:KeyboardEvent)=>{
      if(event.key==='Escape'){onClose();return;}
      if(event.key!=='ArrowLeft'&&event.key!=='ArrowRight')return;
      if(event.target instanceof Element&&event.target.closest(interactiveViewerTarget))return;
      if(!siblings.length)return;
      if(event.key==='ArrowLeft')onSelect(siblings[(index-1+siblings.length)%siblings.length]);
      if(event.key==='ArrowRight')onSelect(siblings[(index+1)%siblings.length]);
    };
    document.addEventListener('keydown',key);
    return()=>document.removeEventListener('keydown',key);
  },[index,onClose,onSelect,siblings]);
  return createPortal(
    <div className="facility-viewer" role="dialog" aria-modal="true" aria-label={item.displayFilename}>
      <header>
        <div><strong>{item.displayFilename}</strong><span>{item.facilityName} / {item.folderPath}</span></div>
        <MccActionGroup>
          {siblings.length>1&&<>
            <button className="secondary-button compact-button glass-button glass-button--secondary" type="button" onClick={()=>onSelect(siblings[(index-1+siblings.length)%siblings.length])}>Previous</button>
            <button className="secondary-button compact-button glass-button glass-button--secondary" type="button" onClick={()=>onSelect(siblings[(index+1)%siblings.length])}>Next</button>
          </>}
          {item.mediaType==='picture'&&<>
            <button aria-label="Zoom out" className="secondary-button compact-button glass-button glass-button--secondary" type="button" onClick={()=>setZoom(value=>Math.max(.25,value-.25))}>−</button>
            <button className="secondary-button compact-button glass-button glass-button--secondary" type="button" onClick={()=>setZoom(1)}>Fit</button>
            <button aria-label="Zoom in" className="secondary-button compact-button glass-button glass-button--secondary" type="button" onClick={()=>setZoom(value=>Math.min(4,value+.25))}>+</button>
          </>}
          <button className="secondary-button compact-button glass-button glass-button--secondary" type="button" onClick={onDownload}>Download</button>
          {item.mediaType==='picture'&&<button className="secondary-button compact-button glass-button glass-button--secondary" type="button" onClick={onPrint}>Print</button>}
          <button className="primary-button compact-button glass-button glass-button--primary" type="button" onClick={onClose}>Close</button>
        </MccActionGroup>
      </header>
      <main>
        {item.mediaType==='picture'
          ?<img src={item.contentUrl} alt={item.caption||item.displayFilename} style={{transform:`scale(${zoom})`}} />
          :<div className="facility-video-stage"><video key={item.id} src={item.contentUrl} controls playsInline preload="metadata" onError={()=>setMediaError(true)}>This browser cannot play the video codec.</video>{mediaError&&<div className="facility-video-error" role="alert"><strong>This browser cannot play the video codec.</strong><span>MCC keeps the original unchanged and does not transcode it.</span><a className="primary-button compact-button glass-button glass-button--primary" href={item.downloadUrl} download>Download / Open Original</a></div>}</div>}
      </main>
      <footer><span>{item.caption||item.description||'No caption'}</span><span>{formatBytes(item.sizeBytes)} · Uploaded {formatDateTime(item.uploadedAt)} by {item.uploadedBy}</span></footer>
    </div>,
    document.body,
  );
}
function escapeHtml(value:string){return value.replace(/[&<>"']/g,character=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[character]!));}
